In [1]:
!git clone https://github.com/X-PLUG/mPLUG-DocOwl.git

Cloning into 'mPLUG-DocOwl'...
remote: Enumerating objects: 879, done.
remote: Counting objects: 100% (87/87), done.
remote: Compressing objects: 100% (40/40), done.
remote: Total 879 (delta 56), reused 62 (delta 47), pack-reused 792 (from 1)
Receiving objects: 100% (879/879), 107.21 MiB | 34.88 MiB/s, done.
Resolving deltas: 100% (382/382), done.

In [2]:
!pip install --no-deps --q \
"bitsandbytes==0.48.1" \
"transformers==4.37.2" \
"tokenizers==0.15.1" \
"accelerate==0.27.0" \
"peft==0.4.0" \
"einops==0.6.1" \
"einops-exts==0.0.4" \
"sentencepiece==0.1.99" \
"timm==0.6.13" \
"huggingface-hub==0.36.2" \
shortuuid sacrebleu portalocker

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 129.4/129.4 kB 3.4 MB/s eta 0:00:00a 0:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.6/2.6 MB 43.6 MB/s eta 0:00:00a 0:00:01
  Preparing metadata (setup.py) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.1/60.1 MB 32.1 MB/s eta 0:00:00:00:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.4/8.4 MB 97.6 MB/s eta 0:00:00:00:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.6/3.6 MB 34.8 MB/s eta 0:00:0000:0100:01m
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 279.7/279.7 kB 13.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 72.9/72.9 kB 3.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.2/42.2 kB 1.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 549.1/549.1 kB 25.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 566.4/566.4 kB 22.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100.8/100.8 kB 5.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 129.6/129.6 kB 7.2 MB/s eta 0:00:00
  Building wheel for sentencepiece (setup.py) ... done

In [3]:
import transformers
import peft
import accelerate
   
print("transformers:", transformers.__version__)
print("peft:", peft.__version__)
print("accelerate:", accelerate.__version__)

transformers: 4.37.2
peft: 0.4.0
accelerate: 0.27.0

In [4]:
%cd /kaggle/working/mPLUG-DocOwl/TinyChart

/kaggle/working/mPLUG-DocOwl/TinyChart

In [5]:
import torch
from peft import PeftModel
from PIL import Image
from tinychart.model.builder import load_pretrained_model
from tinychart.mm_utils import get_model_name_from_path
from tinychart.eval.run_tiny_chart import inference_model
from tinychart.eval.eval_metric import parse_model_output, evaluate_cmds

2026-10-05 15:30:20.987142: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1791214221.142845      58 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1791214221.192486      58 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1791214221.588954      58 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1791214221.589001      58 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1791214221.589004      58 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1791214221.589006      58 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.

In [ ]:
# HF_TOKEN =

In [7]:
from huggingface_hub import login
from kaggle_secrets import UserSecretsClient
secret_label = "HF_TOKEN"
secret_value = UserSecretsClient().get_secret(secret_label)

login(token=secret_value)

In [22]:
# from huggingface_hub import HfApi

# api = HfApi()

# api.delete_folder(
#     repo_id="shiinn97/tinychart3B-indochartqa",
#     repo_type="model",
#     path_in_repo="eval",
#     commit_message="Remove eval folder"
# )

HfHubHTTPError: 429 Client Error: Too Many Requests for url: https://huggingface.co/api/models/shiinn97/tinychart3B-indochartqa/commit/main (Request ID: Root=1-6a690cfa-1a4825c448afa81f5f37f19a;06453ba3-99d1-4e8d-ba69-3d1009f93579)

You have exceeded the rate limit for repository commits (128 per hour). You can retry this action in 29 minutes. To reduce the number of commits, you can upload entire folders at once using the Hub Python library: https://huggingface.co/docs/huggingface_hub/guides/upload#upload-a-folder or for large folders: https://huggingface.co/docs/huggingface_hub/guides/upload#upload-a-large-folder. To increase your rate limit for this action, you can upgrade to a paid plan at https://huggingface.co/pricing.

In [8]:
base_model = "mPLUG/TinyChart-3B-768"
lora_model = "shiinn97/tinychart3B-indochartqav2"

from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained(
    "shiinn97/tinychart3B-indochartqav2",
    token=HF_TOKEN
)

tokenizer, model, image_processor, context_len = load_pretrained_model(
    base_model,
    model_base=None,
    model_name=get_model_name_from_path(base_model),
    device="cuda"
)


model = PeftModel.from_pretrained(
    model,
    lora_model,
    token=HF_TOKEN,
)

model = model.merge_and_unload()
model.eval()

/usr/local/lib/python3.12/dist-packages/huggingface_hub/file_download.py:949: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

added_tokens.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/473 [00:00<?, ?B/s]

Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

added_tokens.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/473 [00:00<?, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.

config.json: 0.00B [00:00, ?B/s]

model.safetensors.index.json: 0.00B [00:00, ?B/s]

Downloading shards:   0%|          | 0/3 [00:00<?, ?it/s]

model-00001-of-00003.safetensors:   0%|          | 0.00/4.98G [00:00<?, ?B/s]

model-00002-of-00003.safetensors:   0%|          | 0.00/4.98G [00:00<?, ?B/s]

model-00003-of-00003.safetensors:   0%|          | 0.00/2.79G [00:00<?, ?B/s]

config.json:   0%|          | 0.00/488 [00:00<?, ?B/s]

Loading checkpoint shards:   0%|          | 0/3 [00:00<?, ?it/s]

Some weights of the model checkpoint at mPLUG/TinyChart-3B-768 were not used when initializing TinyChartPhiForCausalLM: ['model.vision_tower.vision_tower.vision_model.embeddings.patch_embedding.bias', 'model.vision_tower.vision_tower.vision_model.embeddings.patch_embedding.weight', 'model.vision_tower.vision_tower.vision_model.embeddings.position_embedding.weight', 'model.vision_tower.vision_tower.vision_model.encoder.layers.0.layer_norm1.bias', 'model.vision_tower.vision_tower.vision_model.encoder.layers.0.layer_norm1.weight', 'model.vision_tower.vision_tower.vision_model.encoder.layers.0.layer_norm2.bias', 'model.vision_tower.vision_tower.vision_model.encoder.layers.0.layer_norm2.weight', 'model.vision_tower.vision_tower.vision_model.encoder.layers.0.mlp.fc1.bias', 'model.vision_tower.vision_tower.vision_model.encoder.layers.0.mlp.fc1.weight', 'model.vision_tower.vision_tower.vision_model.encoder.layers.0.mlp.fc2.bias', 'model.vision_tower.vision_tower.vision_model.encoder.layers.0.mlp.fc2.weight', 'model.vision_tower.vision_tower.vision_model.encoder.layers.0.self_attn.k_proj.bias', 'model.vision_tower.vision_tower.vision_model.encoder.layers.0.self_attn.k_proj.weight', 'model.vision_tower.vision_tower.vision_model.encoder.layers.0.self_attn.out_proj.bias', 'model.vision_tower.vision_tower.vision_model.encoder.layers.0.self_attn.out_proj.weight', 'model.vision_tower.vision_tower.vision_model.encoder.layers.0.self_attn.q_proj.bias', 'model.vision_tower.vision_tower.vision_model.encoder.layers.0.self_attn.q_proj.weight', 'model.vision_tower.vision_tower.vision_model.encoder.layers.0.self_attn.v_proj.bias', 'model.vision_tower.vision_tower.vision_model.encoder.layers.0.self_attn.v_proj.weight', 'model.vision_tower.vision_tower.vision_model.encoder.layers.1.layer_norm1.bias', 'model.vision_tower.vision_tower.vision_model.encoder.layers.1.layer_norm1.weight', 'model.vision_tower.vision_tower.vision_model.encoder.layers.1.layer_norm2.bias', 'model.vision_tower.vision_tower.vision_model.encoder.layers.1.layer_norm2.weight', 'model.vision_tower.vision_tower.vision_model.encoder.layers.1.mlp.fc1.bias', 'model.vision_tower.vision_tower.vision_model.encoder.layers.1.mlp.fc1.weight', 'model.vision_tower.vision_tower.vision_model.encoder.layers.1.mlp.fc2.bias', 'model.vision_tower.vision_tower.vision_model.encoder.layers.1.mlp.fc2.weight', 'model.vision_tower.vision_tower.vision_model.encoder.layers.1.self_attn.k_proj.bias', 'model.vision_tower.vision_tower.vision_model.encoder.layers.1.self_attn.k_proj.weight', 'model.vision_tower.vision_tower.vision_model.encoder.layers.1.self_attn.out_proj.bias', 'model.vision_tower.vision_tower.vision_model.encoder.layers.1.self_attn.out_proj.weight', 'model.vision_tower.vision_tower.vision_model.encoder.layers.1.self_attn.q_proj.bias', 'model.vision_tower.vision_tower.vision_model.encoder.layers.1.self_attn.q_proj.weight', 'model.vision_tower.vision_tower.vision_model.encoder.layers.1.self_attn.v_proj.bias', 'model.vision_tower.vision_tower.vision_model.encoder.layers.1.self_attn.v_proj.weight', 'model.vision_tower.vision_tower.vision_model.encoder.layers.10.layer_norm1.bias', 'model.vision_tower.vision_tower.vision_model.encoder.layers.10.layer_norm1.weight', 'model.vision_tower.vision_tower.vision_model.encoder.layers.10.layer_norm2.bias', 'model.vision_tower.vision_tower.vision_model.encoder.layers.10.layer_norm2.weight', 'model.vision_tower.vision_tower.vision_model.encoder.layers.10.mlp.fc1.bias', 'model.vision_tower.vision_tower.vision_model.encoder.layers.10.mlp.fc1.weight', 'model.vision_tower.vision_tower.vision_model.encoder.layers.10.mlp.fc2.bias', 'model.vision_tower.vision_tower.vision_model.encoder.layers.10.mlp.fc2.weight', 'model.vision_tower.vision_tower.vision_model.encoder.layers.10.self_attn.k_proj.bias', 'model.vision_tower.vision_tower.vision_model.encoder.layers.10.self_attn.k_proj.weight', 'model.vision_tower.vision_tower.vision_model.encoder.layers.10.self_attn.out_proj.bias', 'model.vision_tower.vision_tower.vision_model.encoder.layers.10.self_attn.out_proj.weight', 'model.vision_tower.vision_tower.vision_model.encoder.layers.10.self_attn.q_proj.bias', 'model.vision_tower.vision_tower.vision_model.encoder.layers.10.self_attn.q_proj.weight', 'model.vision_tower.vision_tower.vision_model.encoder.layers.10.self_attn.v_proj.bias', 'model.vision_tower.vision_tower.vision_model.encoder.layers.10.self_attn.v_proj.weight', 'model.vision_tower.vision_tower.vision_model.encoder.layers.11.layer_norm1.bias', 'model.vision_tower.vision_tower.vision_model.encoder.layers.11.layer_norm1.weight', 'model.vision_tower.vision_tower.vision_model.encoder.layers.11.layer_norm2.bias', 'model.vision_tower.vision_tower.vision_model.encoder.layers.11.layer_norm2.weight', 'model.vision_tower.vision_tower.vision_model.encoder.layers.11.mlp.fc1.bias', 'model.vision_tower.vision_tower.vision_model.encoder.layers.11.mlp.fc1.weight', 'model.vision_tower.vision_tower.vision_model.encoder.layers.11.mlp.fc2.bias', 'model.vision_tower.vision_tower.vision_model.encoder.layers.11.mlp.fc2.weight', 'model.vision_tower.vision_tower.vision_model.encoder.layers.11.self_attn.k_proj.bias', 'model.vision_tower.vision_tower.vision_model.encoder.layers.11.self_attn.k_proj.weight', 'model.vision_tower.vision_tower.vision_model.encoder.layers.11.self_attn.out_proj.bias', 'model.vision_tower.vision_tower.vision_model.encoder.layers.11.self_attn.out_proj.weight', 'model.vision_tower.vision_tower.vision_model.encoder.layers.11.self_attn.q_proj.bias', 'model.vision_tower.vision_tower.vision_model.encoder.layers.11.self_attn.q_proj.weight', 'model.vision_tower.vision_tower.vision_model.encoder.layers.11.self_attn.v_proj.bias', 'model.vision_tower.vision_tower.vision_model.encoder.layers.11.self_attn.v_proj.weight', 'model.vision_tower.vision_tower.vision_model.encoder.layers.12.layer_norm1.bias', 'model.vision_tower.vision_tower.vision_model.encoder.layers.12.layer_norm1.weight', 'model.vision_tower.vision_tower.vision_model.encoder.layers.12.layer_norm2.bias', 'model.vision_tower.vision_tower.vision_model.encoder.layers.12.layer_norm2.weight', 'model.vision_tower.vision_tower.vision_model.encoder.layers.12.mlp.fc1.bias', 'model.vision_tower.vision_tower.vision_model.encoder.layers.12.mlp.fc1.weight', 'model.vision_tower.vision_tower.vision_model.encoder.layers.12.mlp.fc2.bias', 'model.vision_tower.vision_tower.vision_model.encoder.layers.12.mlp.fc2.weight', 'model.vision_tower.vision_tower.vision_model.encoder.layers.12.self_attn.k_proj.bias', 'model.vision_tower.vision_tower.vision_model.encoder.layers.12.self_attn.k_proj.weight', 'model.vision_tower.vision_tower.vision_model.encoder.layers.12.self_attn.out_proj.bias', 'model.vision_tower.vision_tower.vision_model.encoder.layers.12.self_attn.out_proj.weight', 'model.vision_tower.vision_tower.vision_model.encoder.layers.12.self_attn.q_proj.bias', 'model.vision_tower.vision_tower.vision_model.encoder.layers.12.self_attn.q_proj.weight', 'model.vision_tower.vision_tower.vision_model.encoder.layers.12.self_attn.v_proj.bias', 'model.vision_tower.vision_tower.vision_model.encoder.layers.12.self_attn.v_proj.weight', 'model.vision_tower.vision_tower.vision_model.encoder.layers.13.layer_norm1.bias', 'model.vision_tower.vision_tower.vision_model.encoder.layers.13.layer_norm1.weight', 'model.vision_tower.vision_tower.vision_model.encoder.layers.13.layer_norm2.bias', 'model.vision_tower.vision_tower.vision_model.encoder.layers.13.layer_norm2.weight', 'model.vision_tower.vision_tower.vision_model.encoder.layers.13.mlp.fc1.bias', 'model.vision_tower.vision_tower.vision_model.encoder.layers.13.mlp.fc1.weight', 'model.vision_tower.vision_tower.vision_model.encoder.layers.13.mlp.fc2.bias', 'model.vision_tower.vision_tower.vision_model.encoder.layers.13.mlp.fc2.weight', 'model.vision_tower.vision_tower.vision_model.encoder.layers.13.self_attn.k_proj.bias', 'model.vision_tower.vision_tower.vision_model.encoder.layers.13.self_attn.k_proj.weight', 'model.vision_tower.vision_tower.vision_model.encoder.layers.13.self_attn.out_proj.bias', 'model.vision_tower.vision_tower.vision_model.encoder.layers.13.self_attn.out_proj.weight', 'model.vision_tower.vision_tower.vision_model.encoder.layers.13.self_attn.q_proj.bias', 'model.vision_tower.vision_tower.vision_model.encoder.layers.13.self_attn.q_proj.weight', 'model.vision_tower.vision_tower.vision_model.encoder.layers.13.self_attn.v_proj.bias', 'model.vision_tower.vision_tower.vision_model.encoder.layers.13.self_attn.v_proj.weight', 'model.vision_tower.vision_tower.vision_model.encoder.layers.14.layer_norm1.bias', 'model.vision_tower.vision_tower.vision_model.encoder.layers.14.layer_norm1.weight', 'model.vision_tower.vision_tower.vision_model.encoder.layers.14.layer_norm2.bias', 'model.vision_tower.vision_tower.vision_model.encoder.layers.14.layer_norm2.weight', 'model.vision_tower.vision_tower.vision_model.encoder.layers.14.mlp.fc1.bias', 'model.vision_tower.vision_tower.vision_model.encoder.layers.14.mlp.fc1.weight', 'model.vision_tower.vision_tower.vision_model.encoder.layers.14.mlp.fc2.bias', 'model.vision_tower.vision_tower.vision_model.encoder.layers.14.mlp.fc2.weight', 'model.vision_tower.vision_tower.vision_model.encoder.layers.14.self_attn.k_proj.bias', 'model.vision_tower.vision_tower.vision_model.encoder.layers.14.self_attn.k_proj.weight', 'model.vision_tower.vision_tower.vision_model.encoder.layers.14.self_attn.out_proj.bias', 'model.vision_tower.vision_tower.vision_model.encoder.layers.14.self_attn.out_proj.weight', 'model.vision_tower.vision_tower.vision_model.encoder.layers.14.self_attn.q_proj.bias', 'model.vision_tower.vision_tower.vision_model.encoder.layers.14.self_attn.q_proj.weight', 'model.vision_tower.vision_tower.vision_model.encoder.layers.14.self_attn.v_proj.bias', 'model.vision_tower.vision_tower.vision_model.encoder.layers.14.self_attn.v_proj.weight', 'model.vision_tower.vision_tower.vision_model.encoder.layers.15.layer_norm1.bias', 'model.vision_tower.vision_tower.vision_model.encoder.layers.15.layer_norm1.weight', 'model.vision_tower.vision_tower.vision_model.encoder.layers.15.layer_norm2.bias', 'model.vision_tower.vision_tower.vision_model.encoder.layers.15.layer_norm2.weight', 'model.vision_tower.vision_tower.vision_model.encoder.layers.15.mlp.fc1.bias', 'model.vision_tower.vision_tower.vision_model.encoder.layers.15.mlp.fc1.weight', 'model.vision_tower.vision_tower.vision_model.encoder.layers.15.mlp.fc2.bias', 'model.vision_tower.vision_tower.vision_model.encoder.layers.15.mlp.fc2.weight', 'model.vision_tower.vision_tower.vision_model.encoder.layers.15.self_attn.k_proj.bias', 'model.vision_tower.vision_tower.vision_model.encoder.layers.15.self_attn.k_proj.weight', 'model.vision_tower.vision_tower.vision_model.encoder.layers.15.self_attn.out_proj.bias', 'model.vision_tower.vision_tower.vision_model.encoder.layers.15.self_attn.out_proj.weight', 'model.vision_tower.vision_tower.vision_model.encoder.layers.15.self_attn.q_proj.bias', 'model.vision_tower.vision_tower.vision_model.encoder.layers.15.self_attn.q_proj.weight', 'model.vision_tower.vision_tower.vision_model.encoder.layers.15.self_attn.v_proj.bias', 'model.vision_tower.vision_tower.vision_model.encoder.layers.15.self_attn.v_proj.weight', 'model.vision_tower.vision_tower.vision_model.encoder.layers.16.layer_norm1.bias', 'model.vision_tower.vision_tower.vision_model.encoder.layers.16.layer_norm1.weight', 'model.vision_tower.vision_tower.vision_model.encoder.layers.16.layer_norm2.bias', 'model.vision_tower.vision_tower.vision_model.encoder.layers.16.layer_norm2.weight', 'model.vision_tower.vision_tower.vision_model.encoder.layers.16.mlp.fc1.bias', 'model.vision_tower.vision_tower.vision_model.encoder.layers.16.mlp.fc1.weight', 'model.vision_tower.vision_tower.vision_model.encoder.layers.16.mlp.fc2.bias', 'model.vision_tower.vision_tower.vision_model.encoder.layers.16.mlp.fc2.weight', 'model.vision_tower.vision_tower.vision_model.encoder.layers.16.self_attn.k_proj.bias', 'model.vision_tower.vision_tower.vision_model.encoder.layers.16.self_attn.k_proj.weight', 'model.vision_tower.vision_tower.vision_model.encoder.layers.16.self_attn.out_proj.bias', 'model.vision_tower.vision_tower.vision_model.encoder.layers.16.self_attn.out_proj.weight', 'model.vision_tower.vision_tower.vision_model.encoder.layers.16.self_attn.q_proj.bias', 'model.vision_tower.vision_tower.vision_model.encoder.layers.16.self_attn.q_proj.weight', 'model.vision_tower.vision_tower.vision_model.encoder.layers.16.self_attn.v_proj.bias', 'model.vision_tower.vision_tower.vision_model.encoder.layers.16.self_attn.v_proj.weight', 'model.vision_tower.vision_tower.vision_model.encoder.layers.17.layer_norm1.bias', 'model.vision_tower.vision_tower.vision_model.encoder.layers.17.layer_norm1.weight', 'model.vision_tower.vision_tower.vision_model.encoder.layers.17.layer_norm2.bias', 'model.vision_tower.vision_tower.vision_model.encoder.layers.17.layer_norm2.weight', 'model.vision_tower.vision_tower.vision_model.encoder.layers.17.mlp.fc1.bias', 'model.vision_tower.vision_tower.vision_model.encoder.layers.17.mlp.fc1.weight', 'model.vision_tower.vision_tower.vision_model.encoder.layers.17.mlp.fc2.bias', 'model.vision_tower.vision_tower.vision_model.encoder.layers.17.mlp.fc2.weight', 'model.vision_tower.vision_tower.vision_model.encoder.layers.17.self_attn.k_proj.bias', 'model.vision_tower.vision_tower.vision_model.encoder.layers.17.self_attn.k_proj.weight', 'model.vision_tower.vision_tower.vision_model.encoder.layers.17.self_attn.out_proj.bias', 'model.vision_tower.vision_tower.vision_model.encoder.layers.17.self_attn.out_proj.weight', 'model.vision_tower.vision_tower.vision_model.encoder.layers.17.self_attn.q_proj.bias', 'model.vision_tower.vision_tower.vision_model.encoder.layers.17.self_attn.q_proj.weight', 'model.vision_tower.vision_tower.vision_model.encoder.layers.17.self_attn.v_proj.bias', 'model.vision_tower.vision_tower.vision_model.encoder.layers.17.self_attn.v_proj.weight', 'model.vision_tower.vision_tower.vision_model.encoder.layers.18.layer_norm1.bias', 'model.vision_tower.vision_tower.vision_model.encoder.layers.18.layer_norm1.weight', 'model.vision_tower.vision_tower.vision_model.encoder.layers.18.layer_norm2.bias', 'model.vision_tower.vision_tower.vision_model.encoder.layers.18.layer_norm2.weight', 'model.vision_tower.vision_tower.vision_model.encoder.layers.18.mlp.fc1.bias', 'model.vision_tower.vision_tower.vision_model.encoder.layers.18.mlp.fc1.weight', 'model.vision_tower.vision_tower.vision_model.encoder.layers.18.mlp.fc2.bias', 'model.vision_tower.vision_tower.vision_model.encoder.layers.18.mlp.fc2.weight', 'model.vision_tower.vision_tower.vision_model.encoder.layers.18.self_attn.k_proj.bias', 'model.vision_tower.vision_tower.vision_model.encoder.layers.18.self_attn.k_proj.weight', 'model.vision_tower.vision_tower.vision_model.encoder.layers.18.self_attn.out_proj.bias', 'model.vision_tower.vision_tower.vision_model.encoder.layers.18.self_attn.out_proj.weight', 'model.vision_tower.vision_tower.vision_model.encoder.layers.18.self_attn.q_proj.bias', 'model.vision_tower.vision_tower.vision_model.encoder.layers.18.self_attn.q_proj.weight', 'model.vision_tower.vision_tower.vision_model.encoder.layers.18.self_attn.v_proj.bias', 'model.vision_tower.vision_tower.vision_model.encoder.layers.18.self_attn.v_proj.weight', 'model.vision_tower.vision_tower.vision_model.encoder.layers.19.layer_norm1.bias', 'model.vision_tower.vision_tower.vision_model.encoder.layers.19.layer_norm1.weight', 'model.vision_tower.vision_tower.vision_model.encoder.layers.19.layer_norm2.bias', 'model.vision_tower.vision_tower.vision_model.encoder.layers.19.layer_norm2.weight', 'model.vision_tower.vision_tower.vision_model.encoder.layers.19.mlp.fc1.bias', 'model.vision_tower.vision_tower.vision_model.encoder.layers.19.mlp.fc1.weight', 'model.vision_tower.vision_tower.vision_model.encoder.layers.19.mlp.fc2.bias', 'model.vision_tower.vision_tower.vision_model.encoder.layers.19.mlp.fc2.weight', 'model.vision_tower.vision_tower.vision_model.encoder.layers.19.self_attn.k_proj.bias', 'model.vision_tower.vision_tower.vision_model.encoder.layers.19.self_attn.k_proj.weight', 'model.vision_tower.vision_tower.vision_model.encoder.layers.19.self_attn.out_proj.bias', 'model.vision_tower.vision_tower.vision_model.encoder.layers.19.self_attn.out_proj.weight', 'model.vision_tower.vision_tower.vision_model.encoder.layers.19.self_attn.q_proj.bias', 'model.vision_tower.vision_tower.vision_model.encoder.layers.19.self_attn.q_proj.weight', 'model.vision_tower.vision_tower.vision_model.encoder.layers.19.self_attn.v_proj.bias', 'model.vision_tower.vision_tower.vision_model.encoder.layers.19.self_attn.v_proj.weight', 'model.vision_tower.vision_tower.vision_model.encoder.layers.2.layer_norm1.bias', 'model.vision_tower.vision_tower.vision_model.encoder.layers.2.layer_norm1.weight', 'model.vision_tower.vision_tower.vision_model.encoder.layers.2.layer_norm2.bias', 'model.vision_tower.vision_tower.vision_model.encoder.layers.2.layer_norm2.weight', 'model.vision_tower.vision_tower.vision_model.encoder.layers.2.mlp.fc1.bias', 'model.vision_tower.vision_tower.vision_model.encoder.layers.2.mlp.fc1.weight', 'model.vision_tower.vision_tower.vision_model.encoder.layers.2.mlp.fc2.bias', 'model.vision_tower.vision_tower.vision_model.encoder.layers.2.mlp.fc2.weight', 'model.vision_tower.vision_tower.vision_model.encoder.layers.2.self_attn.k_proj.bias', 'model.vision_tower.vision_tower.vision_model.encoder.layers.2.self_attn.k_proj.weight', 'model.vision_tower.vision_tower.vision_model.encoder.layers.2.self_attn.out_proj.bias', 'model.vision_tower.vision_tower.vision_model.encoder.layers.2.self_attn.out_proj.weight', 'model.vision_tower.vision_tower.vision_model.encoder.layers.2.self_attn.q_proj.bias', 'model.vision_tower.vision_tower.vision_model.encoder.layers.2.self_attn.q_proj.weight', 'model.vision_tower.vision_tower.vision_model.encoder.layers.2.self_attn.v_proj.bias', 'model.vision_tower.vision_tower.vision_model.encoder.layers.2.self_attn.v_proj.weight', 'model.vision_tower.vision_tower.vision_model.encoder.layers.20.layer_norm1.bias', 'model.vision_tower.vision_tower.vision_model.encoder.layers.20.layer_norm1.weight', 'model.vision_tower.vision_tower.vision_model.encoder.layers.20.layer_norm2.bias', 'model.vision_tower.vision_tower.vision_model.encoder.layers.20.layer_norm2.weight', 'model.vision_tower.vision_tower.vision_model.encoder.layers.20.mlp.fc1.bias', 'model.vision_tower.vision_tower.vision_model.encoder.layers.20.mlp.fc1.weight', 'model.vision_tower.vision_tower.vision_model.encoder.layers.20.mlp.fc2.bias', 'model.vision_tower.vision_tower.vision_model.encoder.layers.20.mlp.fc2.weight', 'model.vision_tower.vision_tower.vision_model.encoder.layers.20.self_attn.k_proj.bias', 'model.vision_tower.vision_tower.vision_model.encoder.layers.20.self_attn.k_proj.weight', 'model.vision_tower.vision_tower.vision_model.encoder.layers.20.self_attn.out_proj.bias', 'model.vision_tower.vision_tower.vision_model.encoder.layers.20.self_attn.out_proj.weight', 'model.vision_tower.vision_tower.vision_model.encoder.layers.20.self_attn.q_proj.bias', 'model.vision_tower.vision_tower.vision_model.encoder.layers.20.self_attn.q_proj.weight', 'model.vision_tower.vision_tower.vision_model.encoder.layers.20.self_attn.v_proj.bias', 'model.vision_tower.vision_tower.vision_model.encoder.layers.20.self_attn.v_proj.weight', 'model.vision_tower.vision_tower.vision_model.encoder.layers.21.layer_norm1.bias', 'model.vision_tower.vision_tower.vision_model.encoder.layers.21.layer_norm1.weight', 'model.vision_tower.vision_tower.vision_model.encoder.layers.21.layer_norm2.bias', 'model.vision_tower.vision_tower.vision_model.encoder.layers.21.layer_norm2.weight', 'model.vision_tower.vision_tower.vision_model.encoder.layers.21.mlp.fc1.bias', 'model.vision_tower.vision_tower.vision_model.encoder.lay

generation_config.json:   0%|          | 0.00/119 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/801M [00:00<?, ?B/s]

adapter_config.json:   0%|          | 0.00/496 [00:00<?, ?B/s]

adapter_model.safetensors:   0%|          | 0.00/755M [00:00<?, ?B/s]

TinyChartPhiForCausalLM(
  (model): TinyChartPhiModel(
    (embed_tokens): Embedding(50295, 2560)
    (embed_dropout): Dropout(p=0.0, inplace=False)
    (layers): ModuleList(
      (0-31): 32 x PhiDecoderLayer(
        (self_attn): PhiAttention(
          (q_proj): Linear(in_features=2560, out_features=2560, bias=True)
          (k_proj): Linear(in_features=2560, out_features=2560, bias=True)
          (v_proj): Linear(in_features=2560, out_features=2560, bias=True)
          (dense): Linear(in_features=2560, out_features=2560, bias=True)
          (rotary_emb): PhiRotaryEmbedding()
        )
        (mlp): PhiMLP(
          (activation_fn): NewGELUActivation()
          (fc1): Linear(in_features=2560, out_features=10240, bias=True)
          (fc2): Linear(in_features=10240, out_features=2560, bias=True)
        )
        (input_layernorm): LayerNorm((2560,), eps=1e-05, elementwise_affine=True)
        (resid_dropout): Dropout(p=0.1, inplace=False)
      )
    )
    (final_layernorm): LayerNorm((2560,), eps=1e-05, elementwise_affine=True)
    (vision_tower): SigLipVisionTower(
      (vision_tower): SigLipVisionModel(
        (vision_model): SigLipVisionTransformer(
          (embeddings): SigLipVisionEmbeddings(
            (patch_embedding): Conv2d(3, 1152, kernel_size=(14, 14), stride=(14, 14), padding=valid)
            (position_embedding): Embedding(2916, 1152)
          )
          (encoder): SigLipEncoderToMe(
            (layers): ModuleList(
              (0-25): 26 x SigLipEncoderLayerToMe(
                (self_attn): SigLipAttentionToMe(
                  (k_proj): Linear(in_features=1152, out_features=1152, bias=True)
                  (v_proj): Linear(in_features=1152, out_features=1152, bias=True)
                  (q_proj): Linear(in_features=1152, out_features=1152, bias=True)
                  (out_proj): Linear(in_features=1152, out_features=1152, bias=True)
                )
                (layer_norm1): LayerNorm((1152,), eps=1e-06, elementwise_affine=True)
                (mlp): SigLipMLP(
                  (activation_fn): PytorchGELUTanh()
                  (fc1): Linear(in_features=1152, out_features=4304, bias=True)
                  (fc2): Linear(in_features=4304, out_features=1152, bias=True)
                )
                (layer_norm2): LayerNorm((1152,), eps=1e-06, elementwise_affine=True)
              )
            )
          )
          (post_layernorm): LayerNorm((1152,), eps=1e-06, elementwise_affine=True)
          (head): Identity()
        )
      )
    )
    (mm_projector): Sequential(
      (0): Linear(in_features=1152, out_features=2560, bias=True)
      (1): GELU(approximate='none')
      (2): Linear(in_features=2560, out_features=2560, bias=True)
    )
  )
  (lm_head): Linear(in_features=2560, out_features=50295, bias=False)
)

# Direct Question

In [10]:
img_path = "/kaggle/input/datasets/dianshinta09/imagetest/2D_Horizontal_Style5.png"
text = "Mana yang tanaman dengan urutan kedua terluas?"

In [15]:
import time

start_time = time.perf_counter()
img_path = "/kaggle/input/datasets/dianshinta09/imagetest/2D_Horizontal_Style5.png"
text = "Mana yang tanaman dengan urutan kedua terluas?"
response = inference_model(
    [img_path],
    text,
    model,
    tokenizer,
    image_processor,
    context_len,
    conv_mode="phi",
    max_new_tokens=1024
)

latency = time.perf_counter() - start_time

print("Response:", response)
print(f"Latency: {latency:.4f} detik")

Pisang-Pisangan
Response: Pisang-Pisangan
Latency: 1.2563 detik

In [37]:
import time
import os
import base64
from openai import OpenAI

client = OpenAI(api_key=os.environ["OPENAI_API_KEY"])

img_path = "/kaggle/input/datasets/dianshinta09/imagetest/2D_Horizontal_Style5.png"
text = """Aturan output:

1. Jika pertanyaan TIDAK mengandung instruksi
"Jawab menggunakan langkah perhitungannya.",
jawab hanya dengan jawaban akhir yang singkat dan tepat.

Jangan memberikan:
- penjelasan
- alasan
- langkah perhitungan
- narasi tambahan
- satuan

2. Jika pertanyaan MENGANDUNG instruksi
"Jawab menggunakan langkah perhitungannya.",
jawaban HARUS berupa Program of Thoughts (PoT)
dalam bentuk assignment statement Python.

Jangan memberikan narasi atau penjelasan di luar format PoT.

Untuk jawaban PoT:

- Gunakan informasi pada gambar grafik untuk menentukan nilai
  yang diperlukan dalam perhitungan.
- Gunakan komentar satu baris sebelum setiap assignment statement.
- Setiap komentar dibungkus dengan tag <comment>#...</comment>.
- Setiap assignment statement dibungkus dengan tag <step>...</step>.
- Komentar harus bersifat generik dan deskriptif secara logika.
- Output akhir harus disimpan dalam variabel Answer.
- Jangan menggunakan Markdown code fence.
- Jangan memberikan narasi di luar format PoT.

Hanya boleh menggunakan operator dan fungsi berikut:

['len', 'all', 'any', 'index', 'np.sort', 'np.abs',
'np.add', 'np.argmax', 'np.argmin', 'np.diff', 'np.divide',
'np.greater', 'np.greater_equal', 'np.less', 'np.max',
'np.mean', 'np.median', 'np.min', 'np.subtract', 'np.sum',
'np.count_nonzero', 'np.where', '+', '-', '*', '/', '>',
'<', '='].
Kemudian tampilkan isi dari variabel 'Answer' dari perhitungan PoT tersebut!

Berapa jumlah Krisan dengan Anthurium Bunga? Jawab menggunakan langkah perhitungannya"""

# Encode gambar
with open(img_path, "rb") as image_file:
    base64_image = base64.b64encode(image_file.read()).decode("utf-8")

# Inference + latency
start_time = time.perf_counter()

response = client.chat.completions.create(
    model="gpt-4o-mini",
    messages=[
        {
            "role": "user",
            "content": [
                {
                    "type": "text",
                    "text": text
                },
                {
                    "type": "image_url",
                    "image_url": {
                        "url": f"data:image/png;base64,{base64_image}"
                    }
                }
            ]
        }
    ],
    max_tokens=1024
)

latency = time.perf_counter() - start_time

print("Response:", response.choices[0].message.content)
print(f"Latency: {latency:.4f} detik")

Response: <comment># Mendefinisikan jumlah Krisan</comment>
<step>Krisan = 200</step>
<comment># Mendefinisikan jumlah Anthurium Bunga</comment>
<step>Anthurium_Bunga = 1100</step>
<comment># Menghitung jumlah Krisan dengan Anthurium Bunga</comment>
<step>Answer = Krisan</step>
Answer
Latency: 1.2218 detik

# POT Question

In [17]:
img_path = "/kaggle/input/datasets/dianshinta09/imagetest/2D_Horizontal_Style5.png"
text = "Berapa jumlah Krisan dengan Anthurium Bunga? Jawab menggunakan langkah perhitungannya"
import time

start_time = time.perf_counter()

response = inference_model(
    [img_path],
    text,
    model,
    tokenizer,
    image_processor,
    context_len,
    conv_mode="phi",
    max_new_tokens=1024
)

latency = time.perf_counter() - start_time

print("Response:", response)
print(f"Latency: {latency:.4f} detik")

<comment># Definisikan daftar nilai laju pertumbuhan untuk setiap jenis tanaman</comment>
<step>values = [1100, 300, 200]</step>
<comment># Hitung jumlah total menggunakan fungsi numpy</comment>
<step>total = np.sum(values)</step>
<comment># Simpan hasil akhir ke variabel Answer</comment>
<step>Answer = total</step>
Response: <comment># Definisikan daftar nilai laju pertumbuhan untuk setiap jenis tanaman</comment>
<step>values = [1100, 300, 200]</step>
<comment># Hitung jumlah total menggunakan fungsi numpy</comment>
<step>total = np.sum(values)</step>
<comment># Simpan hasil akhir ke variabel Answer</comment>
<step>Answer = total</step>
Latency: 6.4287 detik

In [20]:
img_path = "/kaggle/input/datasets/dianshinta09/imagetest/2D_Horizontal_Style5.png"
text = "Berapa rata-rata luas panen ketiga tanaman berikut? Jawab menggunakan langkah perhitungannya"

import time

start_time = time.perf_counter()

response = inference_model(
    [img_path],
    text,
    model,
    tokenizer,
    image_processor,
    context_len,
    conv_mode="phi",
    max_new_tokens=1024
)
evaluate_cmds(parse_model_output(response))
latency = time.perf_counter() - start_time

print("Response:", response)
print(f"Latency: {latency:.4f} detik")

<comment># Definisikan daftar luas panen</comment>
<step>values = [11000, 300, 200]</step>
<comment># Hitung rata-rata menggunakan fungsi numpy</comment>
<step>mean_value = np.mean(values)</step>
<comment># Simpan hasil akhir</comment>
<step>Answer = mean_value</step>
Response: <comment># Definisikan daftar luas panen</comment>
<step>values = [11000, 300, 200]</step>
<comment># Hitung rata-rata menggunakan fungsi numpy</comment>
<step>mean_value = np.mean(values)</step>
<comment># Simpan hasil akhir</comment>
<step>Answer = mean_value</step>
Latency: 5.8232 detik

In [ ]:
evaluate_cmds(parse_model_output(response))

# PoT vs NonPoT

In [1]:
from huggingface_hub import login

login()

VBox(children=(HTML(value='<center> <img\nsrc=https://huggingface.co/front/assets/huggingface_logo-noborder.sv…

In [16]:
# ============================================================
# STRATIFIED RANDOM SAMPLING 500 NON-PoT
#
# KRITERIA:
#   - Hanya data yang memiliki score
#   - Hanya Non-PoT
#   - Selection dikeluarkan
#
# DESAIN SAMPLING:
#   1. Question Type dibuat seimbang
#   2. Dalam setiap Question Type:
#      Region × Chart Type dialokasikan proporsional
#
# QUESTION TYPE:
#   Sum, Average, Min, Max, Ranking, Compare
#
# OUTPUT:
#   1. CSV 500 sample
#   2. Non-PoT question
#   3. PoT question
#   4. Score Non-PoT
#
# RANDOM SEED = 42
# ============================================================


!pip install -q datasets

import random
import math
import pandas as pd
import json
import glob
import os
import re

from collections import defaultdict
from datasets import load_dataset


# ============================================================
# CONFIG
# ============================================================

DATASET_NAME = "shiinn97/indochartqav2"

SAMPLE_SIZE = 500
RANDOM_SEED = 42

# Kalimat instruksi PoT
POT_PHRASE = "Jawab menggunakan langkah perhitungannya"

# Folder hasil evaluasi TinyChart non-PoT
EVAL_DIR = "/kaggle/input/datasets/dianshinta09/eval-results-ver2"

# Output
OUTPUT_FILE = (
    "/kaggle/working/"
    "indochartqa_500_nonpot_pot_question.csv"
)


# ============================================================
# RANDOM SEED
# ============================================================

random.seed(RANDOM_SEED)


# ============================================================
# FUNGSI AMBIL HUMAN QUESTION
# ============================================================

def get_human_question(conversations):

    if isinstance(conversations, str):

        conversations = json.loads(
            conversations
        )

    for message in conversations:

        if message.get("from") == "human":

            question = message.get(
                "value",
                ""
            )

            question = question.replace(
                "<image>\n",
                ""
            ).strip()

            return question

    return ""


# ============================================================
# LOAD SCORE
# ============================================================

print("=" * 70)
print("MEMBACA SCORE")
print("=" * 70)

jsonl_files = glob.glob(
    os.path.join(
        EVAL_DIR,
        "*.jsonl"
    )
)

print(
    "Jumlah file JSONL:",
    len(jsonl_files)
)


score_dict = {}


for file_path in jsonl_files:

    with open(
        file_path,
        "r",
        encoding="utf-8"
    ) as f:

        for line in f:

            line = line.strip()

            if not line:
                continue

            try:

                data = json.loads(
                    line
                )

            except json.JSONDecodeError:

                continue

            if (
                "id" in data
                and "score" in data
            ):

                score_dict[
                    str(data["id"])
                ] = data["score"]


print(
    "Jumlah ID yang memiliki score:",
    len(score_dict)
)


# ============================================================
# LOAD DATASET
# ============================================================

print("\n" + "=" * 70)
print("LOAD TEST SET")
print("=" * 70)

dataset = load_dataset(
    DATASET_NAME
)

test_data = dataset["test"]

print(
    "Jumlah test set:",
    len(test_data)
)

print(
    "Kolom dataset:",
    test_data.column_names
)


# ============================================================
# PARSE ID
# ============================================================

pattern = re.compile(
    r"^([BS])\d+(BAR|GBAR|LINE)"
    r"(Sum|Average|Min|Max|Ranking|Compare|Selection)_\d+$"
)


def parse_id(sample_id):

    match = pattern.match(
        sample_id
    )

    if not match:
        return None

    region = match.group(1)

    chart_type = match.group(2)

    question_type = match.group(3)

    return (
        region,
        chart_type,
        question_type
    )


# ============================================================
# FILTER DATA
#
# SYARAT:
#   1. Memiliki score
#   2. ID dapat diparse
#   3. Bukan Selection
#   4. Bukan PoT
# ============================================================

eligible_indices = []

for idx, sample in enumerate(
    test_data
):

    sample_id = str(
        sample["id"]
    )


    # --------------------------------------------------------
    # HARUS MEMILIKI SCORE
    # --------------------------------------------------------

    if sample_id not in score_dict:

        continue


    # --------------------------------------------------------
    # PARSE ID
    # --------------------------------------------------------

    parsed = parse_id(
        sample_id
    )

    if parsed is None:

        continue


    region, chart_type, question_type = parsed


    # --------------------------------------------------------
    # EXCLUDE SELECTION
    # --------------------------------------------------------

    if question_type == "Selection":

        continue


    # --------------------------------------------------------
    # HANYA NON-PoT
    # --------------------------------------------------------

    question = get_human_question(
        sample["conversations"]
    )

    if (
        POT_PHRASE.lower()
        not in question.lower()
    ):

        eligible_indices.append(
            idx
        )


# ============================================================
# INFORMASI ELIGIBLE
# ============================================================

print("\n" + "=" * 70)
print("ELIGIBLE NON-PoT")
print("=" * 70)

print(
    "Non-PoT yang memiliki score:",
    len(eligible_indices)
)


# ============================================================
# VALIDASI SAMPLE SIZE
# ============================================================

if len(eligible_indices) < SAMPLE_SIZE:

    raise ValueError(
        f"Hanya terdapat "
        f"{len(eligible_indices)} "
        f"data eligible. "
        f"Dibutuhkan {SAMPLE_SIZE}."
    )


# ============================================================
# KELOMPOKKAN:
#
# QUESTION TYPE
#       ↓
# REGION × CHART TYPE
# ============================================================

question_groups = defaultdict(
    lambda: defaultdict(list)
)


for idx in eligible_indices:

    sample_id = str(
        test_data[idx]["id"]
    )

    parsed = parse_id(
        sample_id
    )

    if parsed is None:

        continue

    region, chart_type, question_type = parsed

    question_groups[
        question_type
    ][
        (region, chart_type)
    ].append(idx)


# ============================================================
# INFORMASI POPULASI PER QUESTION TYPE
# ============================================================

print("\n" + "=" * 70)
print("DISTRIBUSI POPULASI QUESTION TYPE")
print("=" * 70)


for question_type in sorted(
    question_groups.keys()
):

    total_population = sum(
        len(indices)
        for indices
        in question_groups[
            question_type
        ].values()
    )

    print(
        f"{question_type:<10}: "
        f"{total_population:,}"
    )


# ============================================================
# VALIDASI QUESTION TYPE
# ============================================================

question_types = sorted(
    question_groups.keys()
)


print(
    "\nJumlah Question Type:",
    len(question_types)
)


EXPECTED_QUESTION_TYPES = {
    "Sum",
    "Average",
    "Min",
    "Max",
    "Ranking",
    "Compare"
}


if set(question_types) != EXPECTED_QUESTION_TYPES:

    raise ValueError(
        "Question Type tidak sesuai.\n"
        f"Ditemukan: {question_types}\n"
        f"Diharapkan: "
        f"{sorted(EXPECTED_QUESTION_TYPES)}"
    )


# ============================================================
# ALOKASI SEIMBANG QUESTION TYPE
#
# 500 / 6 = 83 sisa 2
#
# Jadi:
#   4 tipe = 83
#   2 tipe = 84
# ============================================================

n_types = len(
    question_types
)

base_sample = (
    SAMPLE_SIZE
    // n_types
)

remainder = (
    SAMPLE_SIZE
    % n_types
)


question_allocation = {}


for i, question_type in enumerate(
    question_types
):

    n_sample = base_sample

    if i < remainder:

        n_sample += 1

    question_allocation[
        question_type
    ] = n_sample


# ============================================================
# VALIDASI POPULASI QUESTION TYPE
# ============================================================

for question_type in question_types:

    population = sum(
        len(indices)
        for indices
        in question_groups[
            question_type
        ].values()
    )

    required = question_allocation[
        question_type
    ]

    if population < required:

        raise ValueError(
            f"{question_type} hanya memiliki "
            f"{population} data, tetapi "
            f"membutuhkan {required} sample."
        )


# ============================================================
# TAMPILKAN TARGET
# ============================================================

print("\n" + "=" * 70)
print("TARGET SAMPLE PER QUESTION TYPE")
print("=" * 70)


for question_type in question_types:

    print(
        f"{question_type:<10}: "
        f"{question_allocation[question_type]}"
    )


print(
    "\nTotal:",
    sum(
        question_allocation.values()
    )
)


assert (
    sum(
        question_allocation.values()
    )
    == SAMPLE_SIZE
)


# ============================================================
# STRATIFIED RANDOM SAMPLING
#
# QUESTION TYPE → SEIMBANG
# REGION × CHART TYPE → PROPORSIONAL
# ============================================================

selected_indices = []

summary = []


for question_type in question_types:

    groups = question_groups[
        question_type
    ]

    target = question_allocation[
        question_type
    ]


    # --------------------------------------------------------
    # TOTAL POPULASI QUESTION TYPE
    # --------------------------------------------------------

    total_population = sum(
        len(indices)
        for indices
        in groups.values()
    )


    # --------------------------------------------------------
    # ALOKASI REGION × CHART TYPE
    # SECARA PROPORSIONAL
    # --------------------------------------------------------

    allocation = {}


    for group_key, indices in groups.items():

        population = len(
            indices
        )

        ideal = (
            population
            / total_population
            * target
        )

        floor_value = math.floor(
            ideal
        )

        allocation[group_key] = {

            "population":
                population,

            "ideal":
                ideal,

            "sample":
                floor_value,

            "remainder":
                ideal - floor_value
        }


    # --------------------------------------------------------
    # SESUAIKAN AGAR TOTAL SAMA DENGAN TARGET
    # --------------------------------------------------------

    current_total = sum(
        x["sample"]
        for x in allocation.values()
    )

    difference = (
        target
        - current_total
    )


    # --------------------------------------------------------
    # TAMBAH BERDASARKAN REMAINDER TERBESAR
    # --------------------------------------------------------

    candidates = sorted(
        allocation.keys(),
        key=lambda x:
            allocation[x]["remainder"],
        reverse=True
    )


    while difference > 0:

        changed = False

        for key in candidates:

            if difference == 0:

                break


            if (
                allocation[key]["sample"]
                <
                allocation[key]["population"]
            ):

                allocation[key][
                    "sample"
                ] += 1

                difference -= 1

                changed = True


        if not changed:

            break


    # --------------------------------------------------------
    # RANDOM SAMPLING PER REGION × CHART TYPE
    # --------------------------------------------------------

    for group_key in sorted(
        groups.keys()
    ):

        indices = groups[
            group_key
        ]

        n_sample = allocation[
            group_key
        ]["sample"]


        if n_sample == 0:

            continue


        selected = random.sample(
            indices,
            n_sample
        )


        selected_indices.extend(
            selected
        )


        region, chart_type = (
            group_key
        )


        summary.append({

            "Question_Type":
                question_type,

            "Region":
                region,

            "Chart_Type":
                chart_type,

            "Population":
                len(indices),

            "Population_Percentage":
                len(indices)
                / total_population
                * 100,

            "Sample":
                n_sample,

            "Sample_Percentage":
                n_sample
                / target
                * 100
        })


# ============================================================
# VALIDASI TOTAL SAMPLE
# ============================================================

print("\n" + "=" * 70)
print("VALIDASI SAMPLING")
print("=" * 70)


print(
    "Jumlah sample:",
    len(selected_indices)
)


assert (
    len(selected_indices)
    == SAMPLE_SIZE
)


# ============================================================
# ACAK URUTAN SAMPLE
# ============================================================

random.shuffle(
    selected_indices
)


# ============================================================
# AMBIL DATA
# ============================================================

sampled_dataset = test_data.select(
    selected_indices
)

df = sampled_dataset.to_pandas()


# ============================================================
# SIMPAN QUESTION NON-PoT
# ============================================================

df["question_nonpot"] = (
    df["conversations"]
    .apply(
        get_human_question
    )
)


# ============================================================
# BUAT QUESTION PoT
# ============================================================

df["question_pot"] = (
    df["question_nonpot"]
    .astype(str)
    .str.rstrip()
    + " "
    + POT_PHRASE
)


# ============================================================
# TAMBAHKAN SCORE NON-PoT
# ============================================================

df["score_nonpot"] = (
    df["id"]
    .astype(str)
    .map(score_dict)
)


# ============================================================
# VALIDASI FINAL
# ============================================================

print("\n" + "=" * 70)
print("VALIDASI FINAL")
print("=" * 70)


print(
    "Jumlah sample:",
    len(df)
)


print(
    "Score tersedia:",
    df["score_nonpot"]
    .notna()
    .sum()
)


print(
    "Score missing:",
    df["score_nonpot"]
    .isna()
    .sum()
)


assert len(df) == SAMPLE_SIZE

assert (
    df["score_nonpot"]
    .notna()
    .all()
)


# ============================================================
# AVERAGE SCORE NON-PoT
# ============================================================

average_nonpot = (
    df["score_nonpot"]
    .mean()
)


print(
    "\nAverage Score Non-PoT:",
    f"{average_nonpot:.4f}"
)


print(
    "Average Score (%):",
    f"{average_nonpot * 100:.2f}%"
)


# ============================================================
# SUMMARY STRATA
# ============================================================

summary_df = pd.DataFrame(
    summary
)


# ============================================================
# DISTRIBUSI QUESTION TYPE
# ============================================================

print("\n" + "=" * 70)
print("DISTRIBUSI QUESTION TYPE HASIL SAMPLING")
print("=" * 70)


question_summary = (
    summary_df
    .groupby(
        "Question_Type"
    )["Sample"]
    .sum()
    .reset_index()
)


display(
    question_summary
)


# ============================================================
# DISTRIBUSI REGION × CHART TYPE × QUESTION TYPE
# ============================================================

print("\n" + "=" * 70)
print(
    "DISTRIBUSI REGION × CHART TYPE × QUESTION TYPE"
)
print("=" * 70)


display(
    summary_df.sort_values(
        [
            "Question_Type",
            "Region",
            "Chart_Type"
        ]
    )
)


# ============================================================
# CEK CONTOH QUESTION
# ============================================================

print("\n" + "=" * 70)
print("CONTOH QUESTION")
print("=" * 70)


display(
    df[
        [
            "id",
            "question_nonpot",
            "question_pot",
            "score_nonpot"
        ]
    ].head(10)
)


# ============================================================
# SAVE CSV
# ============================================================

df.to_csv(
    OUTPUT_FILE,
    index=False
)


# ============================================================
# SELESAI
# ============================================================

print("\n" + "=" * 70)
print("STRATIFIED SAMPLING SELESAI")
print("=" * 70)


print(
    "Test set awal        :",
    len(test_data)
)


print(
    "Eligible non-PoT     :",
    len(eligible_indices)
)


print(
    "Jumlah Question Type :",
    len(question_types)
)


print(
    "Jumlah sample        :",
    len(df)
)


print(
    "Average Non-PoT      :",
    f"{average_nonpot:.4f}"
)


print(
    "Average Non-PoT (%)  :",
    f"{average_nonpot * 100:.2f}%"
)


print(
    "\nOutput:",
    OUTPUT_FILE
)

======================================================================
MEMBACA SCORE
======================================================================
Jumlah file JSONL: 1316
Jumlah ID yang memiliki score: 11050

======================================================================
LOAD TEST SET
======================================================================
Jumlah test set: 11050
Kolom dataset: ['id', 'image', 'conversations']

======================================================================
ELIGIBLE NON-PoT
======================================================================
Non-PoT yang memiliki score: 4973

======================================================================
DISTRIBUSI POPULASI QUESTION TYPE
======================================================================
Average   : 166
Compare   : 1,035
Max       : 1,433
Min       : 1,059
Ranking   : 764
Sum       : 516

Jumlah Question Type: 6

======================================================================
TARGET SAMPLE PER QUESTION TYPE
======================================================================
Average   : 84
Compare   : 84
Max       : 83
Min       : 83
Ranking   : 83
Sum       : 83

Total: 500

======================================================================
VALIDASI SAMPLING
======================================================================
Jumlah sample: 500

======================================================================
VALIDASI FINAL
======================================================================
Jumlah sample: 500
Score tersedia: 500
Score missing: 0

Average Score Non-PoT: 0.5060
Average Score (%): 50.60%

======================================================================
DISTRIBUSI QUESTION TYPE HASIL SAMPLING
======================================================================

  Question_Type  Sample
0       Average      84
1       Compare      84
2           Max      83
3           Min      83
4       Ranking      83
5           Sum      83

======================================================================
DISTRIBUSI REGION × CHART TYPE × QUESTION TYPE
======================================================================

,Question_Type,Region,Chart_Type,Population,Population_Percentage,Sample,Sample_Percentage
0,Average,B,BAR,20,12.048193,10,11.904762
1,Average,B,LINE,5,3.012048,3,3.571429
2,Average,S,BAR,76,45.783133,38,45.238095
3,Average,S,LINE,65,39.156627,33,39.285714
4,Compare,B,BAR,320,30.917874,26,30.952381
5,Compare,B,GBAR,100,9.661836,8,9.523810
6,Compare,B,LINE,15,1.449275,1,1.190476
7,Compare,S,BAR,120,11.594203,10,11.904762
8,Compare,S,GBAR,300,28.985507,24,28.571429
9,Compare,S,LINE,180,17.391304,15,17.857143
10,Max,B,BAR,380,26.517795,22,26.506024
11,Max,B,GBAR,100,6.978367,6,7.228916
12,Max,B,LINE,35,2.442428,2,2.409639
13,Max,S,BAR,268,18.702024,15,18.072289
14,Max,S,GBAR,360,25.122121,21,25.301205
15,Max,S,LINE,290,20.237264,17,20.481928
16,Min,B,BAR,340,32.105760,27,32.530120
17,Min,B,GBAR,60,5.665722,5,6.024096
18,Min,B,LINE,15,1.416431,1,1.204819
19,Min,S,BAR,124,11.709160,10,12.048193
20,Min,S,GBAR,340,32.105760,26,31.325301
21,Min,S,LINE,180,16.997167,14,16.867470
22,Ranking,B,BAR,220,28.795812,24,28.915663
23,Ranking,B,GBAR,40,5.235602,4,4.819277
24,Ranking,B,LINE,15,1.963351,2,2.409639
25,Ranking,S,BAR,164,21.465969,18,21.686747
26,Ranking,S,GBAR,160,20.942408,17,20.481928
27,Ranking,S,LINE,165,21.596859,18,21.686747
28,Sum,B,BAR,100,19.379845,16,19.277108
29,Sum,B,LINE,20,3.875969,3,3.614458
30,Sum,S,BAR,216,41.860465,35,42.168675
31,Sum,S,GBAR,40,7.751938,6,7.228916
32,Sum,S,LINE,140,27.131783,23,27.710843

======================================================================
CONTOH QUESTION
======================================================================

,id,question_nonpot,question_pot,score_nonpot
0,B2GBARMax_12,Triwulan mana yang memiliki persentase Sektor ...,Triwulan mana yang memiliki persentase Sektor ...,1.000000
1,S60GBARMax_36,Berapa nilai maksimum Indeks Pengaruh Inflasi ...,Berapa nilai maksimum Indeks Pengaruh Inflasi ...,1.000000
2,B136BARAverage_3,Apakah Indeks Implisit untuk 'C. Industri Peng...,Apakah Indeks Implisit untuk 'C. Industri Peng...,0.000000
3,S797BARRanking_1,Susun urutan bulan berdasarkan nilai Indeks Ha...,Susun urutan bulan berdasarkan nilai Indeks Ha...,0.656863
4,B115BARRanking_1,Kelompok pengeluaran manakah yang berada pada ...,Kelompok pengeluaran manakah yang berada pada ...,0.000000
5,B14BARCompare_15,Apakah Pengeluaran Konsumsi Rumah Tangga lebih...,Apakah Pengeluaran Konsumsi Rumah Tangga lebih...,1.000000
6,S35GBARMin_18,Bulan manakah yang memiliki nilai Bongkar tere...,Bulan manakah yang memiliki nilai Bongkar tere...,0.533333
7,S445BARMax_3,Kabupaten/Kota mana yang memiliki jumlah mobil...,Kabupaten/Kota mana yang memiliki jumlah mobil...,1.000000
8,B187BARMax_16,Kategori lapangan usaha manakah yang memiliki ...,Kategori lapangan usaha manakah yang memiliki ...,1.000000
9,S63GBARCompare_12,Apakah Indeks Pendapatan Kini pada Triwulan II...,Apakah Indeks Pendapatan Kini pada Triwulan II...,1.000000

======================================================================
STRATIFIED SAMPLING SELESAI
======================================================================
Test set awal        : 11050
Eligible non-PoT     : 4973
Jumlah Question Type : 6
Jumlah sample        : 500
Average Non-PoT      : 0.5060
Average Non-PoT (%)  : 50.60%

Output: /kaggle/working/indochartqa_500_nonpot_pot_question.csv

In [2]:
import os
import tarfile
import shutil
from huggingface_hub import hf_hub_download

# ============================================================
# DOWNLOAD TINYCHART IMAGES
# ============================================================

REPO_ID = "shiinn97/indochartqa"
TAR_FILENAME = "tinychart_images.tar"

TAR_PATH = hf_hub_download(
    repo_id=REPO_ID,
    filename=TAR_FILENAME,
    repo_type="dataset"
)

print("Tar file:", TAR_PATH)


# ============================================================
# EXTRACT
# ============================================================

EXTRACT_DIR = "/kaggle/working/tinychart_images/tinychart_images"

os.makedirs(EXTRACT_DIR, exist_ok=True)

with tarfile.open(TAR_PATH, "r") as tar:
    tar.extractall(EXTRACT_DIR)

print("Images extracted to:", EXTRACT_DIR)

tinychart_images.tar:   0%|          | 0.00/1.01G [00:00<?, ?B/s]

Tar file: /root/.cache/huggingface/hub/datasets--shiinn97--indochartqa/snapshots/790e129b02805b66f5f2b3235554c1af3a674a95/tinychart_images.tar

/tmp/ipykernel_58/3656698375.py:31: DeprecationWarning: Python 3.14 will, by default, filter extracted tar archives and reject files or modify their metadata. Use the filter argument to control this behavior.
  tar.extractall(EXTRACT_DIR)

Images extracted to: /kaggle/working/tinychart_images/tinychart_images

In [17]:
# INFERENCE POT QUESTIONS
import pandas as pd
import os
from tqdm.auto import tqdm
import contextlib
import io
# ============================================================
# CONFIG
# ============================================================

INPUT_CSV = "/kaggle/working/indochartqa_500_nonpot_pot_question.csv"
IMAGE_DIR = "/kaggle/working/tinychart_images/tinychart_images/tinychart_images/"
OUTPUT_CSV = "/kaggle/working/indochartqa_500_pot_inference.csv"

df = pd.read_csv(INPUT_CSV)
print("Jumlah data:", len(df))

def get_image_path(row):
    image_path = os.path.join(
        IMAGE_DIR,
        str(row["image"])
    )

    if not os.path.isfile(image_path):
        raise FileNotFoundError(
            f"Image tidak ditemukan: {image_path}"
        )

    return image_path


results = []

for i, row in tqdm(
    df.iterrows(),
    total=len(df),
    desc="Inference PoT"
):

    image_path = get_image_path(row)
    question = row["question_pot"]

    try:

        # ----------------------------------------------------
        # INFERENCE
        # ----------------------------------------------------

        with contextlib.redirect_stdout(io.StringIO()):
            response = inference_model(
                [image_path],
                question,
                model,
                tokenizer,
                image_processor,
                context_len,
                conv_mode="phi",
                max_new_tokens=1024
            )

        # ----------------------------------------------------
        # PARSE + EXECUTE PoT
        # ----------------------------------------------------

        parsed_output = parse_model_output(response)
        final_answer = evaluate_cmds(parsed_output)

        # ----------------------------------------------------
        # SIMPAN FINAL ANSWER SAJA
        # ----------------------------------------------------

        results.append({

            "id": row["id"],

            "image": row["image"],

            "question_nonpot":
                row["question_nonpot"],

            "question_pot":
                question,

            # Final answer setelah eksekusi PoT
            "answer_pot":
                str(final_answer),

            # Skor non-PoT yang sudah tersedia
            "score_nonpot":
                row["score_nonpot"],

            "error": ""

        })

    except Exception as e:

        results.append({

            "id": row["id"],

            "image": row["image"],

            "question_nonpot":
                row["question_nonpot"],

            "question_pot":
                question,

            "answer_pot": "",

            "score_nonpot":
                row["score_nonpot"],

            "error": str(e)

        })


# ============================================================
# SAVE
# ============================================================

results_df = pd.DataFrame(results)

results_df.to_csv(
    OUTPUT_CSV,
    index=False
)


# ============================================================
# SUMMARY
# ============================================================

print("\n" + "=" * 70)
print("INFERENCE PoT SELESAI")
print("=" * 70)

print("Total data:", len(results_df))

print(
    "Berhasil:",
    (results_df["error"] == "").sum()
)

print(
    "Error:",
    (results_df["error"] != "").sum()
)

print("\nOutput:")
print(OUTPUT_CSV)

Jumlah data: 500

Inference PoT:   0%|          | 0/500 [00:00<?, ?it/s]

/usr/local/lib/python3.12/dist-packages/transformers/generation/configuration_utils.py:392: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(

======================================================================
INFERENCE PoT SELESAI
======================================================================
Total data: 500
Berhasil: 395
Error: 105

Output:
/kaggle/working/indochartqa_500_pot_inference.csv

In [10]:
import json
import re
from pathlib import Path

import pandas as pd
import numpy as np


# ============================================================
# PATH
# ============================================================

CSV_PATH = (
    "/kaggle/input/datasets/"
    "dianshinta09/500-inference-pot-2/"
    "indochartqa_500_pot_inference (2).csv"
)

GROUND_TRUTH_DIR = (
    "/kaggle/input/datasets/"
    "dianshinta09/eval-results-ver2"
)

OUTPUT_DETAIL = (
    "/kaggle/working/"
    "comparison_pot_vs_nonpot_detail.csv"
)


# ============================================================
# SETTINGS
# ============================================================

NUMERIC_TOLERANCE = 0.05
NLS_THRESHOLD = 0.5

YEAR_MIN = 1900
YEAR_MAX = 2026


# ============================================================
# CLEAN TEXT
# ============================================================

def clean_text(value):

    if value is None:
        return ""

    try:
        if pd.isna(value):
            return ""
    except:
        pass

    value = str(value).strip()

    value = re.sub(
        r"\s+",
        " ",
        value
    )

    return value


# ============================================================
# NORMALIZE ID
# ============================================================

def normalize_id(value):

    if value is None:
        return ""

    try:
        if pd.isna(value):
            return ""
    except:
        pass

    value = str(value).strip()

    if re.fullmatch(
        r"-?\d+\.0+",
        value
    ):

        value = value.split(".")[0]

    return value


# ============================================================
# YEAR
# ============================================================

def is_year(
    answer,
    question
):

    answer = clean_text(
        answer
    )

    question = clean_text(
        question
    ).lower()

    if "tahun" not in question:
        return False

    years = re.findall(
        r"\b(19\d{2}|20\d{2})\b",
        answer
    )

    return any(
        YEAR_MIN <= int(year) <= YEAR_MAX
        for year in years
    )


# ============================================================
# NUMERIC
# ============================================================

def numeric_candidates(value):

    value = clean_text(value)

    if not value:
        return []

    value = value.replace(
        "%",
        ""
    )

    value = re.sub(
        r"(?i)\brp\.?",
        "",
        value
    )

    value = value.replace(
        " ",
        ""
    )

    if not re.fullmatch(
        r"-?[\d.,]+",
        value
    ):

        return []

    candidates = []

    def add(x):

        try:

            number = float(x)

            if np.isfinite(number):

                if number not in candidates:

                    candidates.append(
                        number
                    )

        except:
            pass

    comma = value.count(",")
    dot = value.count(".")

    # --------------------------------------------------------
    # Tidak ada separator
    # --------------------------------------------------------

    if comma == 0 and dot == 0:

        add(value)

        return candidates

    # --------------------------------------------------------
    # Ada koma dan titik
    # --------------------------------------------------------

    if comma > 0 and dot > 0:

        if value.rfind(",") > value.rfind("."):

            normalized = (
                value
                .replace(".", "")
                .replace(",", ".")
            )

        else:

            normalized = value.replace(
                ",",
                ""
            )

        add(normalized)

        return candidates

    # --------------------------------------------------------
    # Koma saja
    # --------------------------------------------------------

    if comma > 0:

        parts = value.split(",")

        if len(parts) == 2:

            left, right = parts

            if len(right) == 3:

                add(
                    left + right
                )

                add(
                    left + "." + right
                )

            else:

                add(
                    left + "." + right
                )

        return candidates

    # --------------------------------------------------------
    # Titik saja
    # --------------------------------------------------------

    if dot > 0:

        parts = value.split(".")

        if len(parts) == 2:

            left, right = parts

            if len(right) == 3:

                add(
                    left + right
                )

                add(
                    left + "." + right
                )

            else:

                add(value)

        return candidates

    return candidates


def is_numeric(value):

    return bool(
        numeric_candidates(value)
    )


# ============================================================
# RELAXED ACCURACY
# ============================================================

def numeric_equal(
    prediction,
    ground_truth
):

    predictions = numeric_candidates(
        prediction
    )

    ground_truths = numeric_candidates(
        ground_truth
    )

    if not predictions or not ground_truths:
        return False

    for pred in predictions:

        for gt in ground_truths:

            if gt == 0:

                if pred == 0:
                    return True

            else:

                relative_error = (
                    abs(pred - gt)
                    / abs(gt)
                )

                if relative_error <= NUMERIC_TOLERANCE:

                    return True

    return False


# ============================================================
# LEVENSHTEIN
# ============================================================

def levenshtein(
    s1,
    s2
):

    if s1 == s2:
        return 0

    if not s1:
        return len(s2)

    if not s2:
        return len(s1)

    previous = list(
        range(len(s2) + 1)
    )

    for i, c1 in enumerate(
        s1,
        1
    ):

        current = [i]

        for j, c2 in enumerate(
            s2,
            1
        ):

            current.append(
                min(
                    current[j - 1] + 1,
                    previous[j] + 1,
                    previous[j - 1] + (
                        c1 != c2
                    )
                )
            )

        previous = current

    return previous[-1]


# ============================================================
# NLS
# ============================================================

def compute_nls(
    ground_truth,
    prediction
):

    ground_truth = clean_text(
        ground_truth
    ).lower()

    prediction = clean_text(
        prediction
    ).lower()

    if ground_truth == prediction:
        return 1.0

    if not ground_truth or not prediction:
        return 0.0

    distance = levenshtein(
        ground_truth,
        prediction
    )

    max_length = max(
        len(ground_truth),
        len(prediction)
    )

    return 1 - (
        distance / max_length
    )


# ============================================================
# EM
# ============================================================

def compute_em(
    prediction,
    ground_truth
):

    return float(
        clean_text(prediction)
        == clean_text(ground_truth)
    )


# ============================================================
# EVALUATE PoT
# ============================================================

def evaluate_pot(
    prediction,
    ground_truth,
    question
):

    prediction = clean_text(
        prediction
    )

    ground_truth = clean_text(
        ground_truth
    )

    # --------------------------------------------------------
    # YEAR
    # --------------------------------------------------------

    if is_year(
        prediction,
        question
    ):

        em = compute_em(
            prediction,
            ground_truth
        )

        return {
            "score": em,
            "metric": "EM",
            "answer_type": "year",
            "em": em,
            "nls": compute_nls(
                ground_truth,
                prediction
            ),
            "relaxed_acc": None
        }

    # --------------------------------------------------------
    # NUMERIC
    # --------------------------------------------------------

    if is_numeric(
        prediction
    ):

        relaxed_acc = float(
            numeric_equal(
                prediction,
                ground_truth
            )
        )

        return {
            "score": relaxed_acc,
            "metric": "Relaxed Accuracy",
            "answer_type": "numeric",
            "em": compute_em(
                prediction,
                ground_truth
            ),
            "nls": compute_nls(
                ground_truth,
                prediction
            ),
            "relaxed_acc": relaxed_acc
        }

    # --------------------------------------------------------
    # TEXT
    # --------------------------------------------------------

    nls = compute_nls(
        ground_truth,
        prediction
    )

    return {
        "score": nls,
        "metric": "NLS without threshold",
        "answer_type": "text",
        "em": compute_em(
            prediction,
            ground_truth
        ),
        "nls": nls,
        "relaxed_acc": None
    }


# ============================================================
# LOAD GROUND TRUTH
# ============================================================

def load_ground_truth(
    directory
):

    directory = Path(
        directory
    )

    gt_by_id = {}

    jsonl_files = sorted(
        directory.glob(
            "*.jsonl"
        )
    )

    print(
        f"Jumlah file GT: "
        f"{len(jsonl_files)}"
    )

    for file in jsonl_files:

        with open(
            file,
            "r",
            encoding="utf-8"
        ) as f:

            for line in f:

                if not line.strip():
                    continue

                try:

                    record = json.loads(
                        line
                    )

                except json.JSONDecodeError:

                    continue

                record_id = normalize_id(
                    record.get(
                        "id",
                        ""
                    )
                )

                if not record_id:

                    record_id = normalize_id(
                        record.get(
                            "ID",
                            ""
                        )
                    )

                if not record_id:
                    continue

                gt_by_id[
                    record_id
                ] = {

                    "question":
                        record.get(
                            "question",
                            ""
                        ),

                    "gt_answer":
                        record.get(
                            "gt_answer",
                            record.get(
                                "answer",
                                ""
                            )
                        ),

                    "chart_type":
                        record.get(
                            "chart_type",
                            ""
                        ),

                    "question_type":
                        record.get(
                            "question_type",
                            ""
                        )
                }

    print(
        f"Jumlah GT unik: "
        f"{len(gt_by_id):,}"
    )

    return gt_by_id


# ============================================================
# MAIN COMPARISON
# ============================================================

def main():

    # --------------------------------------------------------
    # LOAD CSV
    # --------------------------------------------------------

    df = pd.read_csv(
        CSV_PATH,
        dtype=str,
        keep_default_na=False
    )

    print(
        "=" * 80
    )

    print(
        "CSV"
    )

    print(
        "=" * 80
    )

    print(
        f"Jumlah data: {len(df):,}"
    )

    print(
        f"Kolom: {list(df.columns)}"
    )

    # --------------------------------------------------------
    # CHECK COLUMN
    # --------------------------------------------------------

    required = [
        "id",
        "answer_pot",
        "score_nonpot"
    ]

    missing = [
        col
        for col in required
        if col not in df.columns
    ]

    if missing:

        raise ValueError(
            f"Kolom tidak ditemukan: "
            f"{missing}"
        )

    # --------------------------------------------------------
    # LOAD GT
    # --------------------------------------------------------

    gt_by_id = load_ground_truth(
        GROUND_TRUTH_DIR
    )

    # --------------------------------------------------------
    # EVALUATION
    # --------------------------------------------------------

    records = []

    missing_ids = []

    for _, row in df.iterrows():

        record_id = normalize_id(
            row["id"]
        )

        # ----------------------------------------------------
        # Find GT
        # ----------------------------------------------------

        if record_id not in gt_by_id:

            missing_ids.append(
                record_id
            )

            continue

        gt = gt_by_id[
            record_id
        ]

        question = clean_text(
            gt["question"]
        )

        gt_answer = clean_text(
            gt["gt_answer"]
        )

        # ----------------------------------------------------
        # PoT
        # ----------------------------------------------------

        answer_pot = clean_text(
            row["answer_pot"]
        )

        pot = evaluate_pot(
            answer_pot,
            gt_answer,
            question
        )

        # ----------------------------------------------------
        # Non-PoT
        # ----------------------------------------------------
        # LANGSUNG AMBIL DARI CSV
        # Tidak dihitung ulang.
        # ----------------------------------------------------

        score_nonpot = pd.to_numeric(
            row["score_nonpot"],
            errors="coerce"
        )

        # ----------------------------------------------------
        # Difference
        # ----------------------------------------------------

        difference = (
            pot["score"]
            - score_nonpot
            if pd.notna(score_nonpot)
            else np.nan
        )

        records.append({

            "id":
                record_id,

            "chart_type":
                gt["chart_type"],

            "question_type":
                gt["question_type"],

            "question":
                question,

            "gt_answer":
                gt_answer,

            "answer_pot":
                answer_pot,

            "score_pot":
                pot["score"],

            "pot_metric":
                pot["metric"],

            "pot_answer_type":
                pot["answer_type"],

            "pot_em":
                pot["em"],

            "pot_nls":
                pot["nls"],

            "pot_relaxed_acc":
                pot["relaxed_acc"],

            "score_nonpot":
                score_nonpot,

            "difference_pot_minus_nonpot":
                difference
        })

    # --------------------------------------------------------
    # DETAIL DATAFRAME
    # --------------------------------------------------------

    result = pd.DataFrame(
        records
    )

    # --------------------------------------------------------
    # SAVE DETAIL
    # --------------------------------------------------------

    result.to_csv(
        OUTPUT_DETAIL,
        index=False,
        encoding="utf-8-sig"
    )

    # ========================================================
    # OVERALL
    # ========================================================

    print(
        "\n"
        + "=" * 80
    )

    print(
        "PERBANDINGAN OVERALL"
    )

    print(
        "=" * 80
    )

    print(
        f"CSV rows       : {len(df):,}"
    )

    print(
        f"Berhasil eval  : {len(result):,}"
    )

    print(
        f"GT tidak ada   : {len(missing_ids):,}"
    )

    print(
        f"\nPoT Score      : "
        f"{result['score_pot'].mean():.4f}"
    )

    print(
        f"Non-PoT Score  : "
        f"{result['score_nonpot'].mean():.4f}"
    )

    print(
        f"Difference     : "
        f"{result['difference_pot_minus_nonpot'].mean():+.4f}"
    )

    # ========================================================
    # COUNT
    # ========================================================

    pot_mean = result[
        "score_pot"
    ].mean()

    nonpot_mean = result[
        "score_nonpot"
    ].mean()

    pot_higher = (
        result[
            "score_pot"
        ]
        > result[
            "score_nonpot"
        ]
    ).sum()

    nonpot_higher = (
        result[
            "score_nonpot"
        ]
        > result[
            "score_pot"
        ]
    ).sum()

    equal = (
        result[
            "score_pot"
        ]
        == result[
            "score_nonpot"
        ]
    ).sum()

    print(
        "\n"
        + "=" * 80
    )

    print(
        "JUMLAH HASIL"
    )

    print(
        "=" * 80
    )

    print(
        f"PoT > Non-PoT : {pot_higher}"
    )

    print(
        f"PoT < Non-PoT : {nonpot_higher}"
    )

    print(
        f"PoT = Non-PoT : {equal}"
    )

    # ========================================================
    # BY QUESTION TYPE
    # ========================================================

    print(
        "\n"
        + "=" * 80
    )

    print(
        "PER QUESTION TYPE"
    )

    print(
        "=" * 80
    )

    by_question = (
        result
        .groupby("question_type")
        .agg(
            n=("id", "count"),
            pot_score=(
                "score_pot",
                "mean"
            ),
            nonpot_score=(
                "score_nonpot",
                "mean"
            ),
            difference=(
                "difference_pot_minus_nonpot",
                "mean"
            )
        )
        .reset_index()
    )

    print(
        by_question.to_string(
            index=False
        )
    )

    # ========================================================
    # BY CHART TYPE
    # ========================================================

    print(
        "\n"
        + "=" * 80
    )

    print(
        "PER CHART TYPE"
    )

    print(
        "=" * 80
    )

    by_chart = (
        result
        .groupby("chart_type")
        .agg(
            n=("id", "count"),
            pot_score=(
                "score_pot",
                "mean"
            ),
            nonpot_score=(
                "score_nonpot",
                "mean"
            ),
            difference=(
                "difference_pot_minus_nonpot",
                "mean"
            )
        )
        .reset_index()
    )

    print(
        by_chart.to_string(
            index=False
        )
    )

    # ========================================================
    # MISSING IDS
    # ========================================================

    if missing_ids:

        missing_path = (
            "/kaggle/working/"
            "missing_gt_ids.csv"
        )

        pd.DataFrame({
            "id":
                missing_ids
        }).to_csv(
            missing_path,
            index=False
        )

        print(
            f"\n⚠️ Missing IDs disimpan:"
        )

        print(
            missing_path
        )

    print(
        f"\n✓ Detail hasil:"
    )

    print(
        OUTPUT_DETAIL
    )

    return result


# ============================================================
# RUN
# ============================================================

result = main()

================================================================================
CSV
================================================================================
Jumlah data: 500
Kolom: ['id', 'image', 'question_nonpot', 'question_pot', 'answer_pot', 'score_nonpot', 'error']
Jumlah file GT: 1316
Jumlah GT unik: 11,050

================================================================================
PERBANDINGAN OVERALL
================================================================================
CSV rows       : 500
Berhasil eval  : 500
GT tidak ada   : 0

PoT Score      : 0.3365
Non-PoT Score  : 0.6117
Difference     : -0.2752

================================================================================
JUMLAH HASIL
================================================================================
PoT > Non-PoT : 104
PoT < Non-PoT : 223
PoT = Non-PoT : 173

================================================================================
PER QUESTION TYPE
================================================================================
question_type   n  pot_score  nonpot_score  difference
              500   0.336519      0.611748   -0.275229

================================================================================
PER CHART TYPE
================================================================================
chart_type   n  pot_score  nonpot_score  difference
           500   0.336519      0.611748   -0.275229

✓ Detail hasil:
/kaggle/working/comparison_pot_vs_nonpot_detail.csv

In [4]:
import pandas as pd
import re

# ============================================================
# CONFIG
# ============================================================

CSV_PATH = "/kaggle/input/datasets/dianshinta09/500-inference-pot-2/indochartqa_500_pot_inference (2).csv"


# ============================================================
# LOAD DATA
# ============================================================

df = pd.read_csv(CSV_PATH)

print(f"Total data: {len(df)}")


# ============================================================
# AMBIL DATA YANG ERROR
# ============================================================

# Error = kolom error tidak kosong
error_df = df[
    df["error"].notna() &
    (df["error"].astype(str).str.strip() != "")
].copy()

print(f"Total data error: {len(error_df)}")


# ============================================================
# PARSE QUESTION TYPE DARI ID
# ============================================================

def get_question_type_from_id(sample_id):

    pattern = (
        r'^([BS])\d+'
        r'(BAR|GBAR|LINE)'
        r'(Sum|Average|Min|Max|Ranking|Compare|Selection)_\d+$'
    )

    match = re.match(pattern, str(sample_id))

    if match:
        return match.group(3)

    return "Unknown"


error_df["question_type"] = error_df["id"].apply(
    get_question_type_from_id
)


# ============================================================
# HITUNG ERROR PER QUESTION TYPE
# ============================================================

error_summary = (
    error_df
    .groupby("question_type")
    .size()
    .reset_index(name="error_count")
    .sort_values("error_count", ascending=False)
)


# ============================================================
# PRINT
# ============================================================

print("\n" + "=" * 60)
print("ERROR COUNT BY QUESTION TYPE")
print("=" * 60)

print(error_summary.to_string(index=False))


# ============================================================
# PERSENTASE ERROR
# ============================================================

error_summary["error_percentage"] = (
    error_summary["error_count"]
    / len(error_df)
    * 100
).round(2)

print("\n" + "=" * 60)
print("ERROR COUNT & PERCENTAGE")
print("=" * 60)

print(error_summary.to_string(index=False))


# ============================================================
# CEK ERROR YANG TIDAK BERHASIL DIPARSE
# ============================================================

unknown_df = error_df[
    error_df["question_type"] == "Unknown"
]

if len(unknown_df) > 0:

    print("\n" + "=" * 60)
    print("ID YANG QUESTION TYPE-NYA TIDAK TERDETEKSI")
    print("=" * 60)

    print(
        unknown_df[
            ["id", "error"]
        ].to_string(index=False)
    )

Total data: 500
Total data error: 125

============================================================
ERROR COUNT BY QUESTION TYPE
============================================================
question_type  error_count
          Max           47
      Ranking           40
      Compare           18
          Min           18
      Average            2

============================================================
ERROR COUNT & PERCENTAGE
============================================================
question_type  error_count  error_percentage
          Max           47              37.6
      Ranking           40              32.0
      Compare           18              14.4
          Min           18              14.4
      Average            2               1.6

# Evaluasi

In [6]:
import json
import re
import os
import zipfile
from pathlib import Path
from collections import defaultdict, Counter

import pandas as pd
import numpy as np


# ============================================================
# SETTINGS
# ============================================================

NUMERIC_TOLERANCE = 0.05
NLS_THRESHOLD = 0.5

YEAR_MIN = 1900
YEAR_MAX = 2026


# ============================================================
# TEXT CLEANING
# ============================================================

def clean_answer_text(answer):
    """
    Clean answer before classification/evaluation.
    """

    if answer is None:
        return ""

    answer = str(answer).strip()

    # Normalize whitespace
    answer = re.sub(r'\s+', ' ', answer)

    return answer


# ============================================================
# YEAR DETECTION
# ============================================================

def is_year(answer_str, question_str):
    """
    Detect whether the answer represents a year.

    Criteria:
    - Question contains the word 'tahun'
    - Answer contains a 4-digit number between 1900 and 2026
    """

    answer_str = clean_answer_text(answer_str)
    question_str = clean_answer_text(question_str).lower()

    if 'tahun' not in question_str:
        return False

    matches = re.findall(
        r'\b(19\d{2}|20\d{2})\b',
        answer_str
    )

    if not matches:
        return False

    for match in matches:

        year = int(match)

        if YEAR_MIN <= year <= YEAR_MAX:
            return True

    return False


# ============================================================
# NUMERIC PARSER
# ============================================================

def numeric_candidates(value):
    """
    Return possible numeric interpretations of an answer.

    Designed for Indonesian and international number formats.
    """

    if value is None:
        return []

    s = clean_answer_text(value)

    if not s:
        return []

    # --------------------------------------------------------
    # REMOVE COMMON SYMBOLS
    # --------------------------------------------------------

    s = s.replace('%', '')

    s = re.sub(
        r'(?i)\brp\.?',
        '',
        s
    )

    s = s.strip()
    s = s.replace(' ', '')

    # --------------------------------------------------------
    # VALID CHARACTER CHECK
    # --------------------------------------------------------

    if not re.fullmatch(
        r'-?[\d.,]+',
        s
    ):
        return []

    candidates = []

    def add_candidate(value):

        try:

            number = float(value)

            if np.isfinite(number):

                if not any(
                    np.isclose(
                        number,
                        existing,
                        rtol=0,
                        atol=1e-12
                    )
                    for existing in candidates
                ):
                    candidates.append(number)

        except (
            ValueError,
            TypeError
        ):
            pass

    comma_count = s.count(',')
    dot_count = s.count('.')

    # ========================================================
    # NO SEPARATOR
    # ========================================================

    if comma_count == 0 and dot_count == 0:

        add_candidate(s)

        return candidates

    # ========================================================
    # BOTH COMMA AND DOT
    # ========================================================

    if comma_count > 0 and dot_count > 0:

        if s.rfind(',') > s.rfind('.'):

            normalized = (
                s
                .replace('.', '')
                .replace(',', '.')
            )

        else:

            normalized = (
                s
                .replace(',', '')
            )

        add_candidate(normalized)

        return candidates

    # ========================================================
    # COMMA ONLY
    # ========================================================

    if comma_count > 0:

        if comma_count > 1:

            if re.fullmatch(
                r'-?\d{1,3}(,\d{3})+',
                s
            ):

                add_candidate(
                    s.replace(',', '')
                )

            return candidates

        left, right = s.split(',')

        if len(right) != 3:

            add_candidate(
                left + '.' + right
            )

            return candidates

        if (
            len(right) == 3
            and len(left.lstrip('-')) <= 3
        ):

            add_candidate(
                left + '.' + right
            )

            add_candidate(
                left + right
            )

        else:

            add_candidate(
                left + '.' + right
            )

        return candidates

    # ========================================================
    # DOT ONLY
    # ========================================================

    if dot_count > 0:

        if dot_count > 1:

            if re.fullmatch(
                r'-?\d{1,3}(\.\d{3})+',
                s
            ):

                add_candidate(
                    s.replace('.', '')
                )

            return candidates

        left, right = s.split('.')

        if len(right) != 3:

            add_candidate(s)

            return candidates

        if (
            len(right) == 3
            and len(left.lstrip('-')) <= 3
        ):

            add_candidate(
                left + right
            )

            add_candidate(s)

        else:

            add_candidate(s)

        return candidates

    return candidates


# ============================================================
# NUMERIC DETECTION
# ============================================================

def is_numeric(answer_str):

    return len(
        numeric_candidates(answer_str)
    ) > 0


# ============================================================
# NUMERIC COMPARISON
# ============================================================

def numeric_equal(
    model_answer,
    gt_answer,
    tolerance=NUMERIC_TOLERANCE
):

    model_candidates = numeric_candidates(
        model_answer
    )

    gt_candidates = numeric_candidates(
        gt_answer
    )

    if not model_candidates or not gt_candidates:
        return False

    for model_num in model_candidates:

        for gt_num in gt_candidates:

            if gt_num == 0:

                if model_num == 0:
                    return True

                continue

            error_rate = (
                abs(model_num - gt_num)
                / abs(gt_num)
            )

            if error_rate <= tolerance:
                return True

    return False


# ============================================================
# ANSWER TYPE
# ============================================================

def get_answer_type(
    model_answer,
    gt_answer,
    question
):
    """
    Determine answer type based on MODEL ANSWER.

    Priority:
    1. Year
    2. Numeric
    3. Text
    """

    # --------------------------------------------------------
    # YEAR
    # --------------------------------------------------------

    if is_year(
        model_answer,
        question
    ):
        return 'year'

    # --------------------------------------------------------
    # NUMERIC
    # --------------------------------------------------------

    if is_numeric(
        model_answer
    ):
        return 'numeric'

    # --------------------------------------------------------
    # TEXT
    # --------------------------------------------------------

    return 'text'


# ============================================================
# LEVENSHTEIN DISTANCE
# ============================================================

def levenshtein_distance(s1, s2):

    if s1 == s2:
        return 0

    if len(s1) == 0:
        return len(s2)

    if len(s2) == 0:
        return len(s1)

    # Pastikan s2 lebih pendek
    if len(s1) < len(s2):
        s1, s2 = s2, s1

    previous_row = list(
        range(len(s2) + 1)
    )

    for i, c1 in enumerate(
        s1,
        start=1
    ):

        current_row = [i]

        for j, c2 in enumerate(
            s2,
            start=1
        ):

            insertion = (
                current_row[j - 1] + 1
            )

            deletion = (
                previous_row[j] + 1
            )

            substitution = (
                previous_row[j - 1]
                + (c1 != c2)
            )

            current_row.append(
                min(
                    insertion,
                    deletion,
                    substitution
                )
            )

        previous_row = current_row

    return previous_row[-1]


# ============================================================
# NORMALIZED LEVENSHTEIN SIMILARITY (NLS)
# ============================================================

def compute_nls(gt, pred):
    """
    Normalized Levenshtein Similarity (NLS) tanpa threshold.
    Nilai berada pada rentang 0–1.
    """

    gt = clean_answer_text(gt).lower()
    pred = clean_answer_text(pred).lower()

    if gt == pred:
        return 1.0

    if not gt or not pred:
        return 0.0

    distance = levenshtein_distance(
        gt,
        pred
    )

    max_len = max(
        len(gt),
        len(pred)
    )

    return 1.0 - (
        distance / max_len
    )


def compute_nls_with_threshold(
    gt,
    pred,
    threshold=NLS_THRESHOLD
):
    """
    NLS dengan threshold.

    Jika NLS >= threshold,
    nilai NLS dipertahankan.

    Jika NLS < threshold,
    skor menjadi 0.
    """

    nls = compute_nls(
        gt,
        pred
    )

    if nls >= threshold:
        return nls

    return 0.0


# ============================================================
# EXACT MATCH
# ============================================================

def compute_em(
    model_answer,
    gt_answer
):

    model_str = clean_answer_text(
        model_answer
    )

    gt_str = clean_answer_text(
        gt_answer
    )

    return (
        1.0
        if model_str == gt_str
        else 0.0
    )


# ============================================================
# RELAXED ACCURACY
# ============================================================

def compute_relaxed_accuracy(
    model_val,
    gt_val,
    tolerance=NUMERIC_TOLERANCE
):

    return (
        1.0
        if numeric_equal(
            model_val,
            gt_val,
            tolerance
        )
        else 0.0
    )


# ============================================================
# SCORE SAMPLE
# ============================================================

def score_sample(
    model_answer,
    gt_answer,
    question,
    question_type
):
    """
    Evaluation logic:

    Numeric:
        Score = Relaxed Accuracy

    Year:
        Score = EM
        NLS with threshold dan NLS without threshold
        dihitung sebagai metrik tambahan.

    Text:
        Score = NLS without threshold
        EM dan NLS with threshold
        dihitung sebagai metrik tambahan.

    Answer type ditentukan berdasarkan MODEL ANSWER.

    Parameter question_type diterima untuk menjaga konteks
    question type, tetapi tidak memaksa answer type tertentu.
    """

    # ========================================================
    # DETERMINE TYPE
    # ========================================================

    answer_type = get_answer_type(
        model_answer,
        gt_answer,
        question
    )

    # ========================================================
    # NUMERIC
    # ========================================================

    if answer_type == 'numeric':

        relaxed_acc = compute_relaxed_accuracy(
            model_answer,
            gt_answer
        )

        return {
            'score': relaxed_acc,
            'answer_type': 'numeric',
            'metric_used': 'Relaxed Accuracy',

            'em': None,
            'nls_with_threshold': None,
            'nls_without_threshold': None,
            'relaxed_acc': relaxed_acc
        }

    # ========================================================
    # YEAR
    # ========================================================

    elif answer_type == 'year':

        # ----------------------------------------------------
        # EM
        # ----------------------------------------------------

        em = compute_em(
            model_answer,
            gt_answer
        )

        # ----------------------------------------------------
        # NLS WITHOUT THRESHOLD
        # ----------------------------------------------------

        nls_without_threshold = compute_nls(
            model_answer,
            gt_answer
        )

        # ----------------------------------------------------
        # NLS WITH THRESHOLD
        # ----------------------------------------------------

        nls_with_threshold = compute_nls_with_threshold(
            model_answer,
            gt_answer
        )

        # Score utama YEAR = EM
        score = em

        return {
            'score': score,
            'answer_type': 'year',
            'metric_used': 'EM',

            'em': em,
            'nls_with_threshold': nls_with_threshold,
            'nls_without_threshold': nls_without_threshold,
            'relaxed_acc': None
        }

    # ========================================================
    # TEXT
    # ========================================================

    else:

        em = compute_em(
            model_answer,
            gt_answer
        )

        nls_without_threshold = compute_nls(
            model_answer,
            gt_answer
        )

        nls_with_threshold = compute_nls_with_threshold(
            model_answer,
            gt_answer
        )

        # Score utama TEXT = NLS without threshold
        score = nls_without_threshold

        return {
            'score': score,
            'answer_type': 'text',
            'metric_used': 'NLS without threshold',

            'em': em,
            'nls_without_threshold': nls_without_threshold,
            'nls_with_threshold': nls_with_threshold,
            'relaxed_acc': None
        }


# ============================================================
# PARSE FILENAME
# ============================================================

def parse_filename(filename):

    name = filename.replace(
        '.jsonl',
        ''
    )

    pattern = (
        r'([A-Z]{2,})'
        r'(Sum|Average|Min|Max|Ranking|Compare|Selection)$'
    )

    match = re.search(
        pattern,
        name
    )

    if match:

        chart_type = match.group(1)
        question_type = match.group(2)

        return (
            chart_type,
            question_type
        )

    return None, None


# ============================================================
# RECLASSIFY QUESTION TYPE
# ============================================================

def classify_question_type(
    model_answer,
    question,
    original_question_type
):
    """
    Menentukan question type akhir berdasarkan model answer
    dan keyword pada pertanyaan.

    Reklasifikasi hanya dilakukan untuk Sum dan Average.

    Ketentuan:
    - Jika model answer numeric:
        tetap menggunakan original question type.
    - Jika model answer nonnumeric:
        cek keyword pertanyaan.
    - Tipe selain Sum/Average:
        tetap menggunakan original question type.
    """

    # --------------------------------------------------------
    # Hanya Sum dan Average yang dapat direklasifikasi
    # --------------------------------------------------------

    if original_question_type not in [
        "Sum",
        "Average"
    ]:
        return original_question_type

    # --------------------------------------------------------
    # Jika model answer numeric,
    # tetap menggunakan tipe pertanyaan asli
    # --------------------------------------------------------

    if is_numeric(model_answer):
        return original_question_type

    # --------------------------------------------------------
    # Model answer nonnumeric
    # → cek keyword pertanyaan
    # --------------------------------------------------------

    question_lower = clean_answer_text(
        question
    ).lower()

    # --------------------------------------------------------
    # MIN
    # --------------------------------------------------------

    if "terendah" or "terkecil" in question_lower:
        return "Min"

    # --------------------------------------------------------
    # MAX
    # --------------------------------------------------------

    if "tertinggi" or "paling banyak" or "terbesar" in question_lower:
        return "Max"

    # --------------------------------------------------------
    # COMPARE
    # --------------------------------------------------------

    compare_keywords = [
        "lebih tinggi",
        "lebih kecil",
        "lebih banyak",
        "lebih sedikit",
        "lebih besar",
        "lebih rendah",
        "daripada",
        "lebih dari"
    ]

    if any(
        keyword in question_lower
        for keyword in compare_keywords
    ):
        return "Compare"

    # --------------------------------------------------------
    # Jika tidak memenuhi aturan apa pun,
    # tetap gunakan tipe asli
    # --------------------------------------------------------

    return original_question_type


# ============================================================
# EVALUATE PoT COMMANDS
# ============================================================

def evaluate_cmds(cmds):

    env = {
        "np": np
    }

    for cmd in cmds:

        exec(
            cmd,
            env
        )

    answer = env["Answer"]

    # ========================================================
    # LIST / ARRAY WITH ONE ELEMENT
    # ========================================================

    if (
        isinstance(
            answer,
            (
                list,
                np.ndarray
            )
        )
        and len(answer) == 1
    ):

        answer = answer[0]

    # ========================================================
    # LIST / ARRAY WITH MULTIPLE ELEMENTS
    # ========================================================

    if isinstance(
        answer,
        (
            list,
            np.ndarray
        )
    ):

        answer = [
            str(x)
            for x in answer
        ]

        if len(answer) == 0:
            return ""

        if len(answer) == 1:
            return answer[0]

        if len(answer) == 2:

            return (
                answer[0]
                + ' and '
                + answer[1]
            )

        new_answer = answer[0]

        for i in range(
            1,
            len(answer) - 1
        ):

            new_answer += (
                ', '
                + answer[i]
            )

        new_answer += (
            ' and '
            + answer[-1]
        )

        answer = new_answer

    # ========================================================
    # BOOLEAN
    # ========================================================

    if isinstance(
        answer,
        (
            bool,
            np.bool_
        )
    ):

        answer = (
            "Yes"
            if answer
            else "No"
        )

    return answer


# ============================================================
# RESOLVE ANSWER
# ============================================================

def resolve_answer(answer):

    answer = clean_answer_text(
        answer
    )

    # ========================================================
    # CHECK PoT
    # ========================================================

    if (
        "<step>" in answer
        or "<comment>" in answer
        or "Answer =" in answer
    ):

        original_answer = answer

        try:

            # ------------------------------------------------
            # Remove comments
            # ------------------------------------------------

            answer = re.sub(
                r"<comment>.*?</comment>",
                "",
                answer,
                flags=re.DOTALL
            )

            # ------------------------------------------------
            # Remove step tags
            # ------------------------------------------------

            answer = answer.replace(
                "<step>",
                ""
            )

            answer = answer.replace(
                "</step>",
                "\n"
            )

            # ------------------------------------------------
            # Split commands
            # ------------------------------------------------

            cmds = [
                cmd.strip()
                for cmd in answer.split("\n")
                if cmd.strip()
            ]

            # ------------------------------------------------
            # Evaluate
            # ------------------------------------------------

            result = evaluate_cmds(
                cmds
            )

            return clean_answer_text(
                result
            )

        except Exception:

            return original_answer

    # ========================================================
    # NON-PoT
    # ========================================================

    return answer


# ============================================================
# NORMALIZE BOOLEAN
# ============================================================

def normalize_boolean_answer(answer):

    answer = clean_answer_text(
        answer
    )

    mapping = {

        "True": "Ya",
        "False": "Tidak",

        "true": "Ya",
        "false": "Tidak",

        "TRUE": "Ya",
        "FALSE": "Tidak",

        "Yes": "Ya",
        "No": "Tidak",

        "yes": "Ya",
        "no": "Tidak",

        "YES": "Ya",
        "NO": "Tidak"
    }

    return mapping.get(
        answer,
        answer
    )


# ============================================================
# EVALUATE JSONL FILES
# ============================================================

def evaluate_jsonl_files(directory):

    results = defaultdict(
        lambda: {
            'count': 0,
            'scores': [],

            # ------------------------------------------------
            # EM, NLS hanya untuk
            # text + year
            # ------------------------------------------------

            'em_scores': [],
            'nls_without_threshold_scores': [],
            'nls_with_threshold_scores': [],
            'relaxed_acc_scores': [],

            # ------------------------------------------------
            # Jumlah sampel yang diukur
            # oleh masing-masing metrik
            # ------------------------------------------------

            'em_count': 0,
            'nls_without_threshold_count': 0,
            'nls_with_threshold_count': 0,
            'relaxed_acc_count': 0
        }
    )

    ranking_answer_types = Counter()
    ranking_numeric_examples = []

    average_answer_types = Counter()
    average_non_numeric_examples = []

    # ========================================================
    # FIND JSONL
    # ========================================================

    jsonl_files = sorted(
        Path(directory).glob(
            '*.jsonl'
        )
    )

    if not jsonl_files:

        print(
            f"No JSONL files found in {directory}"
        )

        return None

    print(
        f"Found {len(jsonl_files)} JSONL files"
    )

    # ========================================================
    # RESOLVED DIRECTORY
    # ========================================================

    resolved_directory = Path(
        '/kaggle/working/resolved_jsonl'
    )

    resolved_directory.mkdir(
        parents=True,
        exist_ok=True
    )

    total_records = 0

    # ========================================================
    # PROCESS FILES
    # ========================================================

    for jsonl_file in jsonl_files:

        chart_type, original_question_type = parse_filename(
            jsonl_file.name
        )

        if (
            not chart_type
            or not original_question_type
        ):

            print(
                f"⚠️ Skipping "
                f"{jsonl_file.name} "
                f"- couldn't parse filename"
            )

            continue

        resolved_file = (
            resolved_directory
            / jsonl_file.name
        )

        try:

            with open(
                jsonl_file,
                'r',
                encoding='utf-8'
            ) as f, open(
                resolved_file,
                'w',
                encoding='utf-8'
            ) as out:

                for line in f:

                    if not line.strip():
                        continue

                    record = json.loads(
                        line
                    )

                    # =================================================
                    # ORIGINAL VALUES
                    # =================================================

                    model_answer = record.get(
                        'model_answer',
                        ''
                    )

                    gt_answer = record.get(
                        'gt_answer',
                        ''
                    )

                    question = record.get(
                        'question',
                        ''
                    )

                    # =================================================
                    # RESOLVE PoT
                    # =================================================

                    model_answer = resolve_answer(
                        model_answer
                    )

                    gt_answer = resolve_answer(
                        gt_answer
                    )

                    # =================================================
                    # NORMALIZE BOOLEAN
                    # =================================================

                    model_answer = normalize_boolean_answer(
                        model_answer
                    )

                    gt_answer = normalize_boolean_answer(
                        gt_answer
                    )

                    # =================================================
                    # FINAL QUESTION TYPE
                    # =================================================

                    final_question_type = (
                        classify_question_type(
                            model_answer,
                            question,
                            original_question_type
                        )
                    )

                    # =================================================
                    # GROUP KEY
                    #
                    # IMPORTANT:
                    # Menggunakan FINAL question type.
                    # =================================================

                    group_key = (
                        chart_type,
                        final_question_type
                    )

                    # =================================================
                    # UPDATE ANSWERS
                    # =================================================

                    record['model_answer'] = (
                        model_answer
                    )

                    record['gt_answer'] = (
                        gt_answer
                    )

                    record[
                        'original_question_type'
                    ] = (
                        original_question_type
                    )

                    record[
                        'question_type'
                    ] = (
                        final_question_type
                    )

                    # =================================================
                    # SCORE
                    # =================================================

                    metrics = score_sample(
                        model_answer,
                        gt_answer,
                        question,
                        final_question_type
                    )

                    # =================================================
                    # AVERAGE ANSWER TYPE CHECK
                    # =================================================

                    if original_question_type == "Average":

                        answer_type = metrics[
                            'answer_type'
                        ]

                        average_answer_types[
                            answer_type
                        ] += 1

                        if answer_type != "numeric":

                            average_non_numeric_examples.append({
                                "id": record.get(
                                    "id",
                                    ""
                                ),
                                "original_question_type":
                                    original_question_type,
                                "final_question_type":
                                    final_question_type,
                                "question":
                                    question,
                                "gt_answer":
                                    gt_answer,
                                "model_answer":
                                    model_answer,
                                "answer_type":
                                    answer_type,
                                "score":
                                    metrics['score'],
                                "metric_used":
                                    metrics['metric_used']
                            })

                    # =================================================
                    # SAVE METRICS
                    # =================================================

                    record['score'] = (
                        metrics['score']
                    )

                    record['answer_type'] = (
                        metrics['answer_type']
                    )

                    record['metric_used'] = (
                        metrics['metric_used']
                    )

                    record['relaxed_acc'] = (
                        metrics['relaxed_acc']
                    )

                    record['em'] = (
                        metrics['em']
                    )

                    record[
                        'nls_without_threshold'
                    ] = (
                        metrics[
                            'nls_without_threshold'
                        ]
                    )

                    record[
                        'nls_with_threshold'
                    ] = (
                        metrics[
                            'nls_with_threshold'
                        ]
                    )

                    # =================================================
                    # RANKING CHECK
                    # =================================================

                    if original_question_type == "Ranking":

                        answer_type = get_answer_type(
                            model_answer,
                            gt_answer,
                            question
                        )

                        ranking_answer_types[
                            answer_type
                        ] += 1

                        if answer_type == "numeric":

                            ranking_numeric_examples.append({
                                "question":
                                    question,
                                "gt_answer":
                                    gt_answer,
                                "model_answer":
                                    model_answer
                            })

                    # =================================================
                    # SAVE RESOLVED + EVALUATED RECORD
                    # =================================================

                    out.write(
                        json.dumps(
                            record,
                            ensure_ascii=False
                        )
                        + '\n'
                    )

                    # =================================================
                    # UPDATE AGGREGATE
                    # =================================================

                    results[group_key]['count'] += 1

                    results[group_key]['scores'].append(
                        metrics['score']
                    )

                    # -------------------------------------------------
                    # EM
                    # -------------------------------------------------

                    if metrics['em'] is not None:

                        results[group_key][
                            'em_scores'
                        ].append(
                            metrics['em']
                        )

                        results[group_key][
                            'em_count'
                        ] += 1

                    # -------------------------------------------------
                    # NLS WITHOUT THRESHOLD
                    # -------------------------------------------------

                    if (
                        metrics[
                            'nls_without_threshold'
                        ] is not None
                    ):

                        results[group_key][
                            'nls_without_threshold_scores'
                        ].append(
                            metrics[
                                'nls_without_threshold'
                            ]
                        )

                        results[group_key][
                            'nls_without_threshold_count'
                        ] += 1

                    # -------------------------------------------------
                    # NLS WITH THRESHOLD
                    # -------------------------------------------------

                    if (
                        metrics[
                            'nls_with_threshold'
                        ] is not None
                    ):

                        results[group_key][
                            'nls_with_threshold_scores'
                        ].append(
                            metrics[
                                'nls_with_threshold'
                            ]
                        )

                        results[group_key][
                            'nls_with_threshold_count'
                        ] += 1

                    # -------------------------------------------------
                    # RELAXED ACCURACY
                    # -------------------------------------------------

                    if metrics['relaxed_acc'] is not None:

                        results[group_key][
                            'relaxed_acc_scores'
                        ].append(
                            metrics[
                                'relaxed_acc'
                            ]
                        )

                        results[group_key][
                            'relaxed_acc_count'
                        ] += 1

                    total_records += 1

        except Exception as e:

            print(
                f"ERROR processing "
                f"{jsonl_file.name}: {e}"
            )

            continue

    # ========================================================
    # AGGREGATE
    # ========================================================

    data = []

    for (
        chart_type,
        question_type
    ), metrics_dict in sorted(
        results.items()
    ):

        row = {

            'chart_type':
                chart_type,

            'question_type':
                question_type,

            # ------------------------------------------------
            # Total sampel
            # ------------------------------------------------

            'count':
                metrics_dict['count'],

            # ------------------------------------------------
            # Jumlah sampel yang diukur
            # oleh masing-masing metrik
            # ------------------------------------------------

            'em_count':
                metrics_dict['em_count'],

            'nls_without_threshold_count':
                metrics_dict[
                    'nls_without_threshold_count'
                ],

            'nls_with_threshold_count':
                metrics_dict[
                    'nls_with_threshold_count'
                ],

            'relaxed_acc_count':
                metrics_dict[
                    'relaxed_acc_count'
                ],

            # ------------------------------------------------
            # Overall score
            #
            # Text -> NLS without threshold
            # Year -> EM
            # Numeric -> Relaxed Accuracy
            # ------------------------------------------------

            'avg_score':
                np.mean(
                    metrics_dict['scores']
                ),

            # ------------------------------------------------
            # Numeric
            # ------------------------------------------------

            'avg_relaxed_acc':
                np.mean(
                    metrics_dict[
                        'relaxed_acc_scores'
                    ]
                )
                if metrics_dict[
                    'relaxed_acc_scores'
                ]
                else None,

            # ------------------------------------------------
            # Text + Year
            # ------------------------------------------------

            'avg_em':
                np.mean(
                    metrics_dict[
                        'em_scores'
                    ]
                )
                if metrics_dict[
                    'em_scores'
                ]
                else None,

            'avg_nls_without_threshold':
                np.mean(
                    metrics_dict[
                        'nls_without_threshold_scores'
                    ]
                )
                if metrics_dict[
                    'nls_without_threshold_scores'
                ]
                else None,

            'avg_nls_with_threshold':
                np.mean(
                    metrics_dict[
                        'nls_with_threshold_scores'
                    ]
                )
                if metrics_dict[
                    'nls_with_threshold_scores'
                ]
                else None,
        }

        data.append(row)

    df = pd.DataFrame(
        data
    )

    # ========================================================
    # ROUND
    # ========================================================

    numeric_cols = [
        'avg_score',
        'avg_relaxed_acc',
        'avg_em',
        'avg_nls_without_threshold',
        'avg_nls_with_threshold'
    ]

    for col in numeric_cols:

        if col in df.columns:

            df[col] = df[col].round(4)

    # ========================================================
    # SUMMARY
    # ========================================================

    print(
        f"\nTotal records processed: "
        f"{total_records}"
    )

    print(
        f"Resolved + evaluated JSONL saved to: "
        f"{resolved_directory}"
    )

    # ========================================================
    # RANKING TYPE SUMMARY
    # ========================================================

    if ranking_answer_types:

        print(
            "\nRanking answer types:"
        )

        for (
            answer_type,
            count
        ) in ranking_answer_types.items():

            print(
                f"  {answer_type}: "
                f"{count}"
            )

    # ========================================================
    # AVERAGE TYPE SUMMARY
    # ========================================================

    if average_answer_types:

        print(
            "\nAverage answer types:"
        )

        for (
            answer_type,
            count
        ) in average_answer_types.items():

            print(
                f"  {answer_type}: "
                f"{count}"
            )

    # ========================================================
    # OVERALL METRICS
    # ========================================================

    all_scores = []
    all_em_scores = []
    all_nls_without_threshold_scores = []
    all_nls_with_threshold_scores = []
    all_relaxed_acc_scores = []

    for group_metrics in results.values():

        all_scores.extend(
            group_metrics['scores']
        )

        all_em_scores.extend(
            group_metrics['em_scores']
        )

        all_nls_without_threshold_scores.extend(
            group_metrics[
                'nls_without_threshold_scores'
            ]
        )

        all_nls_with_threshold_scores.extend(
            group_metrics[
                'nls_with_threshold_scores'
            ]
        )

        all_relaxed_acc_scores.extend(
            group_metrics[
                'relaxed_acc_scores'
            ]
        )

    # --------------------------------------------------------
    # Overall Average Score
    # Semua sample
    # --------------------------------------------------------

    overall_avg_score = (
        np.mean(all_scores)
        if all_scores
        else None
    )

    # --------------------------------------------------------
    # Overall Average Relaxed Accuracy
    # Numeric saja
    # --------------------------------------------------------

    overall_avg_relaxed_acc = (
        np.mean(all_relaxed_acc_scores)
        if all_relaxed_acc_scores
        else None
    )

    # --------------------------------------------------------
    # Overall Average EM
    # Text + Year
    # --------------------------------------------------------

    overall_avg_em = (
        np.mean(all_em_scores)
        if all_em_scores
        else None
    )

    # --------------------------------------------------------
    # Overall Average NLS without threshold
    # Text + Year
    # --------------------------------------------------------

    overall_avg_nls_without_threshold = (
        np.mean(
            all_nls_without_threshold_scores
        )
        if all_nls_without_threshold_scores
        else None
    )

    # --------------------------------------------------------
    # Overall Average NLS with threshold
    # Text + Year
    # --------------------------------------------------------

    overall_avg_nls_with_threshold = (
        np.mean(
            all_nls_with_threshold_scores
        )
        if all_nls_with_threshold_scores
        else None
    )

    # ========================================================
    # JUMLAH SAMPEL UNTUK OVERALL METRIK
    # ========================================================

    overall_em_count = len(
        all_em_scores
    )

    overall_nls_without_threshold_count = len(
        all_nls_without_threshold_scores
    )

    overall_nls_with_threshold_count = len(
        all_nls_with_threshold_scores
    )

    overall_relaxed_acc_count = len(
        all_relaxed_acc_scores
    )

    # ========================================================
    # RETURN
    # ========================================================

    summary = {

        'total_samples':
            total_records,

        'overall_avg_score':
            overall_avg_score,

        'overall_avg_relaxed_acc':
            overall_avg_relaxed_acc,

        'overall_avg_em':
            overall_avg_em,

        'overall_avg_nls_without_threshold':
            overall_avg_nls_without_threshold,

        'overall_avg_nls_with_threshold':
            overall_avg_nls_with_threshold,

        # ----------------------------------------------------
        # Jumlah sampel tiap metrik
        # ----------------------------------------------------

        'overall_em_count':
            overall_em_count,

        'overall_nls_without_threshold_count':
            overall_nls_without_threshold_count,

        'overall_nls_with_threshold_count':
            overall_nls_with_threshold_count,

        'overall_relaxed_acc_count':
            overall_relaxed_acc_count
    }

    return df, summary


# ============================================================
# MAIN
# ============================================================

if __name__ == '__main__':

    # ========================================================
    # INPUT DIRECTORY
    # ========================================================

    # jsonl_directory = (
    #     "/kaggle/input/datasets/"
    #     "dianshinta09/eval-results-ver2/"
    # )

    jsonl_directory = (
        "/kaggle/input/datasets/"
        "dianshinta09/evaluation-result-tinycart/eval/"
    )

    # ========================================================
    # EVALUATION
    # ========================================================

    evaluation_output = evaluate_jsonl_files(
        jsonl_directory
    )

    if evaluation_output is not None:

        df_results, summary = evaluation_output

        print(
            "\n"
            + "=" * 80
        )

        print(
            "EVALUATION RESULTS"
        )

        print(
            "=" * 80
        )

        print(
            df_results.to_string(
                index=False
            )
        )

        print(
            "=" * 80
        )

        # ====================================================
        # SUMMARY
        # ====================================================

        print(
            "\nSUMMARY:"
        )

        print(
            f"Total chart types: "
            f"{df_results['chart_type'].nunique()}"
        )

        print(
            f"Total question types: "
            f"{df_results['question_type'].nunique()}"
        )

        print(
            f"Total samples: "
            f"{summary['total_samples']}"
        )

        print(
            f"Overall Average Score: "
            f"{summary['overall_avg_score']:.4f}"
        )

        print(
            f"Overall Average Exact Match "
            f"(Text + Year): "
            f"{summary['overall_avg_em']:.4f}"
            f" "
            f"(n={summary['overall_em_count']})"
        )

        print(
            f"Overall Average Normalized Lev Similarity "
            f"without threshold (Text + Year): "
            f"{summary['overall_avg_nls_without_threshold']:.4f}"
            f" "
            f"(n={summary['overall_nls_without_threshold_count']})"
        )

        print(
            f"Overall Average Normalized Lev Similarity "
            f"with threshold (Text + Year): "
            f"{summary['overall_avg_nls_with_threshold']:.4f}"
            f" "
            f"(n={summary['overall_nls_with_threshold_count']})"
        )

        print(
            f"Overall Average Relaxed Accuracy "
            f"(Numeric): "
            f"{summary['overall_avg_relaxed_acc']:.4f}"
            f" "
            f"(n={summary['overall_relaxed_acc_count']})"
        )

        # ====================================================
        # SAVE CSV
        # ====================================================

        output_file = (
            '/kaggle/working/'
            'evaluation_results.csv'
        )

        df_results.to_csv(
            output_file,
            index=False
        )

        print(
            f"\n✓ Results saved to "
            f"{output_file}"
        )

        # ====================================================
        # ZIP RESOLVED + EVALUATED JSONL
        # ====================================================

        resolved_directory = Path(
            '/kaggle/working/resolved_jsonl'
        )

        zip_file = (
            '/kaggle/working/'
            'resolved_jsonl.zip'
        )

        jsonl_files_resolved = sorted(
            resolved_directory.glob(
                '*.jsonl'
            )
        )

        with zipfile.ZipFile(
            zip_file,
            'w',
            zipfile.ZIP_DEFLATED
        ) as zipf:

            for jsonl_file in jsonl_files_resolved:

                zipf.write(
                    jsonl_file,
                    arcname=jsonl_file.name
                )

        # ====================================================
        # ZIP INFO
        # ====================================================

        zip_size_mb = (
            os.path.getsize(
                zip_file
            )
            / (1024 * 1024)
        )

        print(
            f"\n✓ Resolved + evaluated JSONL ZIP saved to: "
            f"{zip_file}"
        )

        print(
            f"✓ Total JSONL files in ZIP: "
            f"{len(jsonl_files_resolved)}"
        )

        print(
            f"✓ ZIP size: "
            f"{zip_size_mb:.2f} MB"
        )

Found 1337 JSONL files

<string>:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
<string>:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
<string>:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?

Total records processed: 11830
Resolved + evaluated JSONL saved to: /kaggle/working/resolved_jsonl

Ranking answer types:
  text: 1547
  numeric: 121
  year: 22

Average answer types:
  numeric: 1640
  text: 49
  year: 1

================================================================================
EVALUATION RESULTS
================================================================================
chart_type question_type  count  em_count  nls_without_threshold_count  nls_with_threshold_count  relaxed_acc_count  avg_score  avg_relaxed_acc  avg_em  avg_nls_without_threshold  avg_nls_with_threshold
       BAR       Average    734         1                            1                         1                733     0.5572           0.5580  0.0000                     0.0556                  0.0000
       BAR       Compare    760       729                          729                       729                 31     0.7354           0.4516  0.6968                     0.7492                  0.7155
       BAR           Max    760       641                          641                       641                119     0.7363           0.7899  0.6537                     0.7346                  0.6882
       BAR           Min    796       676                          676                       676                120     0.6054           0.5750  0.4556                     0.6171                  0.5402
       BAR       Ranking    760       694                          694                       694                 66     0.3234           0.5152  0.0893                     0.3063                  0.1847
       BAR     Selection    760         8                            8                         8                752     0.7802           0.7859  0.0000                     0.2441                  0.0865
       BAR           Sum    750         0                            0                         0                750     0.3760           0.3760     NaN                        NaN                     NaN
      GBAR       Average    552         0                            0                         0                552     0.5580           0.5580     NaN                        NaN                     NaN
      GBAR       Compare    560       560                          560                       560                  0     0.8635              NaN  0.8357                     0.8635                  0.8357
      GBAR           Max    560       301                          301                       301                259     0.7626           0.6100  0.6910                     0.8939                  0.8797
      GBAR           Min    580       354                          354                       354                226     0.5870           0.3496  0.5876                     0.7387                  0.6871
      GBAR       Ranking    560       511                          511                       511                 49     0.4095           0.1429  0.2231                     0.4354                  0.3579
      GBAR     Selection    560         0                            0                         0                560     0.7232           0.7232     NaN                        NaN                     NaN
      GBAR           Sum    548         0                            0                         0                548     0.4653           0.4653     NaN                        NaN                     NaN
      LINE       Average    355         0                            0                         0                355     0.6479           0.6479     NaN                        NaN                     NaN
      LINE       Compare    370       353                          353                       353                 17     0.7529           0.6471  0.7054                     0.7648                  0.7220
      LINE           Max    370       301                          301                       301                 69     0.8062           0.8696  0.7342                     0.7917                  0.7392
      LINE           Min    395       344                          344                       344                 51     0.7745           0.6275  0.7500                     0.8145                  0.7938
      LINE       Ranking    370       364                          364                       364                  6     0.3180           0.0000  0.1099                     0.3399                  0.2378
      LINE     Selection    370         5                            5                         5                365     0.9225           0.9315  0.0000                     0.2667                  0.1000
      LINE           Sum    360         0                            0                         0                360     0.3861           0.3861     NaN                        NaN                     NaN
================================================================================

SUMMARY:
Total chart types: 3
Total question types: 7
Total samples: 11830
Overall Average Score: 0.6162
Overall Average Exact Match (Text + Year): 0.5243 (n=5842)
Overall Average Normalized Lev Similarity without threshold (Text + Year): 0.6503 (n=5842)
Overall Average Normalized Lev Similarity with threshold (Text + Year): 0.5911 (n=5842)
Overall Average Relaxed Accuracy (Numeric): 0.5873 (n=5988)

✓ Results saved to /kaggle/working/evaluation_results.csv

✓ Resolved + evaluated JSONL ZIP saved to: /kaggle/working/resolved_jsonl.zip
✓ Total JSONL files in ZIP: 1337
✓ ZIP size: 0.69 MB

In [17]:
!pip install -q datasets huggingface_hub

In [20]:
from datasets import load_dataset
import pandas as pd
import re
from collections import Counter


# ============================================================
# 1. LOAD DATASET
# ============================================================

REPO_1 = "shiinn97/indochartqa"
REPO_2 = "shiinn97/indochartqav2"

ds1 = load_dataset(REPO_1, split="train")
ds2 = load_dataset(REPO_2, split="train")

print("Dataset 1:", REPO_1)
print("Jumlah train:", len(ds1))
print("Kolom:", ds1.column_names)

print("\nDataset 2:", REPO_2)
print("Jumlah train:", len(ds2))
print("Kolom:", ds2.column_names)

README.md:   0%|          | 0.00/636 [00:00<?, ?B/s]

data/train-00000-of-00001.parquet:   0%|          | 0.00/1.76M [00:00<?, ?B/s]

data/validation-00000-of-00001.parquet:   0%|          | 0.00/236k [00:00<?, ?B/s]

data/test-00000-of-00001.parquet:   0%|          | 0.00/246k [00:00<?, ?B/s]

Generating train split:   0%|          | 0/81592 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/11256 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/11830 [00:00<?, ? examples/s]

README.md:   0%|          | 0.00/637 [00:00<?, ?B/s]

data/train-00000-of-00001.parquet:   0%|          | 0.00/27.7M [00:00<?, ?B/s]

data/validation-00000-of-00001.parquet:   0%|          | 0.00/3.86M [00:00<?, ?B/s]

data/test-00000-of-00001.parquet:   0%|          | 0.00/4.27M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/78510 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/10663 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/11050 [00:00<?, ? examples/s]

Dataset 1: shiinn97/indochartqa
Jumlah train: 81592
Kolom: ['id', 'image', 'conversations']

Dataset 2: shiinn97/indochartqav2
Jumlah train: 78510
Kolom: ['id', 'image', 'conversations']

In [26]:
def extract_qa(row):
    """
    Mengambil question dan answer dari struktur conversations.
    """

    question = ""
    answer = ""

    # Format conversations
    if "conversations" in row and row["conversations"] is not None:
        conv = row["conversations"]

        for item in conv:
            role = item.get("from", "")
            value = item.get("value", "")

            if role == "human":
                question = value

            elif role == "gpt":
                answer = value

    # Kalau dataset langsung punya kolom question/answer
    elif "question" in row:
        question = row.get("question", "")

        if "answer" in row:
            answer = row.get("answer", "")
        elif "gt_answer" in row:
            answer = row.get("gt_answer", "")

    return question, answer

def get_id(row):
    return str(row.get("id", ""))


def detect_question_type(row):
    id_value = get_id(row)

    # Prioritas dari ID
    patterns = [
        ("Selection", r"Selection"),
        ("Average", r"Average"),
        ("Ranking", r"Ranking"),
        ("Compare", r"Compare"),
        ("Min", r"Min"),
        ("Max", r"Max"),
        ("Sum", r"Sum"),
    ]

    for qtype, pattern in patterns:
        if re.search(pattern, id_value, flags=re.IGNORECASE):
            return qtype

    return "Unknown"

def detect_chart_type(row):
    id_value = get_id(row).lower()

    if "gbar" in id_value:
        return "GBar"

    if "bar" in id_value:
        return "Bar"

    if "line" in id_value:
        return "Line"

    return "Unknown"

def detect_pot(question):
    if "jawab menggunakan langkah perhitungannya" in question.lower():
        return "PoT"

    return "Non-PoT"

def dataset_to_df(ds):

    records = []

    for row in ds:

        question, answer = extract_qa(row)

        records.append({
            "id": get_id(row),
            "question": question,
            "answer": answer,
            "question_type": detect_question_type(row),
            "chart_type": detect_chart_type(row),
            "pot_type": detect_pot(question),
            "question_length": len(question),
            "answer_length": len(str(answer)),
        })

    return pd.DataFrame(records)


df1 = dataset_to_df(ds1)
df2 = dataset_to_df(ds2)

summary = pd.DataFrame({
    "Dataset 1": [
        len(df1),
        df1["question_type"].nunique(),
        df1["chart_type"].nunique(),
    ],
    "Dataset 2": [
        len(df2),
        df2["question_type"].nunique(),
        df2["chart_type"].nunique(),
    ]
}, index=[
    "Jumlah train",
    "Jumlah question type",
    "Jumlah chart type"
])

display(summary)

question_dist = pd.concat([
    df1["question_type"].value_counts().rename("Dataset 1"),
    df2["question_type"].value_counts().rename("Dataset 2")
], axis=1).fillna(0)

question_dist["Dataset 1 (%)"] = (
    question_dist["Dataset 1"] / len(df1) * 100
)

question_dist["Dataset 2 (%)"] = (
    question_dist["Dataset 2"] / len(df2) * 100
)

question_dist = question_dist.sort_index()

display(question_dist)

chart_dist = pd.concat([
    df1["chart_type"].value_counts().rename("Dataset 1"),
    df2["chart_type"].value_counts().rename("Dataset 2")
], axis=1).fillna(0)

chart_dist["Dataset 1 (%)"] = (
    chart_dist["Dataset 1"] / len(df1) * 100
)

chart_dist["Dataset 2 (%)"] = (
    chart_dist["Dataset 2"] / len(df2) * 100
)

chart_dist = chart_dist.sort_index()

display(chart_dist)

                      Dataset 1  Dataset 2
Jumlah train              81592      78510
Jumlah question type          7          7
Jumlah chart type             3          3

               Dataset 1  Dataset 2  Dataset 1 (%)  Dataset 2 (%)
question_type
Average            11656      10666      14.285714      13.585531
Compare            11656      11526      14.285714      14.680932
Max                11656      11524      14.285714      14.678385
Min                11656      11197      14.285714      14.261877
Ranking            11656      11098      14.285714      14.135779
Selection          11656      11621      14.285714      14.801936
Sum                11656      10878      14.285714      13.855560

            Dataset 1  Dataset 2  Dataset 1 (%)  Dataset 2 (%)
chart_type
Bar             43932      41317      53.843514      52.626417
GBar            17500      17543      21.448181      22.344924
Line            20160      19650      24.708305      25.028659

In [28]:
# Distribusi Chart × Question × PoT

cross_1 = pd.crosstab(
    [df1["chart_type"], df1["question_type"]],
    df1["pot_type"]
)

cross_2 = pd.crosstab(
    [df2["chart_type"], df2["question_type"]],
    df2["pot_type"]
)

comparison = pd.concat(
    [
        cross_1.rename(columns=lambda x: f"D1_{x}"),
        cross_2.rename(columns=lambda x: f"D2_{x}")
    ],
    axis=1
).fillna(0)



comparison["Total D1"] = comparison.filter(like="D1_").sum(axis=1)
comparison["Total D2"] = comparison.filter(like="D2_").sum(axis=1)

comparison["Hilang"] = (
    comparison["Total D1"] - comparison["Total D2"]
)

comparison["Retention (%)"] = (
    comparison["Total D2"] / comparison["Total D1"] * 100
)

comparison["Removed (%)"] = (
    comparison["Hilang"] / comparison["Total D1"] * 100
)

display(
    comparison[
        [
            "Total D1",
            "Total D2",
            "Hilang",
            "Retention (%)",
            "Removed (%)"
        ]
    ].round(2)
)

pot_type                  Total D1  Total D2  Hilang  Retention (%)  \
chart_type question_type
Bar        Average            6276      5460     816          87.00
           Compare            6276      6128     148          97.64
           Max                6276      6146     130          97.93
           Min                6276      5880     396          93.69
           Ranking            6276      5889     387          93.83
           Selection          6276      6196      80          98.73
           Sum                6276      5618     658          89.52
GBar       Average            2500      2448      52          97.92
           Compare            2500      2540     -40         101.60
           Max                2500      2540     -40         101.60
           Min                2500      2523     -23         100.92
           Ranking            2500      2492       8          99.68
           Selection          2500      2540     -40         101.60
           Sum                2500      2460      40          98.40
Line       Average            2880      2758     122          95.76
           Compare            2880      2858      22          99.24
           Max                2880      2838      42          98.54
           Min                2880      2794      86          97.01
           Ranking            2880      2717     163          94.34
           Selection          2880      2885      -5         100.17
           Sum                2880      2800      80          97.22

pot_type                  Removed (%)
chart_type question_type
Bar        Average              13.00
           Compare               2.36
           Max                   2.07
           Min                   6.31
           Ranking               6.17
           Selection             1.27
           Sum                  10.48
GBar       Average               2.08
           Compare              -1.60
           Max                  -1.60
           Min                  -0.92
           Ranking               0.32
           Selection            -1.60
           Sum                   1.60
Line       Average               4.24
           Compare               0.76
           Max                   1.46
           Min                   2.99
           Ranking               5.66
           Selection            -0.17
           Sum                   2.78

# MLLMaS vs TinyChart-3B

In [6]:
!pip install -q datasets huggingface_hub

In [1]:
# ============================================================
# TARGET:
#   - 100 PoT
#   - 400 non-PoT
#
# STRATA:
#   Region × Chart Type × Question Type
#
# ATURAN:
#   - PoT dan non-PoT disampling secara stratified
#
# OUTPUT:
# 1. CSV berisi 500 sample + score
# 2. Folder berisi 500 gambar chart
#
# RANDOM SEED = 42
# ============================================================

!pip install -q datasets

import random
import pandas as pd
import json
import glob
import os
import re
import math

from collections import defaultdict
from datasets import load_dataset


# ============================================================
# CONFIG
# ============================================================

DATASET_NAME = "shiinn97/indochartqa"

SAMPLE_SIZE = 500
POT_SIZE = 100
NONPOT_SIZE = 400

RANDOM_SEED = 42

POT_PHRASE = "Jawab menggunakan langkah perhitungannya"

EVAL_DIR = "/kaggle/input/datasets/dianshinta09/evaluation-result-tinycart/eval"
IMAGE_DIR = "/kaggle/working/tinychart_images/tinychart_images/"
OUTPUT_FILE = "/kaggle/working/indochartqa_test_sample_500.csv"

os.makedirs(IMAGE_DIR, exist_ok=True)

random.seed(RANDOM_SEED)


# ============================================================
# FUNGSI PARSE ID
# ============================================================

pattern = re.compile(
    r"^([BS])\d+(BAR|GBAR|LINE)"
    r"(Sum|Average|Min|Max|Ranking|Compare|Selection)_\d+$"
)


def parse_id(sample_id):

    match = pattern.match(str(sample_id))

    if not match:
        return None

    region = match.group(1)
    chart_type = match.group(2)
    question_type = match.group(3)

    return (
        region,
        chart_type,
        question_type
    )


# ============================================================
# LOAD SCORE
# ============================================================

print("=" * 70)
print("MEMBACA SCORE")
print("=" * 70)

json_files = glob.glob(
    os.path.join(EVAL_DIR, "*.json")
)

jsonl_files = glob.glob(
    os.path.join(EVAL_DIR, "*.jsonl")
)

eval_files = json_files + jsonl_files

print(
    "Jumlah file evaluasi:",
    len(eval_files)
)

score_dict = {}

for file_path in eval_files:

    with open(
        file_path,
        "r",
        encoding="utf-8"
    ) as f:

        for line in f:

            line = line.strip()

            if not line:
                continue

            data = json.loads(line)

            if (
                "id" in data
                and "score" in data
            ):

                score_dict[
                    str(data["id"])
                ] = data["score"]


print(
    "Jumlah ID yang memiliki score:",
    len(score_dict)
)


# ============================================================
# LOAD TEST SET
# ============================================================

print("\n" + "=" * 70)
print("LOAD TEST SET")
print("=" * 70)

dataset = load_dataset(DATASET_NAME)

test_data = dataset["test"]

print(
    "Jumlah seluruh test set:",
    len(test_data)
)


# ============================================================
# FUNGSI AMBIL HUMAN QUESTION
# ============================================================

def get_human_question(conversations):

    if isinstance(conversations, str):

        conversations = json.loads(
            conversations
        )

    for message in conversations:

        if message.get("from") == "human":

            question = message.get(
                "value",
                ""
            )

            question = (
                question
                .replace("<image>\n", "")
                .replace("<image>", "")
                .strip()
            )

            return question

    return ""


# ============================================================
# FUNGSI CEK PoT
# ============================================================

def is_pot(sample):

    question = get_human_question(
        sample["conversations"]
    )

    return (
        POT_PHRASE.lower()
        in question.lower()
    )


# ============================================================
# FILTER:
# HANYA DATA YANG MEMILIKI SCORE
# ============================================================

eligible_indices = []

for idx, sample in enumerate(test_data):

    sample_id = str(sample["id"])

    if sample_id in score_dict:

        # Pastikan ID dapat diparse
        if parse_id(sample_id) is not None:

            eligible_indices.append(idx)


print("\n" + "=" * 70)
print("ELIGIBLE DATA")
print("=" * 70)

print(
    "Data yang memiliki score:",
    len(eligible_indices)
)


# ============================================================
# KELOMPOKKAN PoT DAN NON-PoT
# ============================================================

pot_indices = []
nonpot_indices = []

for idx in eligible_indices:

    sample = test_data[idx]

    if is_pot(sample):

        pot_indices.append(idx)

    else:

        nonpot_indices.append(idx)


print("\n" + "=" * 70)
print("DISTRIBUSI PoT / NON-PoT")
print("=" * 70)

print(
    "PoT     :",
    len(pot_indices)
)

print(
    "non-PoT :",
    len(nonpot_indices)
)


# ============================================================
# KELOMPOKKAN BERDASARKAN STRATA
#
# Region × Chart Type × Question Type
# ============================================================

pot_strata = defaultdict(list)

nonpot_strata = defaultdict(list)


for idx in pot_indices:

    parsed = parse_id(
        str(test_data[idx]["id"])
    )

    region, chart_type, question_type = parsed

    key = (
        region,
        chart_type,
        question_type
    )

    pot_strata[key].append(idx)


for idx in nonpot_indices:

    parsed = parse_id(
        str(test_data[idx]["id"])
    )

    region, chart_type, question_type = parsed

    key = (
        region,
        chart_type,
        question_type
    )

    nonpot_strata[key].append(idx)


# ============================================================
# FUNGSI ALOKASI PROPORSIONAL
# ============================================================

def proportional_allocation(
    strata,
    target_size
):

    total_population = sum(
        len(indices)
        for indices in strata.values()
    )

    allocation = {}

    for key, indices in strata.items():

        population = len(indices)

        ideal = (
            population
            / total_population
            * target_size
        )

        allocation[key] = {
            "population": population,
            "ideal": ideal,
            "sample": math.floor(ideal),
            "remainder":
                ideal - math.floor(ideal)
        }


    # --------------------------------------------------------
    # Tambahkan sisa berdasarkan remainder terbesar
    # --------------------------------------------------------

    current_total = sum(
        x["sample"]
        for x in allocation.values()
    )

    difference = (
        target_size
        - current_total
    )

    candidates = sorted(
        allocation.keys(),
        key=lambda x:
            allocation[x]["remainder"],
        reverse=True
    )

    while difference > 0:

        changed = False

        for key in candidates:

            if difference == 0:
                break

            if (
                allocation[key]["sample"]
                <
                allocation[key]["population"]
            ):

                allocation[key]["sample"] += 1

                difference -= 1

                changed = True

        if not changed:
            break


    return allocation


# ============================================================
# ALOKASI PoT
# ============================================================

pot_allocation = proportional_allocation(
    pot_strata,
    POT_SIZE
)


# ============================================================
# ALOKASI NON-PoT
# ============================================================

nonpot_allocation = proportional_allocation(
    nonpot_strata,
    NONPOT_SIZE
)


# ============================================================
# VALIDASI ALOKASI
# ============================================================

pot_allocated = sum(
    x["sample"]
    for x in pot_allocation.values()
)

nonpot_allocated = sum(
    x["sample"]
    for x in nonpot_allocation.values()
)

print("\n" + "=" * 70)
print("VALIDASI ALOKASI")
print("=" * 70)

print(
    "PoT allocated     :",
    pot_allocated
)

print(
    "non-PoT allocated :",
    nonpot_allocated
)

print(
    "Total             :",
    pot_allocated
    + nonpot_allocated
)

assert pot_allocated == POT_SIZE

assert nonpot_allocated == NONPOT_SIZE


# ============================================================
# RANDOM SAMPLING DALAM SETIAP STRATA
# ============================================================

selected_pot = []

selected_nonpot = []

summary = []


# ------------------------------------------------------------
# PoT
# ------------------------------------------------------------

for key in sorted(pot_strata.keys()):

    region, chart_type, question_type = key

    indices = pot_strata[key]

    n_sample = pot_allocation[key]["sample"]

    selected = random.sample(
        indices,
        n_sample
    )

    selected_pot.extend(
        selected
    )


# ------------------------------------------------------------
# NON-PoT
# ------------------------------------------------------------

for key in sorted(nonpot_strata.keys()):

    region, chart_type, question_type = key

    indices = nonpot_strata[key]

    n_sample = nonpot_allocation[key]["sample"]

    selected = random.sample(
        indices,
        n_sample
    )

    selected_nonpot.extend(
        selected
    )


# ============================================================
# GABUNGKAN DAN ACAK
# ============================================================

selected_indices = (
    selected_pot
    +
    selected_nonpot
)

random.shuffle(
    selected_indices
)


# ============================================================
# AMBIL DATA
# ============================================================

sampled_dataset = test_data.select(
    selected_indices
)

df = sampled_dataset.to_pandas()


# ============================================================
# TAMBAHKAN SCORE
# ============================================================

df["score"] = (
    df["id"]
    .astype(str)
    .map(score_dict)
)


# ============================================================
# TAMBAHKAN LABEL PoT / NON-PoT
# ============================================================

df["answer_type"] = df["conversations"].apply(
    lambda conv:
        "PoT"
        if is_pot({
            "conversations": conv
        })
        else "non-PoT"
)


# ============================================================
# TAMBAHKAN INFORMASI STRATA
# ============================================================

parsed_info = (
    df["id"]
    .astype(str)
    .apply(parse_id)
)

df["region"] = parsed_info.apply(
    lambda x: x[0]
)

df["chart_type"] = parsed_info.apply(
    lambda x: x[1]
)

df["question_type"] = parsed_info.apply(
    lambda x: x[2]
)


# ============================================================
# VALIDASI FINAL
# ============================================================

print("\n" + "=" * 70)
print("VALIDASI SAMPLE")
print("=" * 70)

print(
    "Jumlah sample:",
    len(df)
)

print(
    "PoT:",
    (df["answer_type"] == "PoT").sum()
)

print(
    "non-PoT:",
    (df["answer_type"] == "non-PoT").sum()
)

print(
    "Score tersedia:",
    df["score"].notna().sum()
)

print(
    "Score missing:",
    df["score"].isna().sum()
)

print(
    "Selection:",
    (df["question_type"] == "Selection").sum()
)


assert len(df) == SAMPLE_SIZE

assert (
    (df["answer_type"] == "PoT").sum()
    == POT_SIZE
)

assert (
    (df["answer_type"] == "non-PoT").sum()
    == NONPOT_SIZE
)

assert df["score"].notna().all()


# ============================================================
# AVERAGE SCORE
# ============================================================

average_score = df["score"].mean()

print(
    f"\nAverage Score: "
    f"{average_score:.4f}"
)

print(
    f"Average Score (%): "
    f"{average_score * 100:.2f}%"
)


# ============================================================
# DISTRIBUSI PoT / NON-PoT
# ============================================================

distribution = (
    df["answer_type"]
    .value_counts()
    .rename_axis("Answer_Type")
    .reset_index(name="Count")
)

distribution["Percentage"] = (
    distribution["Count"]
    / len(df)
    * 100
)


print("\n" + "=" * 70)
print("DISTRIBUSI PoT / NON-PoT")
print("=" * 70)

display(distribution)


# ============================================================
# DISTRIBUSI STRATA FINAL
# ============================================================

final_distribution = (
    df.groupby(
        [
            "region",
            "chart_type",
            "question_type",
            "answer_type"
        ]
    )
    .size()
    .reset_index(name="Count")
)


print("\n" + "=" * 70)
print("DISTRIBUSI FINAL PER STRATA")
print("=" * 70)

display(
    final_distribution
)


# ============================================================
# SIMPAN CSV
# ============================================================

df.to_csv(
    OUTPUT_FILE,
    index=False
)


# ============================================================
# SELESAI
# ============================================================

print("\n" + "=" * 70)
print("STRATIFIED SAMPLING SELESAI")
print("=" * 70)

print(
    "Test set awal :",
    len(test_data)
)

print(
    "Eligible      :",
    len(eligible_indices)
)

print(
    "Jumlah strata PoT:",
    len(pot_strata)
)

print(
    "Jumlah strata non-PoT:",
    len(nonpot_strata)
)

print(
    "Sample        :",
    len(df)
)

print(
    "PoT sample    :",
    POT_SIZE
)

print(
    "non-PoT sample:",
    NONPOT_SIZE
)

print(
    f"Average Score : "
    f"{average_score:.4f} "
    f"({average_score * 100:.2f}%)"
)

print(
    "\nCSV   :",
    OUTPUT_FILE
)

KeyboardInterrupt:

In [2]:
import os
import tarfile
import shutil
from huggingface_hub import hf_hub_download

# ============================================================
# DOWNLOAD TINYCHART IMAGES
# ============================================================

REPO_ID = "shiinn97/indochartqa"
TAR_FILENAME = "tinychart_images.tar"

TAR_PATH = hf_hub_download(
    repo_id=REPO_ID,
    filename=TAR_FILENAME,
    repo_type="dataset"
)

print("Tar file:", TAR_PATH)


# ============================================================
# EXTRACT
# ============================================================

EXTRACT_DIR = "/kaggle/working/tinychart_images"

os.makedirs(EXTRACT_DIR, exist_ok=True)

with tarfile.open(TAR_PATH, "r") as tar:
    tar.extractall(EXTRACT_DIR)

print("Images extracted to:", EXTRACT_DIR)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

tinychart_images.tar:   0%|          | 0.00/1.01G [00:00<?, ?B/s]

Tar file: /root/.cache/huggingface/hub/datasets--shiinn97--indochartqa/snapshots/790e129b02805b66f5f2b3235554c1af3a674a95/tinychart_images.tar

/tmp/ipykernel_58/3750776119.py:31: DeprecationWarning: Python 3.14 will, by default, filter extracted tar archives and reject files or modify their metadata. Use the filter argument to control this behavior.
  tar.extractall(EXTRACT_DIR)

Images extracted to: /kaggle/working/tinychart_images

In [7]:
import os
import shutil

EXTRACT_ROOT = "/kaggle/working/tinychart_images/tinychart_images/"
OUTPUT_IMAGE_DIR = "/kaggle/working/indochartqa_test_sample_500_images"

os.makedirs(OUTPUT_IMAGE_DIR, exist_ok=True)

image_paths = []
missing_images = []

for sample in sampled_dataset:
    sid = str(sample["id"])
    relative_image_path = str(sample["image"]).replace("\\", "/")

    # Path persis berdasarkan test.json
    source_path = os.path.join(
        EXTRACT_ROOT,
        relative_image_path
    )

    if not os.path.isfile(source_path):
        missing_images.append({
            "id": sid,
            "image": relative_image_path,
            "expected_path": source_path
        })
        image_paths.append(None)
        continue

    # Pertahankan ekstensi file aslinya
    ext = os.path.splitext(source_path)[1]

    # Rename output menggunakan ID supaya mudah dipakai saat evaluasi Gemini
    destination_path = os.path.join(
        OUTPUT_IMAGE_DIR,
        f"{sid}{ext}"
    )

    shutil.copy2(source_path, destination_path)

    image_paths.append(destination_path)

df["image_path"] = image_paths

print("=" * 60)
print("Total sample      :", len(sampled_dataset))
print("Gambar ditemukan  :", len(sampled_dataset) - len(missing_images))
print("Gambar missing    :", len(missing_images))
print("=" * 60)

if missing_images:
    print("\nContoh missing:")
    for item in missing_images[:10]:
        print(item)


OUTPUT_FILE = "/kaggle/working/indochartqa_test_sample_500.csv"

df.to_csv(
    OUTPUT_FILE,
    index=False,
    encoding="utf-8-sig"
)

print("CSV:", OUTPUT_FILE)
print("Image folder:", OUTPUT_IMAGE_DIR)

NameError: name 'sampled_dataset' is not defined

In [ ]:
# GAPI_KEY =

In [110]:
!pip install openai --q

In [ ]:
import os
# os.environ["OPENAI_API_KEY"] =

In [20]:
import os
import ast
import base64
import pandas as pd
from tqdm import tqdm
from openai import OpenAI
import time
import random

# ============================================================
# PATH
# ============================================================

CSV_PATH = "/kaggle/working/indochartqa_test_sample_500.csv"
IMAGE_DIR = "/kaggle/working/indochartqa_test_sample_500_images/"

OUTPUT_PATH = "/kaggle/working/gpt4o_mini_results_500.csv"

MODEL = "gpt-4o-mini"

# ============================================================
# SETTINGS
# ============================================================

# Jeda antar-request agar tidak terlalu cepat mencapai TPM limit
REQUEST_DELAY = 3

# Jumlah maksimal percobaan jika terkena rate limit
MAX_RETRIES = 6

# Simpan hasil setiap N data
SAVE_EVERY = 10

# ============================================================
# OPENAI
# ============================================================

client = OpenAI(api_key=os.environ["OPENAI_API_KEY"])

# ============================================================
# LOAD CSV
# ============================================================

df = pd.read_csv(CSV_PATH)

print("Jumlah data:", len(df))

CONVERSATION_COLUMN = "conversations"

print("Conversation column:", CONVERSATION_COLUMN)


# ============================================================
# PARSE HUMAN DAN GPT
# ============================================================

def extract_human_question(text):
    """
    Mengambil value dari:
    {'from': 'human', 'value': '...'}

    Hasilnya hanya question, tanpa <image>.
    """

    text = str(text)

    marker_from = "'from': 'human'"
    marker_value = "'value':"

    start = text.find(marker_from)

    if start == -1:
        return None

    value_start = text.find(marker_value, start)

    if value_start == -1:
        return None

    value_start += len(marker_value)

    while value_start < len(text) and text[value_start].isspace():
        value_start += 1

    if text[value_start] == "'":
        value_start += 1

        value_end = value_start

        while value_end < len(text):
            if text[value_end] == "'" and text[value_end - 1] != "\\":
                break
            value_end += 1

        question = text[value_start:value_end]

    else:
        value_end = text.find("'}", value_start)

        if value_end == -1:
            value_end = len(text)

        question = text[value_start:value_end]

    question = question.replace("<image>", "").strip()

    return question


def extract_gpt_answer(text):
    """
    Mengambil value dari:
    {'from': 'gpt', 'value': '...'}

    Hanya digunakan untuk menyimpan ground truth.
    Tidak dikirim ke GPT-4o-mini.
    """

    text = str(text)

    marker_from = "'from': 'gpt'"
    marker_value = "'value':"

    start = text.find(marker_from)

    if start == -1:
        return None

    value_start = text.find(marker_value, start)

    if value_start == -1:
        return None

    value_start += len(marker_value)

    while value_start < len(text) and text[value_start].isspace():
        value_start += 1

    if text[value_start] == "'":
        value_start += 1

        value_end = value_start

        while value_end < len(text):
            if text[value_end] == "'" and text[value_end - 1] != "\\":
                break
            value_end += 1

        answer = text[value_start:value_end]

    else:
        value_end = text.find("'}", value_start)

        if value_end == -1:
            value_end = len(text)

        answer = text[value_start:value_end]

    return answer


# ============================================================
# IMAGE PATH
# ============================================================

def find_image(image_id):

    image_name = f"{image_id}.png"
    image_path = os.path.join(IMAGE_DIR, image_name)

    if os.path.exists(image_path):
        return image_path

    return None


# ============================================================
# IMAGE -> BASE64
# ============================================================

def image_to_data_url(image_path):

    ext = os.path.splitext(image_path)[1].lower()

    mime_types = {
        ".jpg": "image/jpeg",
        ".jpeg": "image/jpeg",
        ".png": "image/png",
    }

    if ext not in mime_types:
        raise ValueError(f"Format image tidak didukung: {ext}")

    with open(image_path, "rb") as f:
        encoded = base64.b64encode(f.read()).decode("utf-8")

    return f"data:{mime_types[ext]};base64,{encoded}"


# ============================================================
# CEK NAMA KOLOM IMAGE
# ============================================================

print("\nPreview data:")
print(df.head(1).to_string())

IMAGE_COLUMN = "id"

if IMAGE_COLUMN not in df.columns:

    print("\nWARNING:")
    print(f"Kolom '{IMAGE_COLUMN}' tidak ditemukan.")
    print("Kolom yang tersedia:", df.columns.tolist())

    raise ValueError(
        "Silakan ubah IMAGE_COLUMN sesuai nama kolom image di CSV."
    )


# ============================================================
# SYSTEM PROMPT
# ============================================================

SYSTEM_PROMPT = """
Aturan output:

1. Jika pertanyaan TIDAK mengandung instruksi
"Jawab menggunakan langkah perhitungannya.",
jawab hanya dengan jawaban akhir yang singkat dan tepat.

Jangan memberikan:
- penjelasan
- alasan
- langkah perhitungan
- narasi tambahan
- satuan

2. Jika pertanyaan MENGANDUNG instruksi
"Jawab menggunakan langkah perhitungannya.",
jawaban HARUS berupa Program of Thoughts (PoT)
dalam bentuk assignment statement Python.

Jangan memberikan narasi atau penjelasan di luar format PoT.

Untuk jawaban PoT:

- Gunakan informasi pada gambar grafik untuk menentukan nilai
  yang diperlukan dalam perhitungan.
- Gunakan komentar satu baris sebelum setiap assignment statement.
- Setiap komentar dibungkus dengan tag <comment>#...</comment>.
- Setiap assignment statement dibungkus dengan tag <step>...</step>.
- Komentar harus bersifat generik dan deskriptif secara logika.
- Output akhir harus disimpan dalam variabel Answer.
- Jangan menggunakan Markdown code fence.
- Jangan memberikan narasi di luar format PoT.

Hanya boleh menggunakan operator dan fungsi berikut:

['len', 'all', 'any', 'index', 'np.sort', 'np.abs',
'np.add', 'np.argmax', 'np.argmin', 'np.diff', 'np.divide',
'np.greater', 'np.greater_equal', 'np.less', 'np.max',
'np.mean', 'np.median', 'np.min', 'np.subtract', 'np.sum',
'np.count_nonzero', 'np.where', '+', '-', '*', '/', '>',
'<', '=']
"""


# ============================================================
# FUNCTION: REQUEST GPT
# ============================================================

def request_gpt(question, image_data_url):

    for attempt in range(MAX_RETRIES):

        try:

            response = client.chat.completions.create(
                model=MODEL,
                messages=[
                    {
                        "role": "system",
                        "content": SYSTEM_PROMPT
                    },
                    {
                        "role": "user",
                        "content": [
                            {
                                "type": "text",
                                "text": question
                            },
                            {
                                "type": "image_url",
                                "image_url": {
                                    "url": image_data_url
                                }
                            }
                        ]
                    }
                ],
                temperature=0,
                max_tokens=500
            )

            return response.choices[0].message.content.strip(), None

        except Exception as e:

            error_message = str(e)

            # -----------------------------------------------
            # RATE LIMIT
            # -----------------------------------------------

            if "429" in error_message:

                # Exponential backoff:
                # 5 -> 10 -> 20 -> 40 -> 60 -> 60 detik
                wait_time = min(
                    60,
                    5 * (2 ** attempt)
                )

                # Tambahkan sedikit random delay
                wait_time += random.uniform(0, 2)

                print(
                    f"\n[429] Rate limit. "
                    f"Percobaan {attempt + 1}/{MAX_RETRIES}. "
                    f"Tunggu {wait_time:.1f} detik..."
                )

                time.sleep(wait_time)

            else:

                return None, error_message

    return None, "rate_limit_after_retries"


# ============================================================
# RUN GPT-4o-mini
# ============================================================

results = []

for idx, row in tqdm(
    df.iterrows(),
    total=len(df),
    desc="Running GPT-4o-mini"
):

    conversation = row[CONVERSATION_COLUMN]

    # --------------------------------------------------------
    # QUESTION
    # --------------------------------------------------------

    question = extract_human_question(conversation)

    # --------------------------------------------------------
    # GROUND TRUTH
    # --------------------------------------------------------

    ground_truth = extract_gpt_answer(conversation)

    # --------------------------------------------------------
    # IMAGE
    # --------------------------------------------------------

    image_id = str(row[IMAGE_COLUMN])

    image_path = find_image(image_id)

    # --------------------------------------------------------
    # QUESTION TIDAK DITEMUKAN
    # --------------------------------------------------------

    if question is None:

        results.append({
            "index": idx,
            "image": image_id,
            "question": None,
            "ground_truth": ground_truth,
            "gpt4o_mini_answer": None,
            "error": "question_not_found"
        })

        continue

    # --------------------------------------------------------
    # IMAGE TIDAK DITEMUKAN
    # --------------------------------------------------------

    if image_path is None:

        results.append({
            "index": idx,
            "image": image_id,
            "question": question,
            "ground_truth": ground_truth,
            "gpt4o_mini_answer": None,
            "error": "image_not_found"
        })

        continue

    # --------------------------------------------------------
    # IMAGE -> DATA URL
    # --------------------------------------------------------

    try:

        image_data_url = image_to_data_url(image_path)

    except Exception as e:

        results.append({
            "index": idx,
            "image": image_id,
            "question": question,
            "ground_truth": ground_truth,
            "gpt4o_mini_answer": None,
            "error": str(e)
        })

        continue

    # --------------------------------------------------------
    # DELAY ANTAR REQUEST
    # --------------------------------------------------------

    time.sleep(REQUEST_DELAY)

    # --------------------------------------------------------
    # REQUEST GPT
    # --------------------------------------------------------

    answer, error = request_gpt(
        question,
        image_data_url
    )

    results.append({
        "index": idx,
        "image": image_id,
        "question": question,
        "ground_truth": ground_truth,
        "gpt4o_mini_answer": answer,
        "error": error
    })

    # --------------------------------------------------------
    # AUTO SAVE
    # --------------------------------------------------------

    if len(results) % SAVE_EVERY == 0:

        temp_df = pd.DataFrame(results)

        temp_df.to_csv(
            OUTPUT_PATH,
            index=False,
            encoding="utf-8-sig"
        )


# ============================================================
# FINAL SAVE
# ============================================================

result_df = pd.DataFrame(results)

result_df.to_csv(
    OUTPUT_PATH,
    index=False,
    encoding="utf-8-sig"
)


# ============================================================
# SUMMARY
# ============================================================

print("\n========================================")
print("SELESAI")
print("========================================")

print("Output :", OUTPUT_PATH)
print("Total  :", len(result_df))

print(
    "Berhasil:",
    result_df["gpt4o_mini_answer"].notna().sum()
)

print(
    "Gagal:",
    result_df["gpt4o_mini_answer"].isna().sum()
)

Jumlah data: 500
Conversation column: conversations

Preview data:
                   id                                                                                                      image                                                                                                                                                          conversations  score answer_type region chart_type question_type                                                                 image_path
0  S223BARSelection_3  Sulsel/WM_BAR/Jumlah Barang Angkutan Laut di Pelabuhan Makassar bulan Juni, 2025/3D_Horizontal_Style1.png  [{'from': 'human', 'value': '<image>\nBerapa jumlah barang angkutan jenis Bongkar di Pelabuhan Makassar pada bulan Juni 2025?'}\n {'from': 'gpt', 'value': '547907'}]    0.0     non-PoT      S        BAR     Selection  /kaggle/working/indochartqa_test_sample_500_images/S223BARSelection_3.png

Running GPT-4o-mini:   2%|▏         | 9/500 [00:42<38:51,  4.75s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 5.9 detik...

Running GPT-4o-mini:   2%|▏         | 11/500 [00:59<52:47,  6.48s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 5.6 detik...

Running GPT-4o-mini:   2%|▏         | 12/500 [01:10<1:04:44,  7.96s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 5.8 detik...

Running GPT-4o-mini:   3%|▎         | 14/500 [01:25<59:30,  7.35s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 5.5 detik...

Running GPT-4o-mini:   4%|▎         | 18/500 [01:50<47:43,  5.94s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 6.1 detik...

[429] Rate limit. Percobaan 2/6. Tunggu 10.9 detik...

Running GPT-4o-mini:   4%|▍         | 21/500 [02:25<1:03:48,  7.99s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 6.2 detik...

Running GPT-4o-mini:   5%|▍         | 23/500 [02:41<1:01:20,  7.72s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 6.8 detik...

Running GPT-4o-mini:   5%|▍         | 24/500 [02:54<1:13:50,  9.31s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 6.5 detik...

Running GPT-4o-mini:   5%|▌         | 26/500 [03:10<1:06:21,  8.40s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 6.2 detik...

Running GPT-4o-mini:   6%|▌         | 28/500 [03:26<1:02:12,  7.91s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 5.1 detik...

Running GPT-4o-mini:   6%|▌         | 29/500 [03:37<1:08:59,  8.79s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 5.5 detik...

[429] Rate limit. Percobaan 2/6. Tunggu 11.3 detik...

Running GPT-4o-mini:   6%|▌         | 30/500 [04:01<1:44:30, 13.34s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 6.7 detik...

Running GPT-4o-mini:   6%|▋         | 32/500 [04:19<1:23:19, 10.68s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 6.2 detik...

Running GPT-4o-mini:   7%|▋         | 33/500 [04:31<1:25:52, 11.03s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 5.0 detik...

Running GPT-4o-mini:   7%|▋         | 35/500 [04:46<1:09:16,  8.94s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 6.5 detik...

Running GPT-4o-mini:   7%|▋         | 36/500 [04:59<1:20:03, 10.35s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 6.6 detik...

Running GPT-4o-mini:   8%|▊         | 39/500 [05:21<1:00:54,  7.93s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 6.2 detik...

Running GPT-4o-mini:   8%|▊         | 40/500 [05:33<1:08:58,  9.00s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 6.5 detik...

[429] Rate limit. Percobaan 2/6. Tunggu 10.4 detik...

[429] Rate limit. Percobaan 3/6. Tunggu 21.0 detik...

Running GPT-4o-mini:   9%|▉         | 46/500 [06:41<53:47,  7.11s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 5.9 detik...

Running GPT-4o-mini:  10%|▉         | 49/500 [07:01<47:21,  6.30s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 5.6 detik...

[429] Rate limit. Percobaan 2/6. Tunggu 12.0 detik...

Running GPT-4o-mini:  10%|█         | 52/500 [07:34<59:31,  7.97s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 5.9 detik...

Running GPT-4o-mini:  11%|█         | 53/500 [07:45<1:06:55,  8.98s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 6.6 detik...

Running GPT-4o-mini:  11%|█         | 54/500 [07:57<1:12:31,  9.76s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 6.9 detik...

Running GPT-4o-mini:  11%|█▏        | 57/500 [08:18<54:26,  7.37s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 5.9 detik...

Running GPT-4o-mini:  12%|█▏        | 58/500 [08:29<1:02:45,  8.52s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 5.8 detik...

Running GPT-4o-mini:  12%|█▏        | 59/500 [08:41<1:10:16,  9.56s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 5.6 detik...

Running GPT-4o-mini:  12%|█▏        | 60/500 [08:52<1:12:39,  9.91s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 5.2 detik...

Running GPT-4o-mini:  12%|█▏        | 61/500 [09:03<1:13:53, 10.10s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 5.3 detik...

Running GPT-4o-mini:  12%|█▏        | 62/500 [09:15<1:18:20, 10.73s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 5.8 detik...

[429] Rate limit. Percobaan 2/6. Tunggu 11.0 detik...

Running GPT-4o-mini:  13%|█▎        | 65/500 [09:50<1:12:10,  9.96s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 6.3 detik...

[429] Rate limit. Percobaan 2/6. Tunggu 10.8 detik...

Running GPT-4o-mini:  13%|█▎        | 67/500 [10:17<1:19:43, 11.05s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 6.5 detik...

Running GPT-4o-mini:  14%|█▎        | 68/500 [10:29<1:21:04, 11.26s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 5.1 detik...

Running GPT-4o-mini:  14%|█▍        | 69/500 [10:39<1:19:25, 11.06s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 5.2 detik...

Running GPT-4o-mini:  14%|█▍        | 71/500 [10:55<1:04:33,  9.03s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 5.5 detik...

Running GPT-4o-mini:  14%|█▍        | 72/500 [11:06<1:08:10,  9.56s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 5.2 detik...

Running GPT-4o-mini:  15%|█▍        | 74/500 [11:21<58:38,  8.26s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 6.5 detik...

[429] Rate limit. Percobaan 2/6. Tunggu 11.7 detik...

Running GPT-4o-mini:  16%|█▌        | 78/500 [12:01<53:30,  7.61s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 6.6 detik...

Running GPT-4o-mini:  16%|█▌        | 79/500 [12:13<1:02:42,  8.94s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 5.0 detik...

[429] Rate limit. Percobaan 2/6. Tunggu 11.7 detik...

Running GPT-4o-mini:  17%|█▋        | 84/500 [12:54<46:07,  6.65s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 5.9 detik...

Running GPT-4o-mini:  17%|█▋        | 85/500 [13:07<59:39,  8.63s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 5.1 detik...

Running GPT-4o-mini:  18%|█▊        | 88/500 [13:28<48:30,  7.06s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 6.0 detik...

Running GPT-4o-mini:  18%|█▊        | 89/500 [13:40<58:21,  8.52s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 6.2 detik...

Running GPT-4o-mini:  18%|█▊        | 90/500 [13:51<1:04:19,  9.41s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 6.0 detik...

Running GPT-4o-mini:  19%|█▊        | 93/500 [14:12<48:57,  7.22s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 5.9 detik...

Running GPT-4o-mini:  19%|█▉        | 94/500 [14:23<57:07,  8.44s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 5.1 detik...

Running GPT-4o-mini:  19%|█▉        | 95/500 [14:33<1:00:13,  8.92s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 5.5 detik...

Running GPT-4o-mini:  19%|█▉        | 96/500 [14:44<1:03:52,  9.49s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 5.3 detik...

Running GPT-4o-mini:  19%|█▉        | 97/500 [14:55<1:07:51, 10.10s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 5.6 detik...

[429] Rate limit. Percobaan 2/6. Tunggu 11.8 detik...

Running GPT-4o-mini:  20%|█▉        | 99/500 [15:26<1:20:48, 12.09s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 6.0 detik...

Running GPT-4o-mini:  20%|██        | 101/500 [15:42<1:04:23,  9.68s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 5.1 detik...

Running GPT-4o-mini:  21%|██        | 104/500 [16:04<49:48,  7.55s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 6.3 detik...

Running GPT-4o-mini:  21%|██        | 105/500 [16:16<57:23,  8.72s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 6.6 detik...

Running GPT-4o-mini:  21%|██        | 106/500 [16:30<1:08:10, 10.38s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 6.4 detik...

Running GPT-4o-mini:  21%|██▏       | 107/500 [16:42<1:10:43, 10.80s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 5.6 detik...

Running GPT-4o-mini:  22%|██▏       | 108/500 [16:53<1:11:27, 10.94s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 5.0 detik...

Running GPT-4o-mini:  22%|██▏       | 109/500 [17:03<1:09:31, 10.67s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 5.8 detik...

Running GPT-4o-mini:  22%|██▏       | 112/500 [17:25<52:14,  8.08s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 5.4 detik...

Running GPT-4o-mini:  23%|██▎       | 113/500 [17:37<59:10,  9.17s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 6.7 detik...

Running GPT-4o-mini:  23%|██▎       | 116/500 [17:59<47:23,  7.41s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 5.2 detik...

Running GPT-4o-mini:  23%|██▎       | 117/500 [18:09<52:33,  8.23s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 6.9 detik...

[429] Rate limit. Percobaan 2/6. Tunggu 11.3 detik...

[429] Rate limit. Percobaan 3/6. Tunggu 20.3 detik...

[429] Rate limit. Percobaan 4/6. Tunggu 41.9 detik...

Running GPT-4o-mini:  26%|██▌       | 128/500 [20:24<34:57,  5.64s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 5.6 detik...

Running GPT-4o-mini:  26%|██▌       | 129/500 [20:38<49:06,  7.94s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 6.4 detik...

[429] Rate limit. Percobaan 2/6. Tunggu 10.8 detik...

Running GPT-4o-mini:  26%|██▌       | 131/500 [21:06<1:02:07, 10.10s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 6.0 detik...

Running GPT-4o-mini:  26%|██▋       | 132/500 [21:18<1:06:34, 10.86s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 5.9 detik...

Running GPT-4o-mini:  28%|██▊       | 139/500 [21:58<32:34,  5.41s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 5.9 detik...

Running GPT-4o-mini:  28%|██▊       | 140/500 [22:09<42:18,  7.05s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 5.3 detik...

Running GPT-4o-mini:  28%|██▊       | 141/500 [22:19<47:48,  7.99s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 5.4 detik...

Running GPT-4o-mini:  29%|██▉       | 144/500 [22:38<38:38,  6.51s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 6.2 detik...

Running GPT-4o-mini:  29%|██▉       | 145/500 [22:50<46:56,  7.93s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 6.5 detik...

Running GPT-4o-mini:  29%|██▉       | 146/500 [23:02<54:14,  9.19s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 5.3 detik...

Running GPT-4o-mini:  29%|██▉       | 147/500 [23:13<57:24,  9.76s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 5.1 detik...

Running GPT-4o-mini:  30%|██▉       | 149/500 [23:31<52:13,  8.93s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 6.5 detik...

[429] Rate limit. Percobaan 2/6. Tunggu 11.7 detik...

Running GPT-4o-mini:  30%|███       | 152/500 [24:06<53:40,  9.26s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 5.7 detik...

[429] Rate limit. Percobaan 2/6. Tunggu 11.6 detik...

Running GPT-4o-mini:  32%|███▏      | 158/500 [24:53<35:34,  6.24s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 5.5 detik...

Running GPT-4o-mini:  32%|███▏      | 159/500 [25:06<46:07,  8.12s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 5.0 detik...

[429] Rate limit. Percobaan 2/6. Tunggu 11.5 detik...

Running GPT-4o-mini:  32%|███▏      | 162/500 [25:41<50:58,  9.05s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 6.7 detik...

[429] Rate limit. Percobaan 2/6. Tunggu 11.2 detik...

Running GPT-4o-mini:  33%|███▎      | 164/500 [26:10<1:01:27, 10.97s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 6.3 detik...

Running GPT-4o-mini:  33%|███▎      | 165/500 [26:22<1:03:12, 11.32s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 6.7 detik...

[429] Rate limit. Percobaan 2/6. Tunggu 10.9 detik...

Running GPT-4o-mini:  34%|███▍      | 170/500 [27:08<42:13,  7.68s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 6.0 detik...

[429] Rate limit. Percobaan 2/6. Tunggu 10.7 detik...

Running GPT-4o-mini:  34%|███▍      | 172/500 [27:36<54:48, 10.03s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 6.5 detik...

Running GPT-4o-mini:  35%|███▍      | 173/500 [27:51<1:03:34, 11.67s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 5.8 detik...

Running GPT-4o-mini:  36%|███▌      | 179/500 [28:26<31:04,  5.81s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 6.9 detik...

Running GPT-4o-mini:  36%|███▌      | 181/500 [28:42<35:49,  6.74s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 6.7 detik...

[429] Rate limit. Percobaan 2/6. Tunggu 12.0 detik...

Running GPT-4o-mini:  37%|███▋      | 185/500 [29:21<38:41,  7.37s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 5.5 detik...

Running GPT-4o-mini:  37%|███▋      | 187/500 [29:39<40:09,  7.70s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 5.8 detik...

Running GPT-4o-mini:  38%|███▊      | 189/500 [29:55<38:33,  7.44s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 6.7 detik...

Running GPT-4o-mini:  38%|███▊      | 191/500 [30:11<38:51,  7.55s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 5.8 detik...

[429] Rate limit. Percobaan 2/6. Tunggu 10.6 detik...

Running GPT-4o-mini:  38%|███▊      | 192/500 [30:35<1:03:18, 12.33s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 5.9 detik...

Running GPT-4o-mini:  39%|███▉      | 194/500 [30:50<49:25,  9.69s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 6.8 detik...

[429] Rate limit. Percobaan 2/6. Tunggu 10.8 detik...

Running GPT-4o-mini:  39%|███▉      | 196/500 [31:19<56:26, 11.14s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 7.0 detik...

Running GPT-4o-mini:  40%|███▉      | 198/500 [31:37<49:04,  9.75s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 6.6 detik...

Running GPT-4o-mini:  41%|████      | 205/500 [32:16<25:23,  5.16s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 6.3 detik...

Running GPT-4o-mini:  41%|████      | 206/500 [32:28<35:04,  7.16s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 5.3 detik...

[429] Rate limit. Percobaan 2/6. Tunggu 11.9 detik...

Running GPT-4o-mini:  42%|████▏     | 209/500 [33:02<40:22,  8.32s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 5.3 detik...

Running GPT-4o-mini:  43%|████▎     | 214/500 [33:31<28:12,  5.92s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 6.9 detik...

[429] Rate limit. Percobaan 2/6. Tunggu 10.7 detik...

[429] Rate limit. Percobaan 3/6. Tunggu 20.2 detik...

[429] Rate limit. Percobaan 4/6. Tunggu 41.7 detik...

Running GPT-4o-mini:  45%|████▌     | 226/500 [35:54<23:38,  5.18s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 5.2 detik...

Running GPT-4o-mini:  46%|████▌     | 228/500 [36:11<29:32,  6.52s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 6.8 detik...

[429] Rate limit. Percobaan 2/6. Tunggu 10.0 detik...

Running GPT-4o-mini:  46%|████▌     | 230/500 [36:38<41:38,  9.25s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 5.3 detik...

Running GPT-4o-mini:  46%|████▌     | 231/500 [36:48<42:39,  9.52s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 6.7 detik...

Running GPT-4o-mini:  46%|████▋     | 232/500 [37:00<45:56, 10.29s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 6.9 detik...

Running GPT-4o-mini:  47%|████▋     | 234/500 [37:16<38:56,  8.79s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 5.1 detik...

[429] Rate limit. Percobaan 2/6. Tunggu 11.6 detik...

Running GPT-4o-mini:  47%|████▋     | 236/500 [37:44<46:58, 10.68s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 5.5 detik...

Running GPT-4o-mini:  47%|████▋     | 237/500 [37:55<46:58, 10.72s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 6.2 detik...

[429] Rate limit. Percobaan 2/6. Tunggu 10.8 detik...

Running GPT-4o-mini:  48%|████▊     | 239/500 [38:22<49:15, 11.32s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 5.2 detik...

Running GPT-4o-mini:  49%|████▊     | 243/500 [38:49<31:22,  7.33s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 5.7 detik...

Running GPT-4o-mini:  49%|████▉     | 244/500 [39:00<36:37,  8.58s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 6.3 detik...

Running GPT-4o-mini:  49%|████▉     | 245/500 [39:12<39:49,  9.37s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 6.1 detik...

[429] Rate limit. Percobaan 2/6. Tunggu 11.9 detik...

Running GPT-4o-mini:  49%|████▉     | 246/500 [39:38<1:00:58, 14.40s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 6.3 detik...

Running GPT-4o-mini:  50%|█████     | 252/500 [40:14<25:50,  6.25s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 6.8 detik...

Running GPT-4o-mini:  51%|█████     | 255/500 [40:37<27:01,  6.62s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 6.0 detik...

Running GPT-4o-mini:  52%|█████▏    | 258/500 [40:59<26:49,  6.65s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 6.1 detik...

[429] Rate limit. Percobaan 2/6. Tunggu 11.2 detik...

Running GPT-4o-mini:  53%|█████▎    | 263/500 [41:43<25:14,  6.39s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 5.5 detik...

[429] Rate limit. Percobaan 2/6. Tunggu 11.4 detik...

[429] Rate limit. Percobaan 3/6. Tunggu 20.6 detik...

Running GPT-4o-mini:  53%|█████▎    | 266/500 [42:39<44:48, 11.49s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 5.5 detik...

Running GPT-4o-mini:  54%|█████▍    | 270/500 [43:05<27:08,  7.08s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 5.2 detik...

Running GPT-4o-mini:  55%|█████▍    | 273/500 [43:28<27:21,  7.23s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 7.0 detik...

Running GPT-4o-mini:  55%|█████▌    | 275/500 [43:45<27:55,  7.45s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 6.5 detik...

[429] Rate limit. Percobaan 2/6. Tunggu 11.4 detik...

Running GPT-4o-mini:  56%|█████▌    | 278/500 [44:20<32:26,  8.77s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 5.2 detik...

[429] Rate limit. Percobaan 2/6. Tunggu 10.3 detik...

Running GPT-4o-mini:  56%|█████▌    | 280/500 [44:48<39:02, 10.65s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 5.6 detik...

[429] Rate limit. Percobaan 2/6. Tunggu 10.1 detik...

Running GPT-4o-mini:  56%|█████▌    | 281/500 [45:10<51:48, 14.20s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 5.6 detik...

Running GPT-4o-mini:  57%|█████▋    | 285/500 [45:35<26:52,  7.50s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 5.1 detik...

[429] Rate limit. Percobaan 2/6. Tunggu 10.7 detik...

Running GPT-4o-mini:  58%|█████▊    | 288/500 [46:06<28:05,  7.95s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 5.9 detik...

Running GPT-4o-mini:  58%|█████▊    | 291/500 [46:26<23:14,  6.67s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 5.5 detik...

[429] Rate limit. Percobaan 2/6. Tunggu 10.8 detik...

[429] Rate limit. Percobaan 3/6. Tunggu 21.4 detik...

Running GPT-4o-mini:  59%|█████▉    | 294/500 [47:25<43:04, 12.55s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 5.4 detik...

Running GPT-4o-mini:  60%|██████    | 301/500 [48:05<19:04,  5.75s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 5.4 detik...

Running GPT-4o-mini:  61%|██████    | 303/500 [48:23<22:49,  6.95s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 6.2 detik...

[429] Rate limit. Percobaan 2/6. Tunggu 10.8 detik...

[429] Rate limit. Percobaan 3/6. Tunggu 21.4 detik...

Running GPT-4o-mini:  62%|██████▏   | 311/500 [49:42<18:22,  5.83s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 6.0 detik...

[429] Rate limit. Percobaan 2/6. Tunggu 11.2 detik...

[429] Rate limit. Percobaan 3/6. Tunggu 20.5 detik...

Running GPT-4o-mini:  63%|██████▎   | 314/500 [50:36<33:56, 10.95s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 6.3 detik...

Running GPT-4o-mini:  64%|██████▍   | 320/500 [51:12<17:27,  5.82s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 5.9 detik...

[429] Rate limit. Percobaan 2/6. Tunggu 11.3 detik...

Running GPT-4o-mini:  65%|██████▌   | 325/500 [51:55<18:39,  6.40s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 6.8 detik...

[429] Rate limit. Percobaan 2/6. Tunggu 10.9 detik...

Running GPT-4o-mini:  65%|██████▌   | 327/500 [52:23<27:31,  9.54s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 5.6 detik...

Running GPT-4o-mini:  66%|██████▌   | 329/500 [52:39<24:01,  8.43s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 6.1 detik...

Running GPT-4o-mini:  66%|██████▋   | 332/500 [53:00<19:46,  7.06s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 5.1 detik...

Running GPT-4o-mini:  67%|██████▋   | 334/500 [53:17<20:01,  7.24s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 6.9 detik...

[429] Rate limit. Percobaan 2/6. Tunggu 12.0 detik...

[429] Rate limit. Percobaan 3/6. Tunggu 20.6 detik...

Running GPT-4o-mini:  67%|██████▋   | 337/500 [54:12<31:10, 11.47s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 6.9 detik...

Running GPT-4o-mini:  68%|██████▊   | 341/500 [54:40<19:51,  7.49s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 6.4 detik...

Running GPT-4o-mini:  68%|██████▊   | 342/500 [54:54<25:05,  9.53s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 5.9 detik...

Running GPT-4o-mini:  69%|██████▉   | 344/500 [55:10<22:05,  8.49s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 5.6 detik...

Running GPT-4o-mini:  70%|██████▉   | 348/500 [55:37<16:15,  6.41s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 7.0 detik...

Running GPT-4o-mini:  70%|██████▉   | 349/500 [55:50<21:15,  8.45s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 6.7 detik...

Running GPT-4o-mini:  70%|███████   | 351/500 [56:07<20:09,  8.12s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 5.2 detik...

Running GPT-4o-mini:  70%|███████   | 352/500 [56:18<21:46,  8.82s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 5.8 detik...

Running GPT-4o-mini:  71%|███████   | 353/500 [56:29<22:57,  9.37s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 5.7 detik...

Running GPT-4o-mini:  71%|███████   | 354/500 [56:40<24:19,  9.99s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 5.6 detik...

[429] Rate limit. Percobaan 2/6. Tunggu 11.4 detik...

Running GPT-4o-mini:  72%|███████▏  | 359/500 [57:22<15:54,  6.77s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 5.0 detik...

Running GPT-4o-mini:  72%|███████▏  | 360/500 [57:33<18:32,  7.95s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 6.7 detik...

[429] Rate limit. Percobaan 2/6. Tunggu 10.8 detik...

Running GPT-4o-mini:  73%|███████▎  | 364/500 [58:10<16:31,  7.29s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 5.0 detik...

[429] Rate limit. Percobaan 2/6. Tunggu 11.7 detik...

Running GPT-4o-mini:  73%|███████▎  | 366/500 [58:39<22:42, 10.17s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 6.6 detik...

Running GPT-4o-mini:  74%|███████▎  | 368/500 [58:56<19:27,  8.85s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 6.9 detik...

[429] Rate limit. Percobaan 2/6. Tunggu 11.8 detik...

Running GPT-4o-mini:  75%|███████▍  | 374/500 [59:43<12:30,  5.96s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 6.5 detik...

Running GPT-4o-mini:  75%|███████▌  | 375/500 [59:55<16:25,  7.88s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 6.7 detik...

Running GPT-4o-mini:  75%|███████▌  | 376/500 [1:00:08<19:33,  9.46s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 6.8 detik...

Running GPT-4o-mini:  75%|███████▌  | 377/500 [1:00:20<20:59, 10.24s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 6.6 detik...

[429] Rate limit. Percobaan 2/6. Tunggu 10.5 detik...

Running GPT-4o-mini:  76%|███████▌  | 380/500 [1:00:53<18:37,  9.31s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 6.6 detik...

Running GPT-4o-mini:  77%|███████▋  | 383/500 [1:01:16<15:08,  7.77s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 5.4 detik...

[429] Rate limit. Percobaan 2/6. Tunggu 10.4 detik...

Running GPT-4o-mini:  78%|███████▊  | 388/500 [1:01:57<11:47,  6.32s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 5.5 detik...

Running GPT-4o-mini:  79%|███████▊  | 393/500 [1:02:33<11:06,  6.22s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 6.5 detik...

Running GPT-4o-mini:  79%|███████▉  | 395/500 [1:02:50<12:43,  7.27s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 6.5 detik...

[429] Rate limit. Percobaan 2/6. Tunggu 11.4 detik...

Running GPT-4o-mini:  79%|███████▉  | 397/500 [1:03:19<17:05,  9.95s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 5.3 detik...

Running GPT-4o-mini:  80%|███████▉  | 398/500 [1:03:30<17:16, 10.16s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 5.2 detik...

Running GPT-4o-mini:  80%|████████  | 400/500 [1:03:47<15:13,  9.14s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 6.3 detik...

[429] Rate limit. Percobaan 2/6. Tunggu 10.1 detik...

[429] Rate limit. Percobaan 3/6. Tunggu 21.6 detik...

Running GPT-4o-mini:  80%|████████  | 401/500 [1:04:32<33:01, 20.02s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 5.1 detik...

Running GPT-4o-mini:  81%|████████  | 406/500 [1:05:02<12:20,  7.88s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 5.7 detik...

Running GPT-4o-mini:  82%|████████▏ | 410/500 [1:05:28<09:31,  6.35s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 5.3 detik...

Running GPT-4o-mini:  82%|████████▏ | 411/500 [1:05:38<11:13,  7.56s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 6.8 detik...

[429] Rate limit. Percobaan 2/6. Tunggu 10.7 detik...

Running GPT-4o-mini:  83%|████████▎ | 414/500 [1:06:14<12:44,  8.89s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 5.8 detik...

Running GPT-4o-mini:  83%|████████▎ | 416/500 [1:06:33<12:27,  8.89s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 5.4 detik...

Running GPT-4o-mini:  83%|████████▎ | 417/500 [1:06:45<13:38,  9.86s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 6.6 detik...

Running GPT-4o-mini:  84%|████████▎ | 418/500 [1:06:57<14:15, 10.44s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 6.8 detik...

Running GPT-4o-mini:  84%|████████▍ | 419/500 [1:07:09<14:43, 10.90s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 5.7 detik...

[429] Rate limit. Percobaan 2/6. Tunggu 11.0 detik...

[429] Rate limit. Percobaan 3/6. Tunggu 20.5 detik...

Running GPT-4o-mini:  85%|████████▍ | 424/500 [1:08:11<10:47,  8.52s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 5.3 detik...

Running GPT-4o-mini:  86%|████████▌ | 429/500 [1:08:41<06:51,  5.79s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 6.8 detik...

Running GPT-4o-mini:  86%|████████▋ | 432/500 [1:09:03<07:02,  6.21s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 6.9 detik...

Running GPT-4o-mini:  87%|████████▋ | 434/500 [1:09:24<08:36,  7.83s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 6.9 detik...

Running GPT-4o-mini:  87%|████████▋ | 437/500 [1:09:51<07:54,  7.53s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 5.6 detik...

Running GPT-4o-mini:  88%|████████▊ | 441/500 [1:10:16<05:53,  5.99s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 6.7 detik...

Running GPT-4o-mini:  89%|████████▊ | 443/500 [1:10:34<06:51,  7.22s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 6.6 detik...

[429] Rate limit. Percobaan 2/6. Tunggu 10.9 detik...

[429] Rate limit. Percobaan 3/6. Tunggu 20.2 detik...

Running GPT-4o-mini:  89%|████████▉ | 446/500 [1:11:27<10:02, 11.16s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 6.5 detik...

Running GPT-4o-mini:  90%|█████████ | 451/500 [1:11:58<05:03,  6.20s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 5.5 detik...

Running GPT-4o-mini:  90%|█████████ | 452/500 [1:12:10<06:13,  7.77s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 6.4 detik...

Running GPT-4o-mini:  91%|█████████ | 454/500 [1:12:27<06:07,  8.00s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 6.3 detik...

[429] Rate limit. Percobaan 2/6. Tunggu 10.8 detik...

Running GPT-4o-mini:  91%|█████████ | 455/500 [1:12:53<09:54, 13.21s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 6.7 detik...

[429] Rate limit. Percobaan 2/6. Tunggu 11.1 detik...

Running GPT-4o-mini:  93%|█████████▎| 463/500 [1:13:50<03:36,  5.84s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 5.2 detik...

Running GPT-4o-mini:  93%|█████████▎| 464/500 [1:14:01<04:27,  7.44s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 5.8 detik...

Running GPT-4o-mini:  93%|█████████▎| 465/500 [1:14:12<04:59,  8.57s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 5.5 detik...

Running GPT-4o-mini:  94%|█████████▎| 468/500 [1:14:33<03:46,  7.07s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 5.2 detik...

Running GPT-4o-mini:  94%|█████████▍| 469/500 [1:14:46<04:32,  8.80s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 5.7 detik...

[429] Rate limit. Percobaan 2/6. Tunggu 11.5 detik...

Running GPT-4o-mini:  94%|█████████▍| 470/500 [1:15:10<06:43, 13.43s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 5.5 detik...

[429] Rate limit. Percobaan 2/6. Tunggu 10.8 detik...

Running GPT-4o-mini:  94%|█████████▍| 471/500 [1:15:32<07:50, 16.21s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 6.3 detik...

Running GPT-4o-mini:  94%|█████████▍| 472/500 [1:15:44<06:54, 14.80s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 5.7 detik...

Running GPT-4o-mini:  95%|█████████▍| 474/500 [1:16:01<04:51, 11.22s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 6.3 detik...

Running GPT-4o-mini:  95%|█████████▌| 476/500 [1:16:17<03:40,  9.20s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 5.9 detik...

[429] Rate limit. Percobaan 2/6. Tunggu 11.2 detik...

Running GPT-4o-mini:  96%|█████████▌| 480/500 [1:16:53<02:30,  7.52s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 6.9 detik...

Running GPT-4o-mini:  96%|█████████▋| 482/500 [1:17:11<02:26,  8.14s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 5.7 detik...

[429] Rate limit. Percobaan 2/6. Tunggu 11.2 detik...

Running GPT-4o-mini:  97%|█████████▋| 485/500 [1:17:44<02:10,  8.72s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 6.3 detik...

Running GPT-4o-mini:  97%|█████████▋| 487/500 [1:18:01<01:45,  8.10s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 6.3 detik...

Running GPT-4o-mini:  98%|█████████▊| 491/500 [1:18:26<00:56,  6.29s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 5.9 detik...

Running GPT-4o-mini:  99%|█████████▊| 493/500 [1:18:43<00:48,  6.98s/it]

[429] Rate limit. Percobaan 1/6. Tunggu 6.4 detik...

[429] Rate limit. Percobaan 2/6. Tunggu 11.3 detik...

[429] Rate limit. Percobaan 3/6. Tunggu 20.2 detik...

[429] Rate limit. Percobaan 4/6. Tunggu 40.1 detik...

Running GPT-4o-mini: 100%|██████████| 500/500 [1:20:36<00:00,  9.67s/it]

========================================
SELESAI
========================================
Output : /kaggle/working/gpt4o_mini_results_500.csv
Total  : 500
Berhasil: 500
Gagal: 0

In [15]:
import json
import re
import os
from datasets import load_dataset
from pathlib import Path
from collections import defaultdict
from difflib import SequenceMatcher
from openpyxl import load_workbook
from openpyxl.drawing.image import Image as XLImage
from openpyxl.utils import get_column_letter
from PIL import Image
import tempfile
import pandas as pd
import numpy as np


# ============================================================
# PATH
# ============================================================

CSV_PATH = "/kaggle/input/datasets/dianshinta09/mygptresult/gpt4o_mini_results_500.csv"

# Folder JSONL TinyChart evaluation
JSONL_DIR = "/kaggle/input/datasets/dianshinta09/evaluation-result-tinycart/eval"
OUTPUT_PATH = "/kaggle/working/evaluation_gpt4o_mini_500.xlsx"
HF_DATASET = "shiinn97/indochartqa"
HF_SPLIT = "test"

IMAGE_ROOT = "/kaggle/working/tinychart_images/tinychart_images/"

# ============================================================
# KONFIGURASI
# ============================================================

POT_SUFFIX = "Jawab menggunakan langkah perhitungannya"


# ============================================================
# 1. LOAD JSONL UNTUK GT PoT
# ============================================================

def load_pot_ground_truth(jsonl_directory):
    """
    Membaca seluruh JSONL dan membuat mapping:
    
        id -> {
            question,
            final_gt_answer,
            ...
        }
    
    Hanya digunakan untuk mengambil final_gt_answer
    pada sampel PoT.
    """

    pot_gt = {}

    jsonl_files = list(Path(jsonl_directory).glob("*.jsonl"))

    print(f"Found {len(jsonl_files)} JSONL files")

    for jsonl_file in sorted(jsonl_files):

        try:
            with open(jsonl_file, "r", encoding="utf-8") as f:

                for line in f:

                    if not line.strip():
                        continue

                    record = json.loads(line)

                    record_id = record.get("id")

                    if record_id is None:
                        continue

                    pot_gt[record_id] = {
                        "question": record.get("question", ""),
                        "final_gt_answer": record.get(
                            "final_gt_answer", ""
                        ),
                        "gt_answer": record.get(
                            "gt_answer", ""
                        )
                    }

        except Exception as e:
            print(f"ERROR reading {jsonl_file.name}: {e}")

    print(f"Loaded {len(pot_gt)} JSONL records")

    return pot_gt

def load_hf_image_mapping():

    print("=" * 80)
    print("Loading Hugging Face test set")
    print("=" * 80)

    dataset = load_dataset(
        HF_DATASET,
        split=HF_SPLIT
    )

    print(f"HF test records : {len(dataset)}")
    print(f"Columns         : {dataset.column_names}")

    image_mapping = {}

    for row in dataset:

        image_id = row.get("id")

        if image_id is None:
            continue

        image_id = os.path.splitext(
            os.path.basename(str(image_id).strip())
        )[0]

        # ----------------------------------------------------
        # Ambil path dari kolom image
        # ----------------------------------------------------

        image_value = row.get("image")

        image_path = None

        if isinstance(image_value, str):

            image_path = image_value

        elif isinstance(image_value, dict):

            # Beberapa dataset HF menyimpan image sebagai:
            # {"path": "...", "bytes": ...}

            image_path = image_value.get("path")

        # ----------------------------------------------------
        # Simpan mapping
        # ----------------------------------------------------

        if image_path:

            image_mapping[image_id] = image_path

    print(
        f"Image path mapping : {len(image_mapping)}"
    )

    return image_mapping

def resolve_local_image_path(image_id, image_mapping):

    image_id = os.path.splitext(
        os.path.basename(str(image_id).strip())
    )[0]

    hf_path = image_mapping.get(image_id)

    if hf_path is None:
        return None

    # Path dari Hugging Face adalah path relatif
    hf_path = str(hf_path).replace("\\", "/").lstrip("/")

    # Join dengan root folder lokal
    local_path = os.path.join(
        IMAGE_ROOT,
        hf_path
    )

    return local_path
    
# ============================================================
# 2. IDENTIFIKASI PoT
# ============================================================

def is_pot_question(question):
    """
    PoT ditentukan berdasarkan adanya instruksi
    'Jawab menggunakan langkah perhitungannya'
    pada pertanyaan.
    """

    question = str(question).strip()

    return POT_SUFFIX.lower() in question.lower()


# ============================================================
# 3. LEVENSHTEIN / STRING SIMILARITY
# ============================================================

def levenshtein_similarity(s1, s2):

    s1 = str(s1)
    s2 = str(s2)

    if not s1 and not s2:
        return 1.0

    if not s1 or not s2:
        return 0.0

    return SequenceMatcher(None, s1, s2).ratio()


# ============================================================
# 4. DETEKSI TIPE JAWABAN
# ============================================================

def is_year(answer_str, question_str):

    answer_str = str(answer_str).strip()
    question_str = str(question_str).lower()

    year_pattern = r"\b(19|20)\d{2}\b"

    return (
        re.search(year_pattern, answer_str) is not None
        and "tahun" in question_str
    )


def is_numeric(answer_str):

    try:
        normalized = normalize_numeric_format(
            answer_str
        )

        float(normalized)

        return True

    except (ValueError, TypeError):
        return False


def get_answer_type(model_answer, gt_answer, question):

    # Year diperiksa lebih dahulu
    if is_year(gt_answer, question):
        return "year"

    # Numeric
    if is_numeric(gt_answer):
        return "numeric"

    # Selain itu text
    return "text"


# ============================================================
# 5. RELAXED ACCURACY
# ============================================================
def compute_relaxed_accuracy(
    model_val,
    gt_val,
    tolerance=0.05
):

    try:

        model_val = normalize_numeric_format(
            model_val
        )

        gt_val = normalize_numeric_format(
            gt_val
        )

        model_num = float(
            str(model_val).strip()
        )

        gt_num = float(
            str(gt_val).strip()
        )

        if gt_num == 0:

            return 1.0 if model_num == 0 else 0.0

        error_rate = (
            abs(model_num - gt_num)
            / abs(gt_num)
        )

        return 1.0 if error_rate <= tolerance else 0.0

    except (ValueError, TypeError):

        return 0.0

# ============================================================
# 6. EXACT MATCH
# ============================================================

def compute_em(model_answer, gt_answer):

    model_str = str(model_answer).strip()
    gt_str = str(gt_answer).strip()

    return 1.0 if model_str == gt_str else 0.0


# ============================================================
# 7. ANLS
# ============================================================

def compute_anls(
    model_answer,
    gt_answer,
    threshold=0.5
):

    model_str = str(model_answer).strip()
    gt_str = str(gt_answer).strip()

    similarity = levenshtein_similarity(
        model_str,
        gt_str
    )

    if similarity >= threshold:
        return similarity

    return 0.0


# ============================================================
# 8. NORMALISASI BOOLEAN
# ============================================================

def normalize_boolean_answer(answer):

    answer = str(answer).strip()

    mapping = {

        "True": "Ya",
        "False": "Tidak",

        "true": "Ya",
        "false": "Tidak",

        "TRUE": "Ya",
        "FALSE": "Tidak",

        "Yes": "Ya",
        "No": "Tidak",

        "yes": "Ya",
        "no": "Tidak",

        "YES": "Ya",
        "NO": "Tidak"
    }

    return mapping.get(answer, answer)

def normalize_closed_answer(answer):
    """
    Mengubah jawaban GPT yang masih berbentuk kalimat menjadi
    closed answer.

    Rules:
    1. Jika diawali Ya/Tidak -> ambil Ya/Tidak.
    2. Jika terdapat teks dalam tanda petik dua -> ambil isi petik.
    3. Jika terdapat pola 'adalah ...' -> ambil jawaban setelah 'adalah'
       dan buang keterangan setelahnya jika memungkinkan.
    4. Jika terdapat pola 'peringkat ...' -> ambil bagian setelahnya.
    5. Jika tidak memenuhi rule -> kembalikan jawaban asli.
    """

    answer = str(answer).strip()

    # --------------------------------------------------------
    # Bersihkan bullet/list di awal
    # --------------------------------------------------------

    answer = re.sub(
        r"^\s*[-•*]\s*",
        "",
        answer
    ).strip()

    # --------------------------------------------------------
    # Rule 1: Ya / Tidak
    # --------------------------------------------------------

    match = re.match(
        r"^(Ya|Tidak)\b",
        answer,
        flags=re.IGNORECASE
    )

    if match:
        return match.group(1).capitalize()

    # --------------------------------------------------------
    # Rule 2: Ambil isi tanda petik dua
    # --------------------------------------------------------

    quoted = re.findall(
        r'"([^"]+)"',
        answer
    )

    if quoted:
        return quoted[-1].strip()

    # --------------------------------------------------------
    # Rule 3: Pola "adalah ..."
    # --------------------------------------------------------

    match = re.search(
        r"\badalah\s+(.+)",
        answer,
        flags=re.IGNORECASE | re.DOTALL
    )

    if match:

        result = match.group(1).strip()

        # Kalau hasilnya memiliki koma/keterangan lanjutan,
        # coba ambil bagian pertama.
        result = re.split(
            r"\s+(?:dengan|yang|sebesar|yaitu)\s+",
            result,
            maxsplit=1,
            flags=re.IGNORECASE
        )[0]

        # Bersihkan tanda baca akhir
        result = result.strip(" .,:;")

        if result:
            return result

    # --------------------------------------------------------
    # Rule 4: Pola "peringkat ..."
    # --------------------------------------------------------

    match = re.search(
        r"\bperingkat(?:nya)?\s+(?:adalah\s+)?(.+)",
        answer,
        flags=re.IGNORECASE | re.DOTALL
    )

    if match:

        result = match.group(1).strip()

        result = re.split(
            r"\s+(?:dengan|yang|sebesar|yaitu)\s+",
            result,
            maxsplit=1,
            flags=re.IGNORECASE
        )[0]

        result = result.strip(" .,:;")

        if result:
            return result

    # --------------------------------------------------------
    # Tidak memenuhi rule
    # --------------------------------------------------------

    return answer
# ============================================================
# 9. RESOLVE PoT GPT
# ============================================================

def resolve_pot_answer(answer):

    """
    Mengubah script PoT menjadi final answer.

    Contoh:

    <comment>...</comment>
    <step>vals = [...]</step>
    <step>mean_val = np.mean(vals)</step>
    <step>Answer = mean_val</step>

    menjadi:

    2.1725
    """

    answer = str(answer).strip()

    # Hapus comment
    answer = re.sub(
        r"<comment>.*?</comment>",
        "",
        answer,
        flags=re.DOTALL
    )

    # Hapus tag step
    answer = answer.replace("<step>", "")
    answer = answer.replace("</step>", "\n")

    answer = answer.strip()

    # --------------------------------------------------------
    # Safe environment
    # --------------------------------------------------------

    safe_globals = {
        "__builtins__": {
            "all": all,
            "any": any,
            "len": len,
            "min": min,
            "max": max,
            "abs": abs,
            "round": round,
            "float": float,
            "int": int,
            "str": str,
            "sum": sum
        },

        "np": np
    }

    safe_locals = {}

    try:

        exec(
            answer,
            safe_globals,
            safe_locals
        )

        result = safe_locals.get(
            "Answer",
            None
        )

        if result is None:

            return None, "FAILED_NO_ANSWER"

        # numpy array
        if isinstance(result, np.ndarray):

            if result.size == 1:
                result = result.item()

            else:
                result = result.tolist()

        # numpy scalar
        elif isinstance(result, np.generic):

            result = result.item()

        return str(result).strip(), "SUCCESS"

    except Exception as e:

        return (
            None,
            f"FAILED_EXECUTION: {type(e).__name__}: {e}"
        )


# ============================================================
# 10. EVALUASI SATU SAMPLE
# ============================================================

def score_sample(
    model_answer,
    gt_answer,
    question
):

    answer_type = get_answer_type(
        model_answer,
        gt_answer,
        question
    )

    # --------------------------------------------------------
    # NUMERIC
    # --------------------------------------------------------

    if answer_type == "numeric":

        relaxed_acc = compute_relaxed_accuracy(
            model_answer,
            gt_answer
        )

        return {
            "score": relaxed_acc,
            "answer_type": "numeric",
            "metric_used": "Relaxed Accuracy",
            "em": None,
            "anls": None,
            "relaxed_acc": relaxed_acc
        }

    # --------------------------------------------------------
    # YEAR
    # --------------------------------------------------------

    elif answer_type == "year":

        em = compute_em(
            model_answer,
            gt_answer
        )

        return {
            "score": em,
            "answer_type": "year",
            "metric_used": "EM",
            "em": em,
            "anls": None,
            "relaxed_acc": None
        }

    # --------------------------------------------------------
    # TEXT
    # --------------------------------------------------------

    else:

        em = compute_em(
            model_answer,
            gt_answer
        )

        anls = compute_anls(
            model_answer,
            gt_answer
        )

        if em == 1.0:

            score = 1.0
            metric_used = "EM"

        elif anls > 0:

            score = anls
            metric_used = "ANLS"

        else:

            score = 0.0
            metric_used = "None"

        return {
            "score": score,
            "answer_type": "text",
            "metric_used": metric_used,
            "em": em,
            "anls": anls,
            "relaxed_acc": None
        }


# ============================================================
# 11. EKSTRAK ID DARI IMAGE
# ============================================================

def extract_id_from_image(image):

    """
    Mengubah nama image menjadi ID JSONL.

    Contoh:

    B115BARAverage_1.png
        ->
    B115BARAverage_1
    """

    image = str(image).strip()

    # Ambil basename
    image = os.path.basename(image)

    # Hilangkan extension
    image_id = os.path.splitext(image)[0]

    return image_id

def normalize_numeric_format(answer):
    """
    Menyamakan format desimal.
    
    Contoh:
    2,1725 -> 2.1725
    1,23   -> 1.23
    -3,28  -> -3.28
    
    Tidak mengubah angka yang sudah menggunakan titik.
    """

    answer = str(answer).strip()

    # Jika koma digunakan sebagai desimal
    if re.fullmatch(r"-?\d+,\d+", answer):
        answer = answer.replace(",", ".")

    return answer
# ============================================================
# 12. MAIN EVALUATION
# ============================================================

def evaluate_gpt():

    # --------------------------------------------------------
    # Load CSV
    # --------------------------------------------------------

    df = pd.read_csv(
        CSV_PATH
    )

    print("=" * 80)
    print("GPT-4o-mini EVALUATION")
    print("=" * 80)

    print(f"Total CSV records : {len(df)}")

    image_mapping = load_hf_image_mapping()

    # --------------------------------------------------------
    # Load JSONL GT
    # --------------------------------------------------------

    pot_gt = load_pot_ground_truth(
        JSONL_DIR
    )

    results = []

    # --------------------------------------------------------
    # Process every sample
    # --------------------------------------------------------

    for idx, row in df.iterrows():

        image = row["image"]
        question = str(row["question"]).strip()

        csv_gt = row["ground_truth"]

        gpt_raw = row["gpt4o_mini_answer"]

        # ----------------------------------------------------
        # Tentukan PoT
        # ----------------------------------------------------

        pot = is_pot_question(question)

        # ----------------------------------------------------
        # ID untuk mencari JSONL
        # ----------------------------------------------------

        image_id = extract_id_from_image(
            image
        )
        
        local_image_path = resolve_local_image_path(
            image_id,
            image_mapping
        )
        # ----------------------------------------------------
        # PoT
        # ----------------------------------------------------
        if pot:

            # GT berasal dari JSONL
            jsonl_record = pot_gt.get(image_id)

            if jsonl_record is None:

                print(
                    f"WARNING: JSONL GT tidak ditemukan "
                    f"untuk {image_id}"
                )

                gt_answer = None

            else:

                gt_answer = jsonl_record["final_gt_answer"]

            # GPT masih berupa script
            resolved_answer, resolve_status = (
                resolve_pot_answer(gpt_raw)
            )

            if resolved_answer is None:
                resolved_answer = ""

            # PoT hasil resolve sudah berupa final answer,
            # jadi TIDAK perlu normalize_closed_answer()
            # karena bisa merusak angka/jawaban yang valid.

        # ----------------------------------------------------
        # Non-PoT
        # ----------------------------------------------------

        else:

            # GT langsung dari CSV
            gt_answer = csv_gt

            # GPT sudah final
            resolved_answer = gpt_raw

            resolve_status = "NOT_POT"

            # Ubah jawaban GPT yang masih berupa kalimat
            # menjadi closed answer
            resolved_answer = normalize_closed_answer(
                resolved_answer
            )

        # ----------------------------------------------------
        # Normalisasi format numeric
        # Berlaku untuk PoT DAN Non-PoT
        # ----------------------------------------------------

        resolved_answer = normalize_numeric_format(
            resolved_answer
        )

        if gt_answer is not None:

            gt_answer = normalize_numeric_format(
                gt_answer
            )

        # ----------------------------------------------------
        # Normalisasi boolean
        # ----------------------------------------------------

        resolved_answer = normalize_boolean_answer(
            resolved_answer
        )

        if gt_answer is not None:

            gt_answer = normalize_boolean_answer(
                gt_answer
            )
            
        # ----------------------------------------------------
        # Score
        # ----------------------------------------------------

        if gt_answer is None:

            metrics = {
                "score": np.nan,
                "answer_type": None,
                "metric_used": "GT_NOT_FOUND",
                "em": None,
                "anls": None,
                "relaxed_acc": None
            }

        else:

            metrics = score_sample(
                resolved_answer,
                gt_answer,
                question
            )

        # ----------------------------------------------------
        # Simpan result
        # ----------------------------------------------------

        results.append({

            "image": image,

            "image_id": image_id,
            "image_path": local_image_path,
            "question": question,

            "is_pot": pot,

            "raw_model_answer": gpt_raw,

            "resolved_model_answer": resolved_answer,

            "ground_truth": gt_answer,

            "resolve_status": resolve_status,

            "answer_type": metrics[
                "answer_type"
            ],

            "metric_used": metrics[
                "metric_used"
            ],

            "score": metrics[
                "score"
            ],

            "relaxed_acc": metrics[
                "relaxed_acc"
            ],

            "em": metrics[
                "em"
            ],

            "anls": metrics[
                "anls"
            ]
        })

    # --------------------------------------------------------
    # DataFrame
    # --------------------------------------------------------

    result_df = pd.DataFrame(
        results
    )

    # --------------------------------------------------------
    # Save detailed result
    # --------------------------------------------------------

    # ========================================================
    # SAVE TO XLSX + EMBED IMAGE
    # ========================================================
    
    result_df.to_excel(
        OUTPUT_PATH,
        index=False
    )
    
    # --------------------------------------------------------
    # Buka workbook
    # --------------------------------------------------------
    
    wb = load_workbook(OUTPUT_PATH)
    ws = wb.active
    
    # --------------------------------------------------------
    # Buat kolom Image di paling kiri
    # --------------------------------------------------------
    
    ws.insert_cols(1)
    ws.cell(row=1, column=1).value = "Image"
    
    # --------------------------------------------------------
    # Masukkan gambar ke setiap row
    # --------------------------------------------------------
    
    TEMP_IMAGE_DIR = "/kaggle/working/compressed_images"
    os.makedirs(TEMP_IMAGE_DIR, exist_ok=True)
    
    for excel_row in range(2, len(result_df) + 2):
    
        image_path = result_df.iloc[
            excel_row - 2
        ]["image_path"]
    
        if (
            image_path is None
            or not os.path.exists(image_path)
        ):
            continue
    
        try:
    
            # Buka gambar asli
            img = Image.open(image_path)
    
            # Resize maksimal 600 x 400
            img.thumbnail(
                (600, 400),
                Image.Resampling.LANCZOS
            )
    
            # Path gambar hasil kompresi
            compressed_path = os.path.join(
                TEMP_IMAGE_DIR,
                f"image_{excel_row}.jpg"
            )
    
            # Convert ke RGB untuk JPEG
            if img.mode in ("RGBA", "LA", "P"):
                img = img.convert("RGB")
            else:
                img = img.convert("RGB")
    
            # Simpan JPEG terkompresi
            img.save(
                compressed_path,
                format="JPEG",
                quality=70,
                optimize=True
            )
    
            # Masukkan gambar hasil kompresi ke Excel
            excel_img = XLImage(
                compressed_path
            )
    
            excel_img.width = 300
            excel_img.height = 200
    
            ws.add_image(
                excel_img,
                f"A{excel_row}"
            )
    
            ws.row_dimensions[
                excel_row
            ].height = 155
    
        except Exception as e:
    
            print(
                f"ERROR embedding image "
                f"row {excel_row}: {e}"
            )
    # --------------------------------------------------------
    # Lebar kolom
    # --------------------------------------------------------
    
    ws.column_dimensions["A"].width = 45
    
    for col in range(2, ws.max_column + 1):
    
        column_letter = get_column_letter(col)
    
        if column_letter == "B":
            ws.column_dimensions[
                column_letter
            ].width = 25
    
        elif column_letter == "C":
            ws.column_dimensions[
                column_letter
            ].width = 70
    
        else:
            ws.column_dimensions[
                column_letter
            ].width = 25
    
    # --------------------------------------------------------
    # Freeze header
    # --------------------------------------------------------
    
    ws.freeze_panes = "A2"
    
    # --------------------------------------------------------
    # Save
    # --------------------------------------------------------
    
    wb.save(OUTPUT_PATH)
    
    print(
        f"\n✓ XLSX saved to:\n{OUTPUT_PATH}"
    )

    # ========================================================
    # SUMMARY
    # ========================================================

    print("\n" + "=" * 80)
    print("SUMMARY")
    print("=" * 80)

    print(
        f"Total samples : {len(result_df)}"
    )

    print(
        f"PoT samples   : {result_df['is_pot'].sum()}"
    )

    print(
        f"Non-PoT       : {(~result_df['is_pot']).sum()}"
    )

    # --------------------------------------------------------
    # Overall score
    # --------------------------------------------------------

    valid_scores = result_df[
        result_df["score"].notna()
    ]["score"]

    print(
        f"\nOverall Score : {valid_scores.mean():.4f}"
    )

    # --------------------------------------------------------
    # PoT score
    # --------------------------------------------------------

    pot_scores = result_df[
        result_df["is_pot"] &
        result_df["score"].notna()
    ]["score"]

    nonpot_scores = result_df[
        ~result_df["is_pot"] &
        result_df["score"].notna()
    ]["score"]

    print(
        f"PoT Score     : {pot_scores.mean():.4f}"
    )

    print(
        f"Non-PoT Score : {nonpot_scores.mean():.4f}"
    )

    # --------------------------------------------------------
    # Breakdown answer type
    # --------------------------------------------------------

    print("\n===== ANSWER TYPE =====")

    print(
        result_df[
            "answer_type"
        ].value_counts()
    )

    # --------------------------------------------------------
    # Breakdown metric
    # --------------------------------------------------------

    print("\n===== METRIC =====")

    print(
        result_df[
            "metric_used"
        ].value_counts()
    )

    # --------------------------------------------------------
    # Failed PoT
    # --------------------------------------------------------

    failed_pot = result_df[
        result_df["is_pot"] &
        (
            result_df[
                "resolve_status"
            ] != "SUCCESS"
        )
    ]

    print(
        f"\nFailed PoT resolution : "
        f"{len(failed_pot)}"
    )

    if len(failed_pot) > 0:

        print(
            failed_pot[
                [
                    "image",
                    "resolve_status",
                    "raw_model_answer"
                ]
            ].to_string(index=False)
        )

    print(
        f"\n✓ Detailed results saved to:"
        f"\n{OUTPUT_PATH}"
    )

    return result_df


# ============================================================
# RUN
# ============================================================

if __name__ == "__main__":
    result_df = evaluate_gpt()

================================================================================
GPT-4o-mini EVALUATION
================================================================================
Total CSV records : 500
================================================================================
Loading Hugging Face test set
================================================================================
HF test records : 11830
Columns         : ['id', 'image', 'conversations']
Image path mapping : 11830
Found 1337 JSONL files
Loaded 11830 JSONL records

✓ XLSX saved to:
/kaggle/working/evaluation_gpt4o_mini_500.xlsx

================================================================================
SUMMARY
================================================================================
Total samples : 500
PoT samples   : 100
Non-PoT       : 400

Overall Score : 0.6018
PoT Score     : 0.5656
Non-PoT Score : 0.6108

===== ANSWER TYPE =====
answer_type
text       256
numeric    238
year         6
Name: count, dtype: int64

===== METRIC =====
metric_used
Relaxed Accuracy    238
None                 97
ANLS                 93
EM                   72
Name: count, dtype: int64

Failed PoT resolution : 6
            image                                                   resolve_status                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  raw_model_answer
 B33GBARRanking_8        FAILED_EXECUTION: NameError: name 'sorted' is not defined                                                                                                                                                                                                                                                                                                                                              <comment># Menghitung total produksi Mangga untuk setiap kecamatan</comment>\n<step>total_produksi_mangga = {'Gerogak': 76507, 'Seririt': 100358, 'Busungbiu': 1929.20, 'Banjar': 10282, 'Sukasada': 4564, 'Buleleng': 47300, 'Sawan': 11630, 'Kubutambahan': 133036.54, 'Tejakula': 24730}</step>\n<comment># Mengurutkan kecamatan berdasarkan total produksi Mangga dari yang tertinggi ke terendah</comment>\n<step>sorted_kecamatan = sorted(total_produksi_mangga.items(), key=lambda x: x[1], reverse=True)</step>\n<comment># Mengambil dua kecamatan dengan produksi Mangga tertinggi</comment>\n<step>top_two_kecamatan = sorted_kecamatan[:2]</step>\n<comment># Menyimpan hasil akhir</comment>\n<step>Answer = top_two_kecamatan</step>
 S106BARRanking_1 FAILED_EXECUTION: SyntaxError: invalid syntax (<string>, line 1) <comment># Menginisialisasi nilai tukar petani untuk setiap subsektor</comment>\n<subsector_values> = [110, 102, 110, 98, 113]\n\n<comment># Menginisialisasi nama subsektor yang sesuai dengan nilai tukar petani</comment>\n<subsector_names> = ["Tanaman Pangan", "Tanaman Hortikultura", "Tanaman Perkebunan Rakyat", "Peternakan", "Perikanan"]\n\n<comment># Mengurutkan nilai tukar petani dan mendapatkan indeks urutan</comment>\n<sorted_indices> = np.argsort(<subsector_values>)[::-1]\n\n<comment># Mengambil nama subsektor berdasarkan urutan yang telah diurutkan</comment>\n<sorted_subsectors> = [<subsector_names>[i] for i in <sorted_indices>]\n\n<comment># Mengambil nilai tukar petani berdasarkan urutan yang telah diurutkan</comment>\n<sorted_values> = [<subsector_values>[i] for i in <sorted_indices>]\n\n<comment># Menggabungkan nama subsektor dan nilai tukar petani dalam format yang diinginkan</comment>\n<result> = list(zip(<sorted_subsectors>, <sorted_values>))\n\n<comment># Menyimpan hasil akhir dalam variabel Answer</comment>\nAnswer = <result>
S56GBARRanking_16 FAILED_EXECUTION: SyntaxError: invalid syntax (<string>, line 1)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   <comment># Mendefinisikan nilai Indeks Pendapatan Kini untuk setiap triwulan</comment>\n<triwulan_I> = 115\n<triwulan_II> = 139\n<triwulan_III> = 119\n<triwulan_IV> = 116\n\n<comment># Mengumpulkan semua nilai Indeks Pendapatan Kini dalam sebuah list</comment>\n<pendapatan_kini> = [triwulan_I, triwulan_II, triwulan_III, triwulan_IV]\n\n<comment># Mengurutkan nilai Indeks Pendapatan Kini dari terbesar ke terkecil</comment>\n<sorted_pendapatan> = np.sort(pendapatan_kini)[::-1]\n\n<comment># Menyimpan hasil akhir dalam variabel Answer</comment>\nAnswer = sorted_pendapatan
S57GBARRanking_14 FAILED_EXECUTION: SyntaxError: invalid syntax (<string>, line 1)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <comment># Mengumpulkan nilai Indeks Pengaruh Inflasi terhadap Konsumsi untuk setiap triwulan</comment>\n<triwulan_values> = [95, 110, 102, 108]\n\n<comment># Mengurutkan nilai dari terbesar ke terkecil</comment>\n<sorted_values> = np.sort(triwulan_values)[::-1]\n\n<comment># Menyimpan hasil akhir dalam variabel Answer</comment>\nAnswer = sorted_values
    S281LINEMin_1            FAILED_EXECUTION: IndexError: list index out of range                                                                                                                                                                                                                                                                   <comment># Mendefinisikan nilai inflasi bulanan untuk setiap bulan</comment>\n<step>inflasi = [-0.01, 0.02, -0.04, 0.01, 0.02, 0, 0.05, 0.02, 0.01, -0.01, -0.01, 0.01, -0.06]</step>\n<comment># Mencari nilai inflasi terkecil</comment>\n<step>min_inflasi = np.min(inflasi)</step>\n<comment># Mencari indeks bulan dengan inflasi terkecil</comment>\n<step>indeks_bulan = np.argmin(inflasi)</step>\n<comment># Menyimpan nama bulan dalam list</comment>\n<step>nama_bulan = ["Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "September", "Oktober", "November", "Desember"]</step>\n<comment># Menentukan bulan dengan inflasi terkecil</comment>\n<step>bulan_terkecil = nama_bulan[indeks_bulan]</step>\n<comment># Menyimpan hasil akhir</comment>\n<step>Answer = bulan_terkecil</step>
 S418BARRanking_1        FAILED_EXECUTION: NameError: name 'sorted' is not defined                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 <comment># Mengumpulkan data inflasi dari setiap kabupaten/kota</comment>\n<step>inflasi = {'Kota Pare-Pare': -1, 'Kabupaten Wajo': -1, 'Kabupaten Luwu Timur': -1, 'Watampone': -2, 'Kabupaten Sidenereng Rappang': -2, 'Bulukumba': -2, 'Kota Makassar': -2, 'Kota Palopo': -2}</step>\n<comment># Mengurutkan kabupaten/kota berdasarkan nilai inflasi dari yang terbesar ke yang terkecil</comment>\n<step>sorted_inflasi = sorted(inflasi.items(), key=lambda x: x[1])</step>\n<comment># Menyimpan hasil urutan dalam variabel Answer</comment>\n<step>Answer = [item[0] for item in sorted_inflasi]</step>

✓ Detailed results saved to:
/kaggle/working/evaluation_gpt4o_mini_500.xlsx

In [17]:
import os
import json
from pathlib import Path
import pandas as pd

CSV_PATH = "/kaggle/input/datasets/dianshinta09/mygptresult/gpt4o_mini_results_500.csv"
EVAL_DIR = "/kaggle/input/datasets/dianshinta09/evaluation-result-tinycart/eval"

POT_SUFFIX = "Jawab menggunakan langkah perhitungannya"

# ============================================================
# LOAD CSV 500 SAMPLE
# ============================================================

df = pd.read_csv(CSV_PATH)

# ============================================================
# LOAD ALL EVALUATION JSONL
# ============================================================

eval_mapping = {}

for jsonl_file in Path(EVAL_DIR).rglob("*.jsonl"):
    with open(jsonl_file, "r", encoding="utf-8") as f:
        for line in f:
            if not line.strip():
                continue

            record = json.loads(line)
            record_id = record.get("id")

            if record_id is None:
                continue

            record_id = os.path.splitext(
                os.path.basename(str(record_id).strip())
            )[0]

            eval_mapping[record_id] = record

# ============================================================
# MATCH 500 SAMPLE
# ============================================================

results = []

for _, row in df.iterrows():

    image_id = os.path.splitext(
        os.path.basename(str(row["image"]).strip())
    )[0]

    record = eval_mapping.get(image_id)

    if record is None:
        continue

    score = record.get("score")

    if score is None:
        continue

    question = record.get("question", "")

    results.append({
        "image_id": image_id,
        "score": float(score),
        "pot": POT_SUFFIX in question
    })

result_df = pd.DataFrame(results)

# ============================================================
# RESULT
# ============================================================

print("=" * 60)
print("TINYCHART FINETUNED - 500 SAMPLE")
print("=" * 60)

print(f"Matched scored samples : {len(result_df)}")

overall_score = result_df["score"].mean()
pot_score = result_df.loc[result_df["pot"], "score"].mean()
nonpot_score = result_df.loc[~result_df["pot"], "score"].mean()

print(f"\nAverage Score          : {overall_score:.4f}")
print(f"Average Score PoT      : {pot_score:.4f}")
print(f"Average Score Non-PoT  : {nonpot_score:.4f}")

print("\nJumlah:")
print(f"PoT     : {result_df['pot'].sum()}")
print(f"Non-PoT : {(~result_df['pot']).sum()}")

============================================================
TINYCHART FINETUNED - 500 SAMPLE
============================================================
Matched scored samples : 500

Average Score          : 0.6381
Average Score PoT      : 0.5209
Average Score Non-PoT  : 0.6674

Jumlah:
PoT     : 100
Non-PoT : 400